### ISSUE TITLE
Precompiled App Bundle not working on OS X 10.10  

### ISSUE THREAD

**Issue by mickelson** [mickelson/attract#101]
http://forum.attractmode.org/index.php?topic=57.msg256#msg256

I don't have access to 10.10 so I'm unable to investigate

**Comment by sprive** [comment]
Is there anything one can do to help troubleshoot this or gather information? (Context: I'm a Python developer, but I can follow steps in Xcode if they are detailed steps).

I can confirm, even if I bypass Gatekeeper, the app does not open when double-clicked (the desktop does the "zoom in swoosh" on the icon, so I know my double click was effective).

**Comment by mickelson** [comment]
Awesome, thanks this helps a lot, I think I know what it is now! 

It's not 10.10 specific but rather it looks like I messed up bundling the recently added network functionality.

I'll try rebuilding and if you could test that would be great

**Comment by mickelson** [comment]
Hi could you try re-downloading the OS X bundle for 1.4 and let me know if it works now?  Thanks

**Comment by sprive** [comment]
Confirming - it loads, and I can choose language and additional configuration.
This was just a quick test, but I think you fixed it, TY. Awesome!


This is a really nice looking emulator GUI, so I'm jazzed to set it up.
For maybe 2 years I've been lamenting the state of OSX emulation GUIs (not sure how I failed to locate this app on my previous searches. I found it somewhat by accident).

**Comment by mickelson** [comment]
That's great!  I hope it works out for you, I haven't used the OS X version much at all myself so let me know if you run into any other problems...
