### ISSUE TITLE
texture_width & texture_height equals 0

### ISSUE THREAD

**Issue by ghost** [mickelson/attract#105]
Hi,

Writing a custom layout, i was interested in doing this : resizing an image, preserving it's aspect ratio and center it (vertically & horizontally) in a fixed rectangle.

Unfortunately, texture_width & texture_height seems to always returns "0". So i wasn't able to compute the dimensions nor the aspect ratio of the image (same problem with videos).

Using the option "preserve_aspect_ratio" works has expected but since i dont have access to the resulting width & height of the scaled image it is not possible to center it vertically & horizontally.

Am i missing something here? I think texture_width always returning 0 might not be the correct behavior.
Thanks

**Comment by mickelson** [comment]
The problem you are running into is that you are trying to get the texture width/height before an image has actually been loaded.  This happens with artworks, which only get loaded after the layout script is done running.

The solution is to do your resizing during the transition when an image has been loaded.  add something like this to your script:

''' squirrel

fe.add_transition_callback("artwork_transition");
function artwork_transition( ttype, var, ttime )
{
   if ( ttype != Transition.FromOldSelection )
      return false;

   // do the centering stuff here


   return false;
}
