### ISSUE TITLE
Linux-to-Windows cross-compilation fails due to missing sfml package

### ISSUE THREAD

**Issue by digitalhobbit** [mickelson/attract#108]
I'm trying to cross-compile from Linux to Windows (64 bit), following the instructions in Compile.md.

I built a full MXE setup, including sfml. I then tried to build attract with the following command:

```make WINDOWS_STATIC=1 CROSS=x86_64-w64-mingw32-```

During compilation, I receive the error message below multiple times:

```
Package sfml was not found in the pkg-config search path.
Perhaps you should add the directory containing `sfml.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sfml' found
```

At the end, the linker fails with many undefined sfml references such as this one:

```
obj/fe_input.o:fe_input.cpp:(.text+0x8da): undefined reference to `sf::Joystick::isButtonPressed(unsigned int, unsigned int)'
```

Even though sfml is installed with MXE, I can't find a sfml.pc file anywhere. Not sure if this is expected or a problem with the sfml MXE package.

I found a few references to sfml / MXE requiring some special settings, but it looks like your Makefile already addresses this.

Any pointers?

I haven't tried building the 32-bit version yet (which would entail another lengthy MXE build first...), but that's the next thing I'm planning to try.

Thanks,

-Mirko

**Comment by digitalhobbit** [comment]
Update: I'm getting exactly the same errors with the 32 bit build (```make WINDOWS_STATIC=1 CROSS=i686-pc-mingw32-```).

**Comment by TimothyGu** [comment]
Also, the same file is not present in Ubuntu either: http://packages.ubuntu.com/search?suite=vivid&arch=any&mode=exactfilename&searchon=contents&keywords=sfml.pc

There are, however, [pkg-config files for each SFML library and an "-all" file](http://packages.ubuntu.com/vivid/amd64/libsfml-dev/filelist):

```
/usr/lib/x86_64-linux-gnu/pkgconfig/sfml-all.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/sfml-audio.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/sfml-graphics.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/sfml-network.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/sfml-system.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/sfml-window.pc
```

**Comment by mickelson** [comment]
I bet it is because I updated my sfml in mxe to the master branch without noting it in the instructions.  If you run the following in your mxe dir and then rebuild mxe's sfml does it fix this?:

git checkout master -- src/sfml.mk

**Comment by digitalhobbit** [comment]
Thanks for the hints.

In fact I was already in the process of building the master version of MXE (not just SFML). After that, I just tried rebuilding Attract Mode with the new MXE default target (```i686-w64-mingw32.static```), and it built successfully this time!

I also briefly tried it on Windows, and I can confirm that it works just fine. :)

So perhaps just update the instructions to suggest using the MXE master branch (rather than stable)? Of course that carries some risk, so perhaps just updating the single sfml package to master is the safer way to go.

**Comment by TimothyGu** [comment]
@digitalhobbit said:

> Of course that carries some risk, so perhaps just updating the single sfml package to master is the safer way to go.

In my experiences master branch is much more stable because it is actually (half-)maintained.

We always try to fix bugs in stable branch as a top priority but it's not completely possible these days as most of @mxe are busy.

**Comment by digitalhobbit** [comment]
Good to know, Timothy. Then using MXE master seems like the way to go.

**Comment by carlmart** [comment]
What does your cmake file or makefile look like? I am trying to build a demo sfml program.
I posted my cmake file, just do not know how to add sfml libraries http://pastebin.com/XeML0gQ6

**Comment by mickelson** [comment]
I think this one is resolved.  compile.md was updated to direct people to use MXE master
