### ISSUE TITLE
-c and --config not working well

### ISSUE THREAD

**Issue by rogalian** [mickelson/attract#110]
If I launch attract.exe and point to its configuration dir with -c:
c:\attractmode\attract.exe -c c:\attractmode

Then snaps/videos/etc are not displayed, nor can I access any emulator configuration.

**Comment by mickelson** [comment]
This all sounds like stuff that uses the emulator cfgs and should be fixed with: https://github.com/mickelson/attract/commit/f9250a0218da82645abb7ec308e16983ab21587a

**Comment by mickelson** [comment]
As a workaround for now, I think you could just add a trailing slash to your command line where you specify the config directory.  What's going on in 1.5.0 is the emulator config path isn't going through the "path cleaning" routine which substitutes $HOME etc and makes sure there is a trailing slash:

c:\attractmode\attract.exe -c c:\attractmode\

**Comment by rogalian** [comment]
Ooh, great, will give it a try!

**Comment by mickelson** [comment]
This was fixed with 1.5.1
