### ISSUE TITLE
1.5.1 build for OSX is broken

### ISSUE THREAD

**Issue by yacoob** [mickelson/attract#111]
Looks like a repeat of #101. The build for OSX for version 1.5.1 crashes with:

```
dyld: Library not loaded: /usr/local/lib/libsfml-graphics.2.1.dylib
  Referenced from: /Applications/Attract.app/Contents/./MacOS/attract
  Reason: image not found
```

1.5.0 works fine.

**Comment by mickelson** [comment]
ack, I keep missing a step in the build.  I'll fix this asap, thanks for the report

**Comment by mickelson** [comment]
Ok, this should be fixed now if you re-download the OS X app bundle for 1.5.1...

**Comment by yacoob** [comment]
Confirmed, works fine. Thanks for a quick fix :)
