### ISSUE TITLE
Suggestion : Artwork for filter/list themselves

### ISSUE THREAD

**Issue by checkist84** [mickelson/attract#119]
While this can be achievable through gross hack in layout.nut, I think it would be nice to add this as standard feature...

What I suggest is that filter, and list themselves can also have associated artworks (movie, picture), that are accessible in layout script as:

  fe.add_artwork([filter_artwork]);
  fe.add_artwork([list_artwork]);
  : for use in layouts, just as other artwork resources

  fe.CurrentList.artwork
  fe.Filter.artwork
  : updated containers for these artworks. related attributes like video_flags, file_name may be added as well

The configuration can be included in emulator's cfgs, like 
    filter_artwork          ...
or 
    artwork   filter        ...

**Comment by mickelson** [comment]
This can be achieved now I believe with the work that was done to resolve Issue #130
