### ISSUE TITLE
Plug-In Request: Search

### ISSUE THREAD

**Issue by millercentral** [mickelson/attract#120]
Typically my front-end is showing a limited filter of games from the RomList, but occasionally I want to play something specific without scrolling through thousands of games in the All list. it would be great to have a plug in to Search for a specific game.

When invoked, the Search plug in would popup a new overlay window with a virtual keyboard (in a perfect world, you could choose between a horizontal line keyboard, or 5x6 style grid keyboard), moving between letters and selecting with a button press. With each character added to the string, a list is returned of matching games (searching against Name and filename). Selecting an item from the list of results could show a bit more info (like artwork, year, manufacturer, working status), and allow you to launch the game, or add it to favorites.

Thoughts?

**Comment by mickelson** [comment]
sounds like a good idea to me!

**Comment by liquid8d** [comment]
I'd really like to be able to do this.. I'd probably put in the time to make something nice via module/plugin - but there is currently no way to modify the current list/filter/rules via code.

Perhaps if we have a way to create/apply a filter and add rules to it in squirrel this could be done.

**Comment by liquid8d** [comment]
I put some time into creating a basic search interface:

![Search config](http://i.imgur.com/fUhYsb6.png)

![Search overlay](http://i.imgur.com/2PB6yZL.png)

Again though, as far as I can tell there isn't a way to modify filters/rules. To do a search interface, I'm thinking we need to be able to create/apply a filter/rule, something like fe.apply_rule("Title contains xxxx"); and it would apply that rule to the current filter/list.

I'm not very good with c++, but I was looking through the code anyways :) I was a little confused on how this could be done. I found the FeFilter and FeRule classes in fe_info.cpp, I see that you can bind functions to the fe table in fe_vm.cpp. I *think* FeSettings::get_rom_info creates the list based on the filter index, so perhaps we'd need to add a new filter to the array and remove it when done - or maybe we can add a rule to the current filter index and remove it when done. I'll keep working on it, and if I can figure it out submit a patch.

**Comment by mickelson** [comment]
At one point I thought about doing something that sounds exactly like what you are thinking @liquid8d : having something like an fe.apply_rule() which could set a temporary additional rule for the current list, which would allow for a search plugin that shows its results in the game list.

I did start work on a more basic approach to searching, and got as far as implementing a keyboard search which will keep the existing list but jump the selection to the next entry that contains the search term.  It's posted here: https://gist.github.com/mickelson/a6a79362224986729627
It needs a keyboard to work, so no joystick only controls (yet)

If you are digging into the code, you should look at fe_romlist.hpp/cpp as well (the FeRomList class).  FeRomList contains the actual romlist, and has a m_filtered_list member that contains the mappings into the romlist entries for each of the filters.  It sounds like what you are thinking of would involve rebuilding/replacing entries in m_filtered_list for the current filter.

**Comment by mickelson** [comment]
Ok, I've had a go at this one, the frontend functionality needed for search plugins should be implemented now:

https://github.com/mickelson/attract/commit/8c208aad327fc4c03541c42ed27b3708827790ae

**Comment by liquid8d** [comment]
Awesome! I'll take a look and see how you added it. I'll work on getting my OSD keyboard implemented into the plugin :)

**Comment by liquid8d** [comment]
Working pretty good! Have a few glitches right now, but it's probably just my regex implementation or something else screwing some things up.

With my approach, I don't use the overlay dialog.. I hook a signal handler and ontick and the search is drawn to its own surface allowing me to create a custom search screen. I have different onscreen keyboard layout configurations which can be themeable. Still need to implement typing.

![search1](https://cloud.githubusercontent.com/assets/3782076/10422288/43b470be-7086-11e5-9148-51a9e1c84014.png)

![search2](https://cloud.githubusercontent.com/assets/3782076/10422290/474054c8-7086-11e5-9ba4-fe585dcd18f8.png)

**Comment by liquid8d** [comment]
You can probably close this issue in light of "search_rule" being implemented.

Also, I have an onscreen keyboard search module working, now really just need to convert mine to a plugin that could replace the current keyboard only one.
