### ISSUE TITLE
FE in Squirrel Generators and Coroutines?

### ISSUE THREAD

**Issue by h0tw1r3** [mickelson/attract#123]
Would it be possible to provide a simple example of using coroutines or generators and the fe methods?

So far I've only been able to make attractmode crash.

**Comment by mickelson** [comment]
Sorry I lost track of this issue.  I have never used coroutines or generators myself, so I don't have any examples of how to use them.  In theory I think they should work just fine and only be as crash prone as anything else (for loops, recursion, etc)...
