### ISSUE TITLE
Feature request: Enable SWF animation playback

### ISSUE THREAD

**Issue by millercentral** [mickelson/attract#125]
Allow theme designers to take advantage of more assets from HyperSpin themes (and build animations without custom Squirrel code) by enabling SWF animation file playback within attractmode. There is a cross-platform, public domain library for SWF animations called GameSWF (http://tulrich.com/geekstuff/gameswf.html) that might be helpful here.

**Comment by mickelson** [comment]
An early 'alpha' quality gameswf integration is available here: https://github.com/mickelson/attract/tree/swf

swf files can be loaded just like any other image.  there is still plenty to do (currently no sound, etc.)
