### ISSUE TITLE
FadeArt doesn't work with UNC artwork paths

### ISSUE THREAD

**Issue by CapnBry** [mickelson/attract#127]
I was checking out the new Reflect layout and none of my snap images were loading. They work fine with other layouts though. If I made the following modification then they'd work again:
~~~
// instead of this
local snap = FadeArt( "snap", 0, 0, 480, 360, surface );
// change to standard art
local snap = surface.add_artwork("snap", 0, 0, 480, 360 );
~~~

In the background in the log I was seeing things like `Error opening input file C:\Games\Attract/Layouts/Reflect\\bacon\mame\snaps\gamename.png` my snaps artwork path is a UNC name. If I map a network drive and update the artwork path it works fine.

**Comment by mickelson** [comment]
I think this is fixed now with this release: https://github.com/mickelson/attract/releases/tag/v1.5.3
Your testing would be appreciated.

**Comment by CapnBry** [comment]
Works perfectly. Tested with both UNC and drive letters.
