### ISSUE TITLE
FLV Video Files Not Working 1.5.2 - 64-bit Windows Binary

### ISSUE THREAD

**Issue by two40** [mickelson/attract#129]
Hi,

As the title says, FLV video files do not work in the 64 bit Win version. It displays the first frame of the FLV.

MP4 and MOV are fine.

Thanks,
George

**Comment by ytsejam78** [comment]
Same with MKV on my setup (Windows XP).
It was working in version 1.5.1 so I will stick to this version for now.

**Comment by mickelson** [comment]
Should be fixed now for the next version. Thanks for the report
