### ISSUE TITLE
OS X - issues transitioning to emulator

### ISSUE THREAD

**Issue by mickelson** [mickelson/attract#132]
http://forum.attractmode.org/index.php?topic=207.0

**Comment by liquid8d** [comment]
I can confirm - with Fill Screen and Fullscreen mode, when you launch a game you get a brief view of dock/desktop. For me it doesn't seem like Mission Control just the dock and app bar are visible.

Full Screen definitely does not go back to Attract-Mode.

**Comment by JustMofy** [comment]
Issue is repeatable on 10.10.1 
Issue persists when emulator starts when Mission control is deactivated; however AM behaves correctly on closing the emulator.

**Comment by JustMofy** [comment]
Focus loss is directly related to hot corners. The mouse is "hidden" in the bottom right corner at mame launch, this triggers the corner action (normaly screen saver or mission control).

Moving the mouse ten or twenty pixles left would solve the problem with focus loss.

The menu problem persists.  Have not tested the fix from 13 days ago.
