### ISSUE TITLE
layout*.nut causing other layouts not to load

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#134]
I created a layout with many different layouts - layout-1, layout-2, layout-3, etc.. 
https://github.com/liquid8d/attract-extra/tree/master/layouts/sample_animate

It seems after using that layout, when I try to switch to others they sometimes doesn't load. It appears as if it is looking for the alternate layout .nut in the new layout.

This might only occur when the layout you are switching to has some errors, I haven't quite tracked down the exact reason. However, once I open up attract.am and removed the saved alternate layout names, I am able to switch to the new one.

**Comment by liquid8d** [comment]
Here's an example where I switched from my animate example layout (a sub layout of layout-14-bug-test.nut) to another and it's looking for my sub-layout in the other layout. 

![layout-switch-bug](https://cloud.githubusercontent.com/assets/3782076/8130893/6d00058e-10e4-11e5-8a2f-5bda08e38d3f.png)

This is what my attract.am looks like:
0;0,2,10
2561,4,4,;layout-14-bug-test;1;
370,0,20,;;2;
0,0,;;0;

**Comment by mickelson** [comment]
hi liquid8d, are you still encountering this issue?

**Comment by liquid8d** [comment]
I just came across this again. I'm still not sure for exact steps to reproduce but if a layout you are switching from/to has multiple layout files and you try to switch to a different layout it tries to load the last layout file you are on. Removing that in AM fixes the issue temporarily until it happens again.

Perhaps it relates to my multi-layout file names having dashes or numbers? I'll try to figure out steps to reproduce or provide a sample.

**Comment by liquid8d** [comment]
FYI, this still occurs on occasion - same issue. I still can't get the exact steps but if you are running a layout that has multiple layouts (maybe just due to dashes/numbers in the name?), and switch to another layout the next time you load attract mode it's looking for the alternate layout (which wouldn't exist of course on the new layout) and fails to load the new layout.

I just remove the line from attract.am and it works again.

**Comment by mickelson** [comment]
I think this commit may have fixed this issue: https://github.com/mickelson/attract/commit/f2f0fca30c7ff1421a926577ff274112c41d36fb
