### ISSUE TITLE
Feature Request: start/restart video or set time

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#140]
I didn't see a way to restart a video or play from a specific time. Can we maybe add add .restart() or perhaps just make video_time a set property as well? We could just set video_time to 0 if we want it to restart from the beginning.

**Comment by liquid8d** [comment]
a stop() would be nice as well :) Basically control over the video that is playing.

**Comment by mickelson** [comment]
I thought you could just set video_playing=false to stop the video at any time, and then set it to true to restart.

Let me know if that doesn't work

**Comment by liquid8d** [comment]
DOH! You are correct, I didn't realize video_playing was a set also, and it does stop and restart it. It would be nice if video_time was a set also, but otherwise that works for me :)
