### ISSUE TITLE
Discussion: Python integration.

### ISSUE THREAD

**Issue by Luke-Nukem** [mickelson/attract#141]
Squirrel lang is... Okay-ish. But I've been bumping in to a lot of very silly problems lately, the number one problem is how it does its maths.
For example:

```
local x = 1080*(1920/1080);
print("1080*(1920/1080) = "+x+"\n");
x = 1080 * 1920 / 1080;
print("1080 * 1920 / 1080 = "+x+"\n");
x = 1080*(1920*1.0/1080);
print("1080*(1920*1.0/1080 = "+x+"\n");
x = 1920*1.0/1080;
print("1920*1.0/1080 = "+x+"\n");
x = 1920/1080;
print("1920/1080 = "+x+"\n");
x = 1080*x;
print("x*1080 = "+x+"\n");
```

This isn't such a big deal when you explicitly write numbers as "1920.0" or "666.0", but it is a _huge_ problem if the numbers are coming from functions or fields where they are going to be plain integers.  If you know where this is likely to be a problem, you can counter it by "\* 1.0" on one of the variables.

The only real negative I can see going against Python (v3.x only!!!) in this case is that it would require a great deal of work to implement.
I'm also unsure of the memory requirements for it. Performance wise, from what I could see, it should be faster than Squirrel. I may write some tests if anyone is interested, or if a decision hinges on it.

Python could really open up AM further too.

Thoughts?

**Comment by Luke-Nukem** [comment]
As an experiment for myself to learn more about the Attract Mode engine itself, and for me to learn more about a Python derivative called Cython, I will attempt to migrate AM to Cython.

After shopping around and seeing what alternatives there are. I've settled on Cython being the best way to integrate Python into AM. This seems to be a very powerful way of doing it, and will open up some very interesting possibilities such as compiling a layout into C and then into an object file that can be used to greatly speed up a complex layout.
Where the real overhead is with Python, is in the function calls. Given that SQ is so far looking to be *slower* than Python, this side-effect of using Cython could well be an excellent thing.

 More info is available here:
http://cython.org/
And an example of Cython code:
https://honnibal.wordpress.com/2014/10/21/writing-c-in-cython/

Note, This makes it very easy to just use Python. And also, to compile plugins/modules into very fast C/C++ code.

After browsing the AM code base, I'm not entirely sure where to start, fe_VM looks to be where all the major SQ functionality is. And am I correct in understanding that SQVM dumps everything into a global table for operations?

My first guess on integrating Python, is that I would just need to remove the SQ VM machine, and trim back a few functions. Then start opening all the necessary functions up to Python/Cython...

**Comment by mickelson** [comment]
Hi Luke, sorry a bit slow responding...

To answer your first post re: squirrel and the maths, there are express conversion methods that are useful for exactly this, so "x.tofloat()" gives you a variable as a float, and I think even "fn().tofloat()" gives you the return value of a function as a float.  Of course literals you can just add the ".0" to get  a float.  I don't have much experience with python but I would think any dynamically typed language would have a similar mechanism.

I don't know much about python or anything about cython, other than that python is a general purpose scripting language whereas squirrel is targetted at being embedded in other applications.  If you want to replace squirrel with a different language (lua, python, whatever) in Attract Mode, then yes you would essentially have to reimplement the fe_vm... that is where all the script-specific stuff is.

If you are looking to improve Attract-Mode's performance you might want to try running it through a profiler like valgrid for a while before you invest too much time rewriting the scripting... I'd be surprised if the time spent in squirrel causes that much of a bottleneck compared to other things like the graphics rendering and video decoding...

**Comment by h0tw1r3** [comment]
Python is definitely not well suited for the task. As far as scripting languages go, it's just slow.

Never used Squirrel before this, but I think it was a good design choice. Much more flexible than configuration files (XML), easy to integrate, and very fast.

> If you are looking to improve Attract-Mode's performance you might want to try running it through a profiler like valgrid for a while before you invest too much time rewriting the scripting... I'd be surprised if the time spent in squirrel causes that much of a bottleneck compared to other things like the graphics rendering and video decoding...

Couldn't agree more. The only bottlenecks I have encountered are related to mostly single threaded nature of the program. Threading a few more things (@mickelson recently did some work) could have a pretty big impact.

**Comment by Luke-Nukem** [comment]
Can't say I've really had any issues with performance either. One of the main reasons I decided to explore the possibility is to leverage external python libs.
Looking further, it would make it a very simple matter to build extra libs for AM by using Python. There is also the possibility of using Cython to speed up any complex modules.

I may delve further into it, purely for a learning experience.

As for the floating point problem I had. It's just damned frustrating having to either add in a 1.0 or tofloat() call.  Which is really what spurred me into looking at alternatives in the first place.

Squirrel is kind of nice. The similarity to CPP in structure, and its class implementation is rather nice.
