### ISSUE TITLE
Feature Request: Delete ROM function 

### ISSUE THREAD

**Issue by jimbowley** [mickelson/attract#142]
Like many people I've started with a large number of ROMS with many games that I don't know or that I can tell just from the snapshot that I don't want.  It would be a great help in paring my list down if there was a ROM delete function. 

The function could move it to a nominated folder (for later disposal or whatever) if people think that's a better way to do it..

**Comment by mickelson** [comment]
I've been thinking of adding an 'edit mode' which would allow you to press a button and an overlay would pop up allowing you to edit the the currently selected rom (change the name, control description etc.)... Deleting the rom itself could be one of the options there.

**Comment by ArcadeBliss** [comment]
Hi mickelson, let me know if I can help here. I could write a plugin to handle this if the proper fe. functions and hooks were in place.

**Comment by mickelson** [comment]
Games can be deleted from a romlist using the "Edit Game" function.  The actual rom on disk is not touched tho
