### ISSUE TITLE
video snap's sound keep running on Taito Type

### ISSUE THREAD

**Issue by kent79** [mickelson/attract#150]
I try to run Taito Type emulator-  typex_loader (typex_loader game.exe) in attract mode. When selected the game and then video snap display. Next, click the game and running. But video snap's sound keep running. Please help to check. Thanks. 

I am using as below cfg and batch file is "typex_loader game.exe"

windows_games.cfg
executable           cmd
args                 /c "[romfilename]"
rompath              $HOME/windows_games/
romext               .lnk;.bat

**Comment by mickelson** [comment]
I've not used the taito type emulator, but it sounds like it might be like steam in that when attract-mode runs it it returns right away and is not "blocking".   Try setting the "Minimum Run Time" in the emulator configuration to some number of seconds that is a little more than however long it takes to load... so for example if it takes 5 seconds to load, set "Minimum Run Time" to 7 seconds.... that might help.

Also you could try asking on the forum (forum.attractmode.org) in case someone there has run into this issue already....
