### ISSUE TITLE
Shader file location prefixed to fe.script_dir

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#151]
It seems you can't specify a fixed or relative path location for shader files, it always searches for the file relative to fe.script_dir.

My goal is to create a shared resource location (for images and shaders) outside of the layout (script_dir) location, but the shaders seem to be forced to script_dir.

**Comment by mickelson** [comment]
hi liquid8d, are you using the most recent development code or is this in the last release?  I know I was messing around with the loading of shaders recently on the development repository (to get them to load from inside zip files) so that might have messed it up...

**Comment by liquid8d** [comment]
This is still with 1.5.2 - I haven't gotten to test out the .zip support - perhaps since you done work with the zip loading, that might not be an issue anymore? I had issues compiling previously but I'll try to get a recent build together and give it another shot.

I'm looking to have a shared folder for my module assets which would include shaders so if a module could be zipped and the included shaders can be used from there, that will work for me :)

**Comment by liquid8d** [comment]
Just tried a new build and looks like it still does prefix fe.script_dir. Does the zip support work for any zip file or is it limited to an entire layout/module? In other words, could you include a zip and reference it like a relative directory - shaders/something.frag from a shaders.zip file?

**Comment by mickelson** [comment]
Ok I've fixed this now, thanks for the report.

As for the zip support, if a layout or plugin is in a zip file, then any relative paths that are encountered in that layout/plugin are treated as being in the zip file as well.  There are also some basic functions available to scripts to get the contents of a zip file and to load a file from a zip file into a squirrel blob...
