### ISSUE TITLE
compiling with debian wheezy

### ISSUE THREAD

**Issue by damiendd** [mickelson/attract#154]
Hi,

I tryed ti install attract on a debian wheezy but without success. I can install all lib using the testing mode.
But i got an error when i try to make the installable about unknow entity reference, anyone is experiencing the same?

(i can post output later).
And debian package .deb, seems to be for ubuntu versions?

Thank you,
Damien.

ps: i cannot register on the attractmode forum, what is that answer to programming language **?

**Comment by mickelson** [comment]
Hi, are you following the directions for compling on debian wheezy found here: https://github.com/mickelson/attract/wiki/Compiling-on-Debian-Wheezy-%28oldstable%29

The version of SFML that is in debian wheezy is too old for Attract-Mode, so you need to take some extra measures to get Attract-Mode running on wheezy.

The output posting will certainly help us see what is going on specifically...

As for the .debs, I don't really know but I suspect you are right and they are ubuntu only.  akafox on the forum will be able to help with them.  

The answer to get on the forum is right there on the about page: http://attractmode.org/about.html  email me with your email and preferred user name and I can set you up if you are still having problems.
