### ISSUE TITLE
Feature Request: Modules in a subdirectory

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#157]
When creating plugins, you can create a folder with a file called plugin.nut. This is helpful if your plugins will have additional files included to keep things organized.

With modules though, it doesn't seem you can do the same thing. It doesn't appear to look for a main "module.nut" or "plugin.nut" script, so your load module call would have to be fe.load_module("folder/file");

This is the issue I'm running in with the animate module. I want the load to be fe.load_module("animate"); but in order to do that, my animate.nut has to be in the modules/ folder.

This is more just an OCD / organization thing, but I don't want to confuse users with fe.load_module("animate/animate") and since plugins already operate that way I hope it can added  easily.

I'll note I haven't tried .zip format, if that might be another option.

Does that make sense? :)

**Comment by mickelson** [comment]
Yes I think that makes sense!  Basically if script asks for load_module( "animate" ) it should check for animate.nut but then fall back to "animate/module.nut" (or something).. that should be easy enough to implement, I'll take a look right now.

zip isn't implemented for modules at the current time, there are a couple of tricky issues that make it not that straight forward...

**Comment by liquid8d** [comment]
thanks, that's excellent :)
