### ISSUE TITLE
Feature Request: center rotation and scale

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#158]
Before I forget this one :) Not sure how difficult this will be:

Object rotation currently has the origin at 0,0 of the object - i think by default most might expect it to rotate from center. Even if that isn't the default, I'd like to see a way of doing a centered rotation.

I'd also like to see a scale property. I'm not sure if this should actually modify width and height or just when the object is drawn it takes into account the scale.

I sort of hacked these into the animate module, but it's difficult to work with since scripts might change the location, size, rotation, pinch, skew, etc.. which can throw off calculations unless I track and update changes to those properties.

**Comment by ArcadeBliss** [comment]
sfml already provides the ability to scale and image and to change its "origin" to another part of the image. It is documented here: **sf::Transformable** http://www.sfml-dev.org/tutorials/2.4/graphics-transform.php 

if these properties can be exposed using squirrel withing fe.image, and fe.text we would have everything needed to make easier animations. 

Raygun, would it be very involved to expose this property in squirrel? On the other hand, I am thinking of editing the AM code myself. What src files would I need to look into to ensure it gets exposed to squirrel and fe.image?

I also wrote this request in the forum here: http://forum.attractmode.org/index.php?topic=1006.0#

Thanks.

**Comment by mickelson** [comment]
This was implemented a while ago and I forgot to close the issue: dbcc5c8f6dd61e2adcac823fc9fd86d9968277d2
