### ISSUE TITLE
Magic Token empty values bug

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#159]
If the magic token is empty, an error is thrown that the image/video is not available, but then grabs another random image from the same path. If the new index has a value but doesn't match, it does as expected and removes the image.

Here's an example:
```
local text = fe.add_text("[Title]", 0, 0, 400, 30);
local category = fe.add_text("[Category]", 0, 40, 400, 30);
text.align = category.align = Align.Left;
local image = fe.add_image("[Category].png", 0, 80, 175, 75);

Error opening input file: C:\attract-1.60\layouts/bug//layout.nut
ERROR loading video: C:\attract-1.60\layouts/bug//layout.nut
```
Make sure some entries have categories with matching images and some don't or use a different magic token where the value might be empty.

Expected result would be maybe to load [MagicToken].png, .jpg, etc.. - and if that doesn't exist, set it to no image.

Here's working, then non-working after scrolling back and forth through the entries:
![magic-working](https://cloud.githubusercontent.com/assets/3782076/10461295/b56578e0-71a6-11e5-8972-02c8df46a1cd.png)
![magic-not-working-1](https://cloud.githubusercontent.com/assets/3782076/10461296/b913d8c4-71a6-11e5-9290-30b9e06ea133.png)
![magic-not-working-2](https://cloud.githubusercontent.com/assets/3782076/10461298/ba80378e-71a6-11e5-9520-fac9ae22a8be.png)

**Comment by liquid8d** [comment]
I realized you can handle it yourself with functions to force something if the magic token is empty, although file_name="" still causes the same result - so perhaps something as simple as setting file_name to "" can wipe the texture?:

```
local image = fe.add_image("[!check_cat].png", 0, 80, 175, 75);

function check_cat( offset )
{
    print("check cat: " + offset + "\n");
    local cat = fe.game_info(Info.Category, offset );
    return ( cat != "" ) ? cat + ".png" : "category.png";
}
```

**Comment by mickelson** [comment]
Thanks for the report, fixed.
