### ISSUE TITLE
intro.mp4 does not display, sound only

### ISSUE THREAD

**Issue by BENETNATH** [mickelson/attract#161]
I've updated today to 1.6 and the intro.mp4 does not play well.
I've got sound but no picture.
running the intro.mp4 is fine outside of attract.
leaving the intro field empty in configuration does not skip the intro

config : win XP, 720*576

**Comment by mickelson** [comment]
hmmm.  Is this with the intro.mp4 video included in base windows installation?

Also is there any chance you are running the old IntroVid plugin (which conflicts with the built-in intro video support added as of 1.6)?

**Comment by tnhabib** [comment]
I'm having the same issue on Linux. I built from source and I'm archlinux

**Comment by mickelson** [comment]
One thing to note is that attract-mode doesn't use any hardware acceleration for video, so it is possible the file is just too much for it to handle depending on your system specs...

AM's video code was never intended to be used for full size HD videos, it's a fairly basic software implementation.

**Comment by calle81** [comment]
It's one of the missing pieces for the perfect Attract Mode experience on the Pi. We currently have to use 240P videos in order for AM to display the correctly. 480P wold be a massive improvement. Thanks for your amazing work! You should check out the Retropie group on Facebook. Everyone is loving AM and new themes are created on an almost daily basis. Cheers!

**Comment by mickelson** [comment]
Closing another issue that hasn't been kept up to date.  MMAL decoding on the PI implemented here: dbcc5c8f6dd61e2adcac823fc9fd86d9968277d2

useful hardware accelerated decoding for other systems is  still a work in progress
