### ISSUE TITLE
Feature Request: Blit layout using keep_aspect_ratio 

### ISSUE THREAD

**Issue by rsn8887** [mickelson/attract#163]
In the current implementation, images and surfaces can be drawn using keep_aspect_ratio, but the layout itself is always stretched to fit the screen.

It would be great to be able to select "keep layout aspect ratio true/false" in the general options in the menu to force a layout that was designed for a certain aspect ratio such as 4:3 to be shown in it's designed aspect ratio, centered with black borders on a widescreen TV, instead of always stretching all the artwork in it to fill the screen.

**Comment by liquid8d** [comment]
I second this.. BUT Layouts would have to take this into consideration so I'm not sure what the best implementation would be.

I was working on a way for layouts to handle this on their own - basically this would be something like Aspect = "stretch,crop,fill" and the whole layout would either stretch (as it does by default now),  crop the layout ( fitting the layout surfaces largest dimension), or fill the screen ( fitting/centering to the layout surfaces smallest dimension ).

It's a bit tricky though on what you'd report to the layout creator for dimensions or how they might modify their layout dynamically based on those dimensions.

**Comment by mickelson** [comment]
what I've done for now is to make a "preserve_aspect_ratio" flag that can be set by scripts on the fe.layout object.  It will behave much the same as the preserve aspect ratio flag for images.

Layouts can of course still draw things outside the bounds of the layout (by specifying negative coordinates for example) so there should be crafty stuff that can be done to get a cropped effect still with this setting turned on.
