### ISSUE TITLE
Since 1.6.2: Emulators started in windowed mode are invisible when launching Attract Mode via Windows GUI

### ISSUE THREAD

**Issue by rsn8887** [mickelson/attract#164]
If I configure an emulator to start up in windowed mode and launch it from Attract Mode, its window does not appear, the sound plays though, but the window is completely hidden. This is on Windows 10 using 1.6.2. (worked fine in 1.6.1). It works fine if the emulator is configured to start in Fullscreen mode.

This problem ONLY happens when launching Attract Mode via the Windows GUI by double clicking its icon. It goes away completely when launching Attract Mode from the command-line.

I therefore believe this problem is a consequence of the following new feature introduced in 1.6.2: 
"Close windows console automatically when starting from GUI"

**Comment by rsn8887** [comment]
I just confirmed that simply creating a shortcut icon to attract mode and changing target to 
cmd.exe /C Attract.exe
fixes this problem. It causes the command window to stay open and emulator windows to appear in the foreground above AM always.

This is also an issue with any emulator starting in "windowed - maximized" mode, or in the same fullscreen resolution as AM.

**Comment by mickelson** [comment]
@h0tw1r3 ... any chance you could take a look at this issue?  It appears to be related to the code you added to automatically close the windows console when starting from the GUI

**Comment by h0tw1r3** [comment]
@mickelson I can look into it in the next couple days.
