### ISSUE TITLE
Feature Request: Treat .xmv files as video files

### ISSUE THREAD

**Issue by rsn8887** [mickelson/attract#165]
Since Attract Mode uses ffmpeg to play video files, .xmv is actually a supported video format. However, it seems as if AM does not recognize .xmv as a video format and does not play the files, unless they are renamed to .avi. Renaming the files to .avi is a fix, but could lead to confusion since it obscures the true file format. 

I propose to add files with .xmv extension to the recognized list of video files. 

This is important because there is an extensive and well-sorted library of .xmv video snapshots easily available for free online as part of the Resurrection Xtras packages for Xbox classic. With the proposed feature, users who own those packages could easily use them in Attract Mode.

**Comment by rsn8887** [comment]
AM already does everything right and is actually very smart! It passes all non-image files that have an extension not listed in FE_ART_EXTENSIONS to ffmpeg to find out if they are playable video files. That is done based on filename extension (to ensure it is fast), using the av_guess_format function from ffmpeg. 

So ffmpeg is the problem. Although it supports the xmv format, the extension ".xmv" is not actually associated with the codec implementation inside FFmpeg/libavformat/xmv.c, so when AM hands over (smartly as it does) the filename to av_guess_format, it returns a NULL because it doesn't know the file is an .xmv based on extension.

One solution would be to do a quick hack and bypass av_guess_format if the extension is .xmv. But I don't really like that kind of hack much. It is possible though.

For now I will stick to renaming my files from .xmv to .avi, and try to issue a pull request to ffmpeg.

**Comment by mickelson** [comment]
I've got a workaround for this that I think will work.  Attract-mode can be changed to send the file extension to av_guess_format() as the "short name" for the format.  It looks like this will solve this problem for xmv (and maybe other formats?).

https://ffmpeg.org/doxygen/2.8/group__lavf__encoding.html#ga8795680bd7489e96eeb5aef5e615cacc

**Comment by rsn8887** [comment]
Also, good news my pull request for ffmpeg was accepted. So at least in future releases of ffmpeg, the .xmv extension will be recognized.

https://github.com/FFmpeg/FFmpeg/pull/166

**Comment by mickelson** [comment]
ok, between the workaround and your patch to FFmpeg I think we've got this covered. thanks, I'll close this issue now.

**Comment by rsn8887** [comment]
I just tried the latest buildbot version 1.6.2-6 which should have this fix applied. It is still not the xmv files, I am not sure what is going on. In case you want to test it, I am uploading a zipped .xmv and corresponding empty rom file. Just extract to ./ create an emulator, set rompath to ./ and video path to ./ and generate romlist. The video will not play. I am not sure why. If renamed from .xmv to .avi, the video will play, suggesting that ffmpeg can play it without problem.

[xmlTest.zip](https://github.com/mickelson/attract/files/70941/xmlTest.zip)

**Comment by rsn8887** [comment]
Tried in version 2.0.0 release but this issue remains. It is not a big deal since the .xmv can be renamed to .avi to make it work.
