### ISSUE TITLE
1.6.2 Bug: Changing Window Mode causes blank screen

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#166]
When changing window mode and exiting the menu back to the layout, the layout has not been redrawn - and the resolution also appears to have changed since you can still access the Exit menu but it isn't fit to the screen resolution.

Appears this is confirmed on Windows and OSX.. changing the layout for the current display does force it to reload.

**Comment by mickelson** [comment]
thanks for the report, should be fixed now
