### ISSUE TITLE
Odroid xu3/xu4 boards support request (arm boards)

### ISSUE THREAD

**Issue by tipoto** [mickelson/attract#169]
Attract-Mode can be installed on the Raspberry Pi, but it would be nice to be able to install it also on the more powerful Odroid Xu3/Xu4 cards, the 2 cards are 100% software compatible with each other, but not with the pi of course. The compilation process is very similar to the pi since they are arm cards too, but It seems the only problem is to get compiled an SFML library that works with Attract-Mode.

Thanks in advance!

**Comment by mickelson** [comment]
From: http://www.hardkernel.com/main/products/prdt_info.php?g_code=g138745696275&tab_idx=3

> Does it support the OpenGL ES 1.1/2.0 on the Ubuntu/Linux distros?
> Yes, ARM Mali-400 3D GPU works in Linux X11.

This sounds promising and should put you a lot further ahead of where we were with the RPi.  The problem on the RPi was that we couldn't get a hardware accelerated OpenGL ES 1.1 context in X11 and a custom version of SFML was required.

What I suggest you try doing is uninstalling any sfml packages that you have tried installing on your device, and then downloading the sfml source and compiling it yourself.  You need to compile SFML with a specific flag for it to use OpenGL ES (-DSFML_OPENGL_ES=1), and my guess is the sfml packages you are trying to use aren't built with that flag.

So to modify the rpi instructions (https://github.com/mickelson/attract/wiki/Compiling-on-the-Raspberry-Pi-%28Raspbian-Wheezy%29) for your situation, try the following to get SFML installed on your odroid:

* Uninstall all sfml libraries you may have previously installed
* Create a build environment
```
cd ~
mkdir develop
```
* Install SFML and Attract-Mode dependencies
```
sudo apt-get install cmake libx11-dev libx11-xcb-dev libflac-dev libogg-dev libvorbis-dev libopenal-dev libjpeg8-dev libfreetype6-dev libxcb-randr0-dev libxcb-image0-dev libxcb-util0-dev libxcb-ewmh-dev libxcb-keysyms1-dev libxcb-icccm4-dev libudev-dev libavutil-dev libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavresample-dev libfontconfig1-dev
```
* Download and build the latest sfml from the SFML project's git
```
cd ~/develop
git clone https://github.com/SFML/SFML sfml
mkdir sfml/build;cd sfml/build
cmake -DSFML_OPENGL_ES=1 ..
sudo make install
sudo ldconfig
```

You may need to play around with the cmake settings a bit.  I'd try the above cmake command and see what sort of error messages you get.  Installing a cmake gui might help you configure everything that cmake may require on your system...

Let me know how that goes for you... post error messages if you are stumped, I can at least try to make an educated guess. You could also try posting on the sfml project's forum to see if anyone there has had success getting sfml going on odroid...

**Comment by tipoto** [comment]
Thank you!
Here is how far I got to compile AM... I could fix some errors, but not all of them unfortunately.

I managed to compile SFML libraries with your options, but I had to modify 3 files to fix some errors. Here are the 3 files:
/home/odroid/develop/sfml/src/SFML/Window/EglContext.cpp
/home/odroid/develop/sfml/src/SFML/Window/EglContext.hpp
/home/odroid/develop/sfml/src/SFML/Window/GlContext.cpp

And I had to add this:
#include <X11/Xutil.h>

With those changes, the libraries compiled successfully, but then, I got undefined reference errors while making AM. Here is the detail:

fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
g++ -o attract obj/fe_base.o obj/fe_util.o obj/fe_util_sq.o obj/fe_cmdline.o obj/fe_info.o obj/fe_input.o obj/fe_romlist.o obj/fe_settings.o obj/scraper_xml.o obj/scraper_general.o obj/scraper_net.o obj/fe_config.o obj/fe_presentable.o obj/fe_present.o obj/sprite.o obj/fe_image.o obj/fe_sound.o obj/fe_shader.o obj/fe_overlay.o obj/fe_window.o obj/tp.o obj/fe_text.o obj/fe_listbox.o obj/fe_vm.o obj/zip.o obj/main.o obj/fe_net.o obj/swf.o obj/media.o obj/libsquirrel.a obj/libsqstdlib.a obj/libgameswf.a obj/libaudio.a  -Wl,--export-dynamic -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/miniz -Iextlibs/audio/include -I/usr/include/freetype2 -I/usr/include/AL  -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/gameswf  -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_SWRESAMPLE -lsfml-graphics -lsfml-window -lsfml-network -lsfml-system -ljpeg -lz -ldl -lGL -lX11 -lXinerama -lfontconfig -lfreetype -lavformat -lavcodec -lavutil -lswscale -lopenal -lswresample  -lexpat
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_randr_get_screen_info_reply'
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_randr_query_version_reply'
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_randr_set_screen_config'
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_randr_query_version'
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_randr_id'
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_randr_set_screen_config_reply'
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_create_pixmap_from_bitmap_data'
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_randr_get_screen_info_sizes'
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_randr_get_screen_info'
//usr/local/lib/libsfml-window.so: undefined reference to `xcb_randr_get_screen_info_sizes_length'
collect2: error: ld returned 1 exit status
Makefile:385: recipe for target 'attract' failed
make: *** [attract] Error 1

I guess it's looking at the wrong location for some files/libraries, but it's not clear which ones and where to put them. Do I have to copy manually the content of /home/odroid/develop/sfml/include in a specific folder?

**Comment by tipoto** [comment]
I should have mentioned that one library wasn't available anymore "**libjpeg8-dev**" and I had to replace it with "**libjpeg62-turbo-dev**".

Also, here are the error messages I received before modifying **EglContext.cpp**, **EglContext.hpp** and **GlContext.cpp**: 
```
In file included from /home/odroid/develop/sfml/src/SFML/Window/GlContext.cpp:66:0:
/home/odroid/develop/sfml/src/SFML/Window/EglContext.hpp:163:12: error: ‘XVisualInfo’ does not name a type static XVisualInfo selectBestVisual(::Display* display, unsigned int bitsPerPixel, const ContextSettings& settings);
            ^
src/SFML/Window/CMakeFiles/sfml-window.dir/build.make:77: recipe for target 'src/SFML/Window/CMakeFiles/sfml-window.dir/GlContext.cpp.o' failed
make[2]: *** [src/SFML/Window/CMakeFiles/sfml-window.dir/GlContext.cpp.o] Error 1
CMakeFiles/Makefile2:152: recipe for target 'src/SFML/Window/CMakeFiles/sfml-window.dir/all' failed
make[1]: *** [src/SFML/Window/CMakeFiles/sfml-window.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

I also received the same type of error with **EglContext.cpp**, it's why I also modified it.

**Comment by zacklmoore** [comment]
Hello,

I also have been trying to get Attract-Mode to build for my Odroid XU3 and have been running into the same issue. From what I can find it seems to be an issue with SFML rather than with Attract-Mode itself. Check out this thread on the SFML forums:

http://en.sfml-dev.org/forums/index.php?topic=19262.msg139160#msg139160

When I have time I'm going to try some of the suggestions in that thread and re-build SFML.

**Comment by mickelson** [comment]
I agree it's an issue with SFML zacklmoore, and those approaches you linked look promising

tipto: adding the Xutil include is something I had to do as well to get it working on the pi, so I think that is right.  Here is a link showing all the changes I had to make to get SFML working on the PI, this might give you some troubleshooting ideas:

https://github.com/mickelson/SFML/commit/143fe7c03e2d99855836b0ce79dd86b53016c633

I think you should take a look at the change to src/SFML/Window/CMakeLists.txt
in the above.  You might have to do somethign like that on your system too to get around the linker error.  Hope this helps.

**Comment by zacklmoore** [comment]
A little update: I managed to get everything to compile. I compiled SFML just using the instructions you provided above and got everything to finish compiling by modifying the following section of the makefile:

```makefile
ifeq ($(NO_NET),1)
  LIBS += -lsfml-graphics \
	-lsfml-window \
	-lsfml-system \
	-lxcb-randr \
	-lxcb-util \
	-lxcb-image
  FE_FLAGS += -DNO_NET
 else
  LIBS += -lsfml-graphics \
	-lsfml-window \
	-lsfml-network \
	-lsfml-system \
	-lxcb-randr \
	-lxcb-util \
	-lxcb-image
 endif
```

Now it launches but the window never fully appears and I get an endless stream of the following:

"Failed to create texture, invalid size: (0x0)"

I think it may be related to fonts, but I'm not 100% sure. I have tried to run other simple SFML apps and those have run correctly, though none of them have been very complex.

**Comment by tipoto** [comment]
I didn't have time to test it yesterday, but I will try tonight. I'm glad to see we're getting close, but it seems there is not a lot of info about this new error message, except the font thing.
I'll do some tests on my side and let you know if I managed to go further.

**Comment by zacklmoore** [comment]
Definitely seems to be some sort of font issue. I tried running it with different fonts using the --font argument and when I run with the Times font the window seems to open but I get different errors:

Failed to set bitmap font size to 27
Available sizes are: 14 
...
Failed to set bitmap font size to 18
Available sizes are: 14 
...

I'm trying it with all of the fonts I can find on my system but so far I haven't gotten it to work yet. Certain fonts give me the original invalid texture error, and some give me errors similar to those above.

**Comment by tipoto** [comment]
Unfortunately I didn't manage to go further, I also have the "Failed to create texture, invalid size (0x0)" message. I don't even manage to have another message by using the -f flag :/
I didn't edit the makefile like you did though, I didn't find the section you were suggesting to modify, but it compiled fine anyway without these changes.
I only edited the file  src/SFML/Window/CMakeLists.txt with the same changes done for the RPi, except I removed the "conditional". For the other files, the changes were specific to the Pi so I didn't use them, but I guess we maybe need to edit src/SFML/Window/EglContext.cpp with something similar to what was done for the Pi.

**Comment by zacklmoore** [comment]
The changes I made to the makefile made it run without modifying SFML, but once I made the changes to the Window CMakeLists I was also able to compile without modifying the makefile. I haven't made any progress on the new issue yet, however.

**Comment by tipoto** [comment]
I created a thread on the Odroid forums about this issue. I've got a reply today with a patch that we can apply. I'm not at home right now, so I don't know if it works yet, but if you want to test it, here is the link to the topic :)
http://forum.odroid.com/viewtopic.php?f=91&t=18283&p=120706#p120706

**Comment by tipoto** [comment]
It works!
Thank you to **AreaScout** from the Odroid forums for his patch, also thank you to you guys for your help. We should maybe prepare a clean version of this install for every xu3/xu4 owners. Let me know if you need my help to prepare it.

The AreaScout's patch has to be used for step where you build Attract-Mode, so basically, here are all the steps to build AM (after compiling SFML):
```
cd ~/develop
git clone --depth 1 https://github.com/mickelson/attract attract
cd attract
wget -O patch.txt http://pastebin.com/raw/fybsi5FT
patch -p0 < patch.txt
make
sudo make install
```
If you are logged as root, you don't need "sudo" of course
