### ISSUE TITLE
Crash when scraping long filename with unusual characters

### ISSUE THREAD

**Issue by rsn8887** [mickelson/attract#170]
At first I thought it was related to a long filename, but it is something else. Every once in a while when I am scraping from gamesdb, AM crashes. I am not sure how to reproduce. I will update this issue as I find out.

**Comment by rsn8887** [comment]
I found the culprit. If I try to scrape a file with the name
Action Replay 2 Version 2.30 (USA) (En,Fr,Es,Pt) (Disc 2) (Bonus PSone Codes!) (Unl).cue
AM crashes reproducibly.

**Comment by rsn8887** [comment]
I think found out how it works:
If the rom filename has more than 60 or so characters, it crashes when scraping thegamesdb. I tried to find the exact filename length to cause a crash, but it seems to vary from trial to trial sometimes it crashes with a filename length >60, sometimes even 70 characters works. I suspect it has something to do with some kind of unexpected response (or lack thereof) from thegamesdb?

**Comment by mickelson** [comment]
I've tried to improve the error logging from thegamesdb.net, there is a chance this might fix the issue but at the very least it should help track down the error source.  So please try to reproduce this with the newest version of the nightly build when you have a chance

**Comment by rsn8887** [comment]
Here's the error message using buildbot revision 8
*** Initializing display: 'retroarch-mednafen-psx'
 - Loaded master romlist 'retroarch-mednafen-psx' in 15 ms (1619 entries kept, 103 discarded)
 - Constructed 2 filters in 30 ms (3238 comparisons)
 - Loaded layout: P:\Attract Mode\layouts/xtras/ (layout.nut)
*** Generating Collection/Rom List: retroarch-mednafen-psx
 - Found 1722 files.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 49901184) > this->size() (which is 84)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by rsn8887** [comment]
And here is the same error I get when scraping a single file called 
12345678901234567890123456789012345678901234567980123465789012345679801234567890.cue

Starting Attract-Mode 1.6.2 (Windows)
Config: P:\Attract Mode\attract.cfg

*** Initializing display: 'retroarch-mednafen-psx'
 - Loaded master romlist 'retroarch-mednafen-psx' in 0 ms (1 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (2 comparisons)
 - Loaded layout: P:\Attract Mode\layouts/xtras/ (layout.nut)
*** Generating Collection/Rom List: retroarch-mednafen-psx
 - Found 1 files.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 134217776) > this->size() (which is 80)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by rsn8887** [comment]
I get the same error in 32bit and 64bit versions

**Comment by mickelson** [comment]
Please let me know if this is still happening with version 2.0-rc3.  I believe this might have been fixed with some of the crash fixes in that version.
