### ISSUE TITLE
Snap / Video Snaps only work with full fixed drive location. All others work fine without

### ISSUE THREAD

**Issue by Bloodwyn2** [mickelson/attract#171]
Example:

artwork    flyer           ../flyers *working perfectly
artwork    marquee         ../marquees *working perfectly
artwork    snap            G:/Arcade/Video *cannot use ../Video or will not show snap or video.
artwork    wheel           ../Wheel *working perfectly

Not sure why with Video or snaps I have to use the full path name for it to work. Frustrating since I want to run everything off USB on different machines.

**Comment by mickelson** [comment]
I'm guessing you are using the "robospin" or some other layout that uses the "FadeArt" module?
I think I might have tracked down the issue and will commit a fix, try out the nightly build in a couple of days and let me know if it fixes this issue for you!

**Comment by Bloodwyn2** [comment]
Great! thank you.

Everything else works fantastic.

Tom
