### ISSUE TITLE
Feature Request: Themeable Displays Menu

### ISSUE THREAD

**Issue by elsonrodriguez** [mickelson/attract#172]
It seems a logical use of the Displays function is to make a Display per system. After adding a few systems, the Displays switching menu becomes a welcome feature, however it is way too plain.

It would be great if the Displays menu were exposed to be themeable, so layout authors could customize the look.

Bonus points for a themeable Filters menu.

**Comment by mickelson** [comment]
Funny timing on this feature request, I've been working on just this thing right now!

So I'll attribute the commits to this issue for tracking purposes.
