### ISSUE TITLE
Hardcode attractmode menu fonts.

### ISSUE THREAD

**Issue by elsonrodriguez** [mickelson/attract#173]
When switching layouts, sometimes the font of the attractmode menu also switches. Problem is that some fonts don't have separate upper/lowercase characters. This can cause confusion when configuring things like filepaths.

Is there a way to override layout author font choices for these backend menus?

**Comment by mickelson** [comment]
Ok I think the best solution to this is that I will hardcode the configuration menu to always use the default font, which can be separately configured...
