### ISSUE TITLE
Support zipped artwork

### ISSUE THREAD

**Issue by nguillaumin** [mickelson/attract#175]
Hi,

Unless I'm mistaken zipped artwork is not supported? For example all my MAME snapshots are in a single `snap.zip` file under my MAME `snap/` folder (so `snap/snap.zip`) but I need to unzip them all into individual files for Attract Mode.

Supporting zipped artwork would be nice, especially since it's supported by MAME and also because [popular artwork sources](http://www.progettosnaps.net/snapshots/) provide artwork DAT files in a format that results in them being zipped (A single `machine` XML tag where each snapshot is a `rom` tag, resulting in a single `<machine>.zip` file by popular DATs/ROMs managers).

Cheers,

Nico

**Comment by mickelson** [comment]
ok, changes made.  any testing you can do using the nightly build in a couple of days would be appreciated!!

**Comment by nguillaumin** [comment]
Wow I wasn't expecting it to be implemented so soon, Thanks!

I tested the latest Git version and it works, however:
* I wasn't expecting to have to put the path to the ZIP file in the config, I thought it would find it by itself in the folder (the same way it can find images). Not a big deal I guess...
* It freezes at startup for ~10s presumably to process the ZIP file (My `snap.zip` is 1.3GB big). It's understandable but it seems the screen / OpenGL surface is not properly initialised when it does so so I get an odd image which is partly a screenshot of my desktop. It may be desirable to replace it with a progress message or something?
* Browsing games is also significantly slower, with a 0.5s - 2s delay between each game, presumably to fetch the artwork from the ZIP file. Not sure what can be done there...

So it's good enough for me, but it may benefit from a little polishing!

Cheers,

Nico

**Comment by mickelson** [comment]
Good timing, I've had some time on my hands the last few days to fix things up.

I think requiring the path be right to the zip file is the only sane way to do this, due to the way Attract-Mode searches for all the various artworks resources.  With respect to the time its taking to load and browse, I've gone and added a caching mechanism that should speed this up.  Let me know if it is faster for you in the newer build.

**Comment by nguillaumin** [comment]
Thanks, I've tested the latest version and it's much better. I still freezes the very first time to load all the artwork, but after that browsing games is very smooth and if I restart it loads snappily without freezing.

Cheers!
