### ISSUE TITLE
Video pixel aspect ratio

### ISSUE THREAD

**Issue by h0tw1r3** [mickelson/attract#176]
Attract doesn't appear to be respecting the embedded aspect ratio of videos (expects they are square pixel).

Screenshot shows AM''s view of the same video as vlc is playing.

![untitled](https://cloud.githubusercontent.com/assets/809115/12219644/eca39ab6-b711-11e5-8ffb-da39e365e2af.png)

Videos which exhibit behavior:
http://playground.zaplabs.com/dl/galaxian.mp4
http://playground.zaplabs.com/dl/frogger.mp4

**Comment by mickelson** [comment]
Yup, that was an oversight.  Thanks for pointing that out, it should be fixed now.
