### ISSUE TITLE
Feature - Main Menu

### ISSUE THREAD

**Issue by ryuuji89** [mickelson/attract#185]
Well I think will be nice to have Main Menu where u can select which system to enter (ofc themeable).

**Comment by mickelson** [comment]
Hi there, I believe this can be achieved now using the "Displays Menu" feature in Attract-Mode.  This menu is themeable as well.

As of version 2.0, each display can be configured whether it shows up in the menu, the FE can be set to always start from the displays menu, and you can configure your escape/back button to go back to the displays menu.

THis allows for setups where there is a "Main Menu" (the "displays menu") where you can select each system to enter, assuming you create a display that corresponds to each system.
