### ISSUE TITLE
Attract-mode: rotation

### ISSUE THREAD

**Issue by daimonnomos** [mickelson/attract#191]
possible bug -> preserve_aspect_ratio in combination with rotation.

The following code will give, on my win7 PC, not the expected result.

local snap = fe.add_artwork( "snap", x, y, width, height);
snap.preserve_aspect_ratio=true;
snap.rotation = 180;

Some images (in my case .png, didn't try other formats) will be rotated correct, other images will shift in horizontal- or vertical direction. Assuming the rotation point is top left of the original none rotated image.

**Comment by daimonnomos** [comment]
Following workaround will do what I expect:

// possible bug -> preserve_aspect_ratio in combination with rotate.
// workaround -> do your on resizeing and preserve aspect ratio.
snap.preserve_aspect_ratio=false;
fe.add_transition_callback("artwork_transition");
function artwork_transition( ttype, var, ttime )
{
  if (( ttype == Transition.FromOldSelection )
     || ( ttype == Transition.ToNewList ))
  {
	local wf=snap_width/snap2.subimg_width.tofloat();
	local hf=snap_height/snap2.subimg_height.tofloat();
	if(wf<hf)
	{
		snap2.width=wf*snap2.subimg_width;
		snap2.height=wf*snap2.subimg_height;
	}
	else
	{
		snap2.width=hf*snap2.subimg_width;
		snap2.height=hf*snap2.subimg_height;
	}
	local snap_x_offset=(snap_width-snap2.width)/2
	local snap_y_offset=(snap_height-snap2.height)/2
	snap2.set_pos(fe.layout.width-list_x_offset-snap_x_offset, fe.layout.height-header_height-snap_y_offset);
  }
  return false;
}

**Comment by mickelson** [comment]
Thanks for the report, this should be fixed now
