### ISSUE TITLE
BUG Win10 Tablet mode launch

### ISSUE THREAD

**Issue by ryuuji89** [mickelson/attract#192]
When I try to launch AM from Win10 Tablet mode, AM it is not visible (it is launched but it's somehow hidden, when switching to desktop mode it is visible)

**Comment by mickelson** [comment]
@ryuuji89 please report if this issue still occurs with version 2.1.0, thanks

**Comment by ryuuji89** [comment]
Works as it should using 2.1.0 under w10 tablet mode.
