### ISSUE TITLE
RC2 hangs on win10

### ISSUE THREAD

**Issue by omegaman1** [mickelson/attract#193]
RC2 hangs on windows 10, causing event error "1002". This is a tricky one, because it seems to hang after playing a game for an extended amount of time. 

The program attract.exe version 2.0.0.4 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 1e2c
 Start Time: 01d17886b8b6fa55
 Termination Time: 57
 Application Path: C:\arcade\attract\attract.exe
 Report Id: ed1cc508-e47a-11e5-9bf1-2c27d73397d9
 Faulting package full name: 
 Faulting package-relative application ID:

**Comment by omegaman1** [comment]
Update, I need to troubleshoot this further on my end. I rolled back to 1.6.2 and have the same issue. Basically, exiting the game after playing it for an extended amount of time causes attract to freeze. Leaving the game idle has the same effect.

**Comment by mickelson** [comment]
Hi Omegaman, I don't have access to Windows 10, and have been unable to reproduce on a pilfered Windows 8 laptop.

Could you confirm a couple of things with this if you have a chance:

1. does it still occur if you run attract in compatability mode with Windows 8 (one of the right click options I believe)?

2. does configuring an Exit Hotkey in the emulator configuration for the emulator in question change this behaviour at all?

**Comment by omegaman1** [comment]
The first thing I tried was different compatibility settings to no avail. I tried mapping different emulator exit hotkey controls, and it didn't matter if it was keyboard or joystick. I even went so far as to remap all emulator controls., same result. The only thing I didn't try was setting all attract controls to use keyboard only. 

It's really weird. Attract doesn't lock up if you exit the game after playing for less than a minute or so. But, if you play for more than 3 minutes and then exit, attract locks up hard. When you kill the task is when it crashes.

**Comment by mickelson** [comment]
Can you check if this still happens with rc3?

**Comment by omegaman1** [comment]
Yes, unfortunately. Not. sure what to make of it.     Batty: We're not computers, Sebastian. We're physical.
Daryl Hannah as Pris: I think, Sebastian. Therefore I am.
 

    On Friday, March 18, 2016 9:03 PM, Andrew Mickelson <notifications@github.com> wrote:
 

 Can you check if this still happens with rc3?—

**Comment by h0tw1r3** [comment]
@mickelson Confirmed on RC3-1. It's actually not locking up, it's just not returning focus. Maybe related to #199?

If I press alt-tab attract is instantly unstuck.

**Comment by omegaman1** [comment]
In my case alt-tab doesn't unfreeze. I need to do a crl-alt-del and kill the task. Also, I made sure there was nothing running in the system tray to take focus away. 

Here are some registry settings that you can edit to help fix focus issues. It didn't work for me, though.
regedit > HKEY_CURRENT_USER\Control Panel\Desktop

ForegroundLockTimeout Default 20,000 milliseconds. Specifies the time, following user input, during which the system keeps applications from moving into the foreground.

ForegroundFlashCount Default value is 7, set to 0 to disable taskbar button flashes

**Comment by h0tw1r3** [comment]
@omegaman1 could you try this test build? https://build.zaplabs.com/dl/project/attractmode/.temp/attract-v2.0.0-rc3-test-win64.zip

**Comment by omegaman1** [comment]
Problem still exist. So, It does look like a focus issue after all. It seems that windows 10 handles focus a  little different than win8 does. Devs discussing a similar issue with their app. 

https://github.com/atom/electron/issues/2867

One solution...
If I call window.minimize() right before window.focus(), I can get the window to the foreground no matter what on Windows 10.

**Comment by h0tw1r3** [comment]
If AM is hard locking (can't task switch to it) as you initially reported, the issue is probably different.

Are you running in Desktop or Tablet mode?
How are you launching AM (script, console, or explorer/icon)?

**Comment by h0tw1r3** [comment]
@omegaman1 Reworked message handling a bit. Please try this build. https://build.zaplabs.com/project/attractmode/.temp/attract-issue193.zip

**Comment by omegaman1** [comment]
I'm running in desktop and using a shortcut but also tried from console. That said, newest build still a no go for me.

**Comment by h0tw1r3** [comment]
Are you sure you downloaded https://build.zaplabs.com/project/attractmode/.temp/attract-issue193.zip ?

This issue is separate from the other issue, and the test builds have a completely different focus.

**Comment by omegaman1** [comment]
Positive :p  I  even downloaded it again to be sure. And, just to rule somethings out, I tested MAME using a different front-end without issue.

**Comment by omegaman1** [comment]
Yay! Great, the nightly build fixes the problem for me as well.
