### ISSUE TITLE
Crash on generating mame rom list

### ISSUE THREAD

**Issue by keilmillerjr** [mickelson/attract#198]
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	attract.exe
  Application Version:	2.0.0.0
  Application Timestamp:	af50af48
  Fault Module Name:	attract.exe
  Fault Module Version:	2.0.0.0
  Fault Module Timestamp:	af50af48
  Exception Code:	40000015
  Exception Offset:	00000000015e0bea
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	7f37
  Additional Information 2:	7f37aa6d3c0348cf5d13b1f460364815
  Additional Information 3:	19d2
  Additional Information 4:	19d29ce26364475bcce24d2a05458e58

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

> # Generated by Attract-Mode v2.0.0-rc2
> #
> executable           $HOME/Apps/GroovyMame171/groovymame64.exe
> args                 [name]
> rompath              $HOME/Apps/GroovyMame171/roms/
> romext               .zip;.7z;<DIR>
> system               neogeo
> import_extras        $HOME/Apps/GroovyMame171/mame.xml;$HOME/Apps/GroovyMame171/catver.ini
> artwork    flyer           
> artwork    marquee         $HOME/Apps/GroovyMame171/marquees/
> artwork    snap            $HOME/mame/videos;$HOME/Apps/GroovyMame171/snap/
> artwork    wheel           

I have tried importing listxml and adding mame.xml under import_extras. Both crash at 17%. Any ideas? Running Windows 7.

**Comment by mickelson** [comment]
ha yeah, I'm pretty sure I just fixed this yesterday!:

https://github.com/mickelson/attract/commit/449f5b94cfcd9db613a5b4aeccc5db41d37a2146

I'm planning on doing a a new release candidate soon so you should be able to test this fix very soon.

**Comment by keilmillerjr** [comment]
Awesome! I'll check it out when released and report back. :+1:

**Comment by keilmillerjr** [comment]
Issue resolved with candidate 3. Thank you @mickelson !
