### ISSUE TITLE
fade.nut module does not fallback to layout missing art

### ISSUE THREAD

**Issue by ArcadeBliss** [mickelson/attract#202]
when using the fade.nut module and the next chosen artwork is missing, it should load the default artwork from the layout directory. I have modified my fade.nut with 3 lines of code to make this happen. 
The code is commented with "// changed: ArcadeBliss
[fade.nut.txt](https://github.com/mickelson/attract/files/192832/fade.nut.txt)

**Comment by mickelson** [comment]
Thanks, I've checked in your changes

**Comment by ArcadeBliss** [comment]
cool thanks.
