### ISSUE TITLE
Makefile: mkdir obj should be run in priority

### ISSUE THREAD

**Issue by akien-mga** [mickelson/attract#207]
I've had an issue when trying to build attract for the first time in a git clone, using ``make -j3``.
It spawned three parallel instructions for ``mkdir obj``, ``mkdir obj/squirrel`` and ``mkdir obj/sqstdlib``, and someone the last two were faster and failed because ``obj`` hadn't been created yet.

I haven't managed to reproduce it reliably, but to be on the safe side, you should probably either:
- ensure that ``mkdir obj`` is run first, and that the rest are only processed once it has succeeded, even when using parallel make
- or simpler, use ``mkdir -p`` to have the ``mkdir -p obj/squirrel`` succeed even if ``obj`` is missing.

**Comment by mickelson** [comment]
Ok, I've changed the makefile to now use mkdir -p
