### ISSUE TITLE
raspbian pi jessie sudo apt-get install libudev-dev fails with 404 error

### ISSUE THREAD

**Issue by MikesAracade** [mickelson/attract#208]
I'm trying to build attract mode for the 1st time following instructions for compiling on my raspberry pi-3 with raspbian jessie.  The compile is failing because of missing dependencies which I cannot install.
I'm a total newbie with raspberry pi.  1st compile EVER.

The following commands fail with 404 errors:

sudo apt-get install libudev-dev
sudo apt-get install libavutil-dev
sudo apt-get install libavcodec-dev
sudo apt-get install libavformat-dev
sudo apt-get install libavfilter-dev
sudo apt-get install libswscale-dev
sudo apt-get install libavresample-dev

Here are the errors for the 1st line:
---------------------------------------
sudo apt-get install libudev-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libudev-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 23.2 kB of archives.
After this operation, 261 kB of additional disk space will be used.
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libudev-dev armhf 215-17+deb8u3
  404  Not Found [IP: 5.153.225.207 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/s/systemd/libudev-dev_215-17+deb8u3_armhf.deb  404  Not Found [IP: 5.153.225.207 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

------------------------------------------
Any ideas on how to resolve this?

**Comment by mickelson** [comment]
try running "sudo apt-get update" first, and then try to install the dependencies...

**Comment by MikesAracade** [comment]
That did it! Why?

**Comment by philenotfound** [comment]
Your package list was outdated, as in newer versions of the packages were available.. the old ones were removed, that's why you got a 404. "apt-get update" redownloads the package list so your local package database knows about the currently available packages and their respective versions.
