### ISSUE TITLE
Resolution Change problem RC3

### ISSUE THREAD

**Issue by ArcadeBliss** [mickelson/attract#209]
Hi,
I have Attractmode running at 800x600 on my trisync arcade monitor. I start the emulator Supermodel with a resolution of 496x384. Supermodel runs fullscreen ok. After returning to Attractmode, the resolution changes back to 800x600 but Attractmode somehow thinks it is still at 496x384.

I have included a video to illustrate the problem. Pay attention to the cools layout, after returning from supermodel, you can not see everything. Also the Attractmode close window helps to show the problem. 

Video Link: https://youtu.be/EhhtkSOjs1g 

Let me know if I can provide more information.

**Comment by mickelson** [comment]
are you sure that the video mode goes back to 800x600 after supermodel runs?

you could try using the "resfix" plugin... see: https://github.com/mickelson/attract/issues/80

**Comment by ArcadeBliss** [comment]
just found the res plugin and it works like a charm sorry for the bug report when you already had an answer for it :)
