### ISSUE TITLE
2.0 RC3 Nightly build 17 - "Error parsing xml output:" when building MAME list

### ISSUE THREAD

**Issue by chris-vg** [mickelson/attract#212]
I just grabbed the latest nightly to test out and set it up from scratch, I added the most recent catver and nplayers ini files and generated a list for MAME.

The list generation message in the middle of the screen in AM stayed at 0%.  I opened up my console window and it was outputting the entire -listxml output with "Error parsing xml output:" interspersed throughout. 

It did actually generate a list in the end, however it's missing all of the metadata from MAME, it just has the romname, title (just the rom name repeated, not the actual title from the metadata), emulator name for AM, and the catver category metadata.  It didnt add any metadata from nplayers strangely enough.

I've just re run it again, without any extra ini files, and it's done the same thing, but of course no catver this time.

after it has finished running the list i get this output in the console:

```
 ! No XML output found, command: d:\emulators\mame_official172\mame64.exe -listxml
 - Removing any duplicate entries...
 + Writing 11020 entries to: D:\Frontends\attract-v2.0.0-rc3-17-win64\romlists/mame.txt
```

I've attached my mame.txt so you can see the full output.
[mame.txt](https://github.com/mickelson/attract/files/219434/mame.txt)

**Comment by chris-vg** [comment]
this is still an issue with 2.0 release build.

I've only got Windows 10 here to test with, so not sure how many others this is affecting.

**Comment by chris-vg** [comment]
Ok, just did a bit more testing.. this seems to be specific to MAME 0.172 official release.  Just tested it with 0.171 and it works fine.

**Comment by mickelson** [comment]
Ok, I've been having trouble reproducing it myself, I'll check with 172

**Comment by chris-vg** [comment]
ohhhhh... i think i see the problem.. I have got the highscore LUA script enabled in 0.172 here. It seems there's a bug in mame's console output that includes the LUA script output before outputting the xml..

0.171: mame64 -listxml > mame171.xml
```
<?xml version="1.0"?>
...
```

0.172: mame64 -listxml > mame172.xml
```
Starting plugin hiscore...
<?xml version="1.0"?>
...
```

**Comment by chris-vg** [comment]
PS: if you want to try and replicate this, in 0.172 you should have a plugin.ini file, set hiscore to 1 and that should do it.

**Comment by chris-vg** [comment]
Ok and yeah, i just set hiscore to 0, went back to AM and was able to generate a list just fine :)

**Comment by h0tw1r3** [comment]
Have you checked with the mame team? Definitely an upstream regression.

**Comment by chris-vg** [comment]
Considering I only found the bug a few days before 0.173 was due to come out, no I didn't bother.

I've just downloaded 0.173 and tested listxml with plugins enabled and there is no erroneous console output.. seems to be all good now.
