### ISSUE TITLE
Feature Request: add show/hidden option

### ISSUE THREAD

**Issue by fbs777** [mickelson/attract#213]
I have an idea to hide/show a rom and maybe would be simple to add this function.

1- In the end of each rom line in romlist file, add ";1" (default, to show the rom) or ";0" (to hidden the rom) when create a new romlist
2 - In the controls menu in config mode, add an option to set an input for the show/hidden option
3 - Like the Favourites, pressing the choosen input will show the option (bad english, so need corrections):

              "Add 'GAME_NAME' To Show or To Hide?"

                    To Hide (to hide the game setting the value to "0" in the romlist)
                    To show (to show the game setting the value to "1" in the romlist)
                    Show All (restore all the hidden games setting the value "1" on all games in the romlist)

4 - Add a filter target option for the hide mode to filter all the games with the value "0" (to show only the hidden games) or "1" (to show all but the hidden games) in the last field in the romlist.

**Comment by chris-vg** [comment]
why not just create a filter that excludes certain games?

```
	filter               SomeGames
                ...
		rule                 Name not_equals romname1
		rule                 Name not_equals romname2
		rule                 Name not_equals romname3
                ...
```

**Comment by fbs777** [comment]
If you have a No-Intro complete pack is impossible to create 100, 200, 300, 500 rules, you will take months to do this way. Can you imagine someone adding 100 rules in this way to create 100 favourite games?

Im talking about something as simple as add/remove a favourite: you see the game in the menu, you click the game and you select to hide the game

**Comment by fbs777** [comment]
Btw, a good idea is to create a second favourite option, just renaming all the favourite's code to hide, something like an "hidden favourites", then you can go to the rule's filter and select to not show all the hidden favourites.

This is even better because the code already exist, just need to clone the favourite to make 2 favourites, one to show only the favourites and the other to show all but the hidden games (second "favourites")

**Comment by mickelson** [comment]
check out the add/remove tags feature, it can do exactly what you are looking for

1. map the 'add/remove tag' feature in the controls config

2. use this to add a new tag, call it "hidden" or something

3. add this tag to all the games you want hidden

4. add a rule to the global filter for your display that filters where "Tags" contains "hidden" (or whatever tag name you used)

**Comment by fbs777** [comment]
Yes, the tag feature already does it. it can act as infinity "favourites" mode.

I was thinking the tag feature was much more complicated...

So this can be closed, thank you.
