### ISSUE TITLE
Un-favouriting a favourite

### ISSUE THREAD

**Issue by keilmillerjr** [mickelson/attract#214]
1. View favourites filtered list.
2. Press key to un-favourite it.

Game Info on front end updates to the next rom as one would expect, but artwork for the no longer favouroite rom remains. I tested this with my layout mvscomplete, and the cools layout.

**Comment by chris-vg** [comment]
I work around this by manually updating the file_name property of image/artwork objects using fe.get_art() during the Transition.ToNewList event.

**Comment by keilmillerjr** [comment]
@chris-vg Thanks for the work around. I’ll give it a try.

**Comment by mickelson** [comment]
Fixed, thanks
