### ISSUE TITLE
fe.get_art() causes hard crash in AM when image is missing

### ISSUE THREAD

**Issue by chris-vg** [mickelson/attract#215]
so, before the favourites bug got fixed a few days ago, I had set up a work around in a layout I'm working on that uses image objects instead of artwork objects, and then on transition events i would manually use fe.get_art to get the filename for each image object and then replace the image.file_name property with the output of fe.get_art.

It has since come to my attention that if an image for a game is missing, fe.get_art will cause AM to hard crash.  This has been observed on Windows 10 and OSX.

I'll write up a sample layout to show this behavior in the next day or so.

**Comment by chris-vg** [comment]
```
/*
Test layout to reproduce bug in fe.get_art().
*/

local snap_file = fe.get_art("snap", 0, 0, Art.ImagesOnly);
local snap = fe.add_image(snap_file);

fe.add_transition_callback("update");

function update(ttype, var, ttime)
{
    if (ttype == Transition.ToNewList || ttype == Transition.FromOldSelection)
    {
        // this is where the crash occurs if fe.get_art is unable to find an image matching the current rom name.
        // will only occur if Art.ImagesOnly flag is set.
        snap_file = fe.get_art("snap", 0, 0, Art.ImagesOnly);

        snap.file_name = snap_file;
    }
}
```

**Comment by mickelson** [comment]
It figures this would turn up right when the new version gets released... duoh!

Thanks for the info on how to reproduce, it's fixed now (I think)
