### ISSUE TITLE
No rendering when dragging AM window

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#222]
I feel silly adding bugs? for windowed mode, but I do a lot of testing in windowed mode so I notice them :)

I'm not sure this is the desired outcome - when you drag a window around, the rendering stops until you left go of the mouse button to stop dragging. I kind of expect it to render when dragging since the window is focused. I think it should only not render when it doesn't have focus (or ideally minimized/hidden?)

**Comment by mickelson** [comment]
This appears to be a problem in SFML's windows implementation.  When I drag around attract-mode in a window on linux, it keeps rendering, but on windows 10 it stops during the drag.  I don't think there is anything we can do in the attract-mode source to address this (so I'll close this issue for now).
