### ISSUE TITLE
Pi3 RetroPie/Attract Mode Nintendo DS image

### ISSUE THREAD

**Issue by rawbe** [mickelson/attract#223]
Hello- Is their a fix for the Nintendo DS logo showing up for Mame4all missing artwork/marquee/flyer/wheel art? 

Thank you!
Robbie

**Comment by robertybob** [comment]
Why do you think the RetroPie devs would be the people the ask? They have nothing to do with Attract Mode, and the only way to get it working with RetroPie is either using Floob's image or for someone to build it themselves...

**Comment by rawbe** [comment]
So you don't know how to change the default image "Nintendo DS" robertybob?

**Comment by mickelson** [comment]
The readme file that comes with attract-mode explains how artwork gets chosen: https://github.com/mickelson/attract/blob/master/Readme.md

It looks like you have a nintendo ds image in as one of the default images.  The fix would be for you to replace this image with something more appropriate.

Try posting on the support forum if you need more help: http://forum.attractmode.org
