### ISSUE TITLE
cannot install on ubuntu really bad package management!

### ISSUE THREAD

**Issue by gameslayer** [mickelson/attract#226]
the .deb is missing a big list of dependencies that are no longer able to install

sudo -s dpkg -i /home/linuxlite/Downloads/attract-v2.0.0-amd64.deb
Selecting previously unselected package attract.
(Reading database ... 165256 files and directories currently installed.)
Preparing to unpack .../attract-v2.0.0-amd64.deb ...
Unpacking attract (2.0.0-1) ...
dpkg: dependency problems prevent configuration of attract:
 attract depends on libavcodec56 (>= 6:11~beta1) | libavcodec-extra-56 (>= 6:11.4); however:
  Package libavcodec56 is not installed.
  Package libavcodec-extra-56 is not installed.
 attract depends on libavformat56 (>= 6:11~beta1); however:
  Package libavformat56 is not installed.
 attract depends on libavresample2 (>= 6:11~beta1); however:
  Package libavresample2 is not installed.
 attract depends on libavutil54 (>= 6:11~beta1); however:
  Package libavutil54 is not installed.
 attract depends on libjpeg62-turbo (>= 1.3.1); however:
  Package libjpeg62-turbo is not installed.
 attract depends on libsfml-graphics2 (>= 2.1); however:
  Package libsfml-graphics2 is not installed.
 attract depends on libsfml-network2 (>= 2.1); however:
  Package libsfml-network2 is not installed.
 attract depends on libsfml-system2 (>= 2.1); however:
  Package libsfml-system2 is not installed.
 attract depends on libsfml-window2 (>= 2.1); however:
  Package libsfml-window
dpkg: error processing package attract (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 attract

**Comment by philenotfound** [comment]
Try an "apt-get -f install" afterwards

**Comment by h0tw1r3** [comment]
deb's are distro specific. Many times you can get away with installing a deb on distro X that was build on Y, but usually (eventually) they break. I suggest compiling it yourself.

**Comment by gameslayer** [comment]
Not really if the package is done well it will for example work on any Debian/ubuntu based system just like how appimage is universal to all distros

**Comment by h0tw1r3** [comment]
@gameslayer that is misleading at best.

As I said, often you can get away with it, but eventually - particularly if there are dependencies on external libraries - those dependencies will diverge between distros and you will enjoy the breakage. **No matter how well the package is done**.

If your statement was correct, there would be little need for packages distributed by debian, ubuntu, deb-multimedia, etc. specific to each distro and each named release.

Appimage is an entirely different beast which was created to solve this type of problem (be distribution-agostic, and obviously a lot more).

**Comment by gameslayer** [comment]
@h0tw1r3 Not really if the package is done right you don't run into these issues with the dependencies build in, if any are needed it would of told you to install it but installing the dependencies for this package doesn't exist.

**Comment by philenotfound** [comment]
@h0tw1r3 We should state that the .deb package is built for Debian Jessie.
@gameslayer Which distribution are you using?

**Comment by gameslayer** [comment]
@philenotfound Ah I see I am using Xubuntu 14.04

**Comment by philenotfound** [comment]
@gameslayer There is no way to build that .deb universal. It is built for Debian Jessie, which is newer than Ubuntu 14.04. For example the libavcodec56 package is built from the libav source package, where is Ubuntu 14.04 the libav source package builds libavcodec54.

You can either:
* Update your Ubuntu to a newer release, providing libavcodec56
* Build it from source
* Build a new .deb targeting Ubuntu 14.04
* Use libav backports for Ubuntu 14.04, if they exist or build them yourself

**Comment by gameslayer** [comment]
@philenotfound ok where do you get the new 14.04 package? when I downloaded the ubuntu package they had on the website it was the same as the debian jessie package

**Comment by mickelson** [comment]
The only deb that is distributed by the project is pretty clear that it is for Debian 8 64-bit.

Akafox on the forum has posted some ubuntu debs.  You should ask him if you have questions about them.

Oh and for what it is worth I lose my mind when it comes to trying to figure out linux package management.  Any and all help with this stuff is greatly appreciated.

**Comment by davewongillies** [comment]
This won't help (at the moment) for users for Ubuntu Trusty 14.04 but I've just a PPA which at the moment has packages for Ubuntu Xenial (16.04) and Yakkety Yak. The PPA can be found here:

https://launchpad.net/~daveg/+archive/ubuntu/attract

I'll hopefully have Ubuntu Trusty (14.04) packages soon once I figure out a build issue I'm having.

**Comment by davewongillies** [comment]
And I've built a package for Ubuntu Trusty (14.04)

**Comment by davewongillies** [comment]
@gameslayer you get download a working attractmode package for Ubuntu 14.04 from [my ppa](https://launchpad.net/~daveg/+archive/ubuntu/attract)
