### ISSUE TITLE
D-Pad and analog stick stop working after press RT button

### ISSUE THREAD

**Issue by fbs777** [mickelson/attract#228]
Today git version (with Issue #124 included) tested with the xbox 360 usb controller on Raspberry Pi 2.

Its hard to define a new function for LT and RT buttons (analog buttons). After press the button nothing happens, then pressing again the function is defined with the "min." + "max." RT.
After 5,6 tries finally is possible to define the function with just one RT "key"

And after the RT right configured, if pressed in the display the D-Pad and analog stick dont work anymore until restart the AM (but work in the menu options)
Sometimes even the keyboard stop working, and i need to force the AM to kill using the SSH

**Comment by fbs777** [comment]
With the new commit now i can define a function for the LT and RT without problem, but the bug still there:

1 - Configure both D-Pad and analog stick to act as up, down, left, right
2 - Choose a function for LT and RT (in my case LT = Back/Exit confirm and RT = Add/Remove tags)
3 - Go to the display screen and test the up/down to change the game with both d-pad and analog stick. Will work fine.
4 - Press LT to exit (select cancel to go back to the game selection) or RT to add a new tag and then cancel
5 - Ok, now dont matter if you pressed LT or RT in the step 4, the LT dont work anymore (RT still work) and both d-pad and analog stick dont work anymore to change a game with up/down and dont work to change the display with left/right. But both d-pad and analog stick still work in the configure screen, just dont work in the display game selection.
All the digital buttons (except d-pad) and keyboard still work in the display layout, but a few times (i dont know the rule for this) after press LT or RT (and after cancel the action) in the game selection display all the functions dont work anymore in both xbox 360 controller and keyboard, then i need to press crtl+alt+del to reboot or kill the AM using the SSH.

**Comment by mickelson** [comment]
ok thanks for the tests, I'll check this out some more
