### ISSUE TITLE
Windowed Screen (mac) - layout cut off

### ISSUE THREAD

**Issue by keilmillerjr** [mickelson/attract#229]
When using mac 10.14.4 and attract mode 2.0.0, the bottom of all layouts are cut off when using windowed mode. Size and position of the windowed does not eliminate the error. Perhaps the scaling is incorrect. This bug does not occur when I use Windows 7.

**Comment by mickelson** [comment]
My guess is that the amount that is cut off is about the same amount as the height of the Mac's menu bar.  Is that correct?

**Comment by keilmillerjr** [comment]
Still the same issue with 2.2.0 on mac OS X. Not yet resolved. Also getting issue with layouts not finding modules.

**Comment by keilmillerjr** [comment]
I noticed issue is resolved with attract 2.3.
