### ISSUE TITLE
UTF8 issue for romlists file

### ISSUE THREAD

**Issue by kent79** [mickelson/attract#230]
I try to change romlist file to utf 8 format since I would like to show game's name out of English language. After changed format, the first game's name is changed to "title". Please advise and fix it. Thanks.  
![12](https://cloud.githubusercontent.com/assets/13723897/16135057/8cf02138-3453-11e6-9926-fcc2350735f6.jpg)

**Comment by mickelson** [comment]
The easiest fix would be to open the romlist file with a text editor and delete the first line.

cheers

**Comment by kent79** [comment]
Tested. It works.  1st game's name shows correct now. But the snap video doesn't

**Comment by mickelson** [comment]
I'm not really sure what you are doing to "change the romlist file to utf 8 format"

The romlist files are simple text files, and the frontend already treats all characters in them as utf-8 encoded.

It might be that whatever you are doing is adding hidden characters to the start of the file, which will mess up the first entry in the list.
