### ISSUE TITLE
Option to revert back to not randomizing artwork, as in pre 2.1.0 versions

### ISSUE THREAD

**Issue by rsn8887** [mickelson/attract#231]
Before 2.1.0, AM prioritized artwork by the sequence of locations, separated by ;, specified in the emulator settings. 

If there was artwork in the first location, it used that one always. 

If there was no artwork in the first location, then and only then would it look in the second location.

In version 2.1.0, if there are multiple matches, it always randomizes the artwork from the different locations. This leads to unpredictable artwork being displayed, and often crappy "fallback" artwork being displayed for games that have "nice" artwork in the first folder.

The old behaviour was a handy and deterministic feature. It would be great if it was still available as an option. 

Is it possible to add a config switch to revert back to the old behaviour if desired?

**Comment by mickelson** [comment]
Ok this is what caused the change: https://github.com/mickelson/attract/issues/227

I think I will revert that fix so that the old behaviour comes back, and I will try to figure out another way to address the original issue...

**Comment by rsn8887** [comment]
Yes that would be perfect. Or an option to choose between the two behaviors as long as randomization can be switched off :)
