### ISSUE TITLE
Scraper Adding Extra Artwork for Random Systems

### ISSUE THREAD

**Issue by Enverex** [mickelson/attract#232]
So I noticed some unrelated artwork being shown on some themes, e.g. MAME showing Nintendo DS icons for missing wheel art and assumed it was an issue with the theme, except it appears to actually be an issue with the scraper.

For example, I have a bunch of systems set up, one of which is Atari ST. Inside ".attract/scraper/atarist" is the respective set of artwork folders. But inside .attract/scraper/atarist/fanart is another folder named atarist which contains 3 images. A picture of a Dreamcast, a Dreamcast logo and a collage of Dreamcast stuff. Inside the flyer folder for atarist is a file named atarist.jpg which again is just a Dreamcast logo. Same with marquee, a file named atarist.jpg and it's a banner of for Dreamcast.

The same system confusion appears to apply lots (but not all) other systems too. For example MAME has these files but for a DS.

Despite this, it has also correctly downloaded artwork for the games on those systems into their respective folders.

Any idea what's happened here? My config files all look fine and all have the correct references/folders/names/systems.

**Comment by Enverex** [comment]
Example...

```
*** Scraping artwork for: amiga
 + Downloaded: /home/arcade/.attract/scraper/amiga/fanart/amiga/3-1.jpg
 + Downloaded: /home/arcade/.attract/scraper/amiga/fanart/amiga/3-4.jpg
 + Downloaded: /home/arcade/.attract/scraper/amiga/fanart/amiga/3-2.jpg
 + Downloaded: /home/arcade/.attract/scraper/amiga/fanart/amiga/3-3.jpg
```

... where it appears to be downloading N64 images. e.g. 3-1 is...
![image](https://cloud.githubusercontent.com/assets/958670/16385166/a177aaee-3c83-11e6-8729-5f9d2a752dd8.png)

The actual game images are fine.

The reason this is an issue is because it keeps using these (wrong) images in place of missing titles which is quite confusing.

**Comment by mickelson** [comment]
Ok, definite bug.  Thanks for the report, this should be fixed now.

**Comment by Enverex** [comment]
Great, thanks mickelson.
