### ISSUE TITLE
Front end freezing

### ISSUE THREAD

**Issue by Scarletpanda17** [mickelson/attract#234]
Somehow while attempting to adjust settings in retro arch, my NES section started have ng problems. I select a game but nothing happens for a few seconds. The video pauses for the briefest of seconds but when the emulator comes up, the music from the video is playing in the background. Then when I exit the emulator the front end is still frozen. I can reboot with Carl-alt-delete but nothing else seems to work. I thought it might be a waiting issue but when I changed it to 1 second it worked going in, but still froze when coming out of the emulator. It is only effecting one display and deleting and remaking it did not remove the error.

**Comment by Scarletpanda17** [comment]
It seems to be an issue with pi-NES theme. Changed to pi-SNES and it is not doing it anymore.

**Comment by Scarletpanda17** [comment]
It loaded okay but still froze on exit with a different theme...

**Comment by mickelson** [comment]
What OS?  You are using pi named themes, so does that mean you are on a raspberry pi?
Are any messages printed at the command line?
