### ISSUE TITLE
Game Description / Flavour Text?

### ISSUE THREAD

**Issue by Enverex** [mickelson/attract#237]
Is it possible to have a field added (or is there an existing one?) that can be used for game flavour text? I've got a paragraph or two description for every game I have, but I can't find a relevant field in the romlist for AttractMode that it would actually go in to.

Same applies to "rating" of the game. I've got all this info scraped and ready, but no-where to put it.

EDIT: Putting it in the Extra section seems to work fine, but I'm not sure if that field is designed for another use.

**Comment by mickelson** [comment]
I've been thinking of adding this, but I don't think the current structure of the romlist file supports it very well (romlist has one rom per line, game flavour txt should probably support multiple lines of text).  So I'm not sure how best to add it.

The extra section is probably as good a place as any for now, if I recall correctly it only gets used to flag a few unique things about MAME roms (chd games for example).

**Comment by ArcadeBliss** [comment]
Adding this to extras would make the romlist become illegible and very big. Mabye it can also be implemented such as an extra file such as tags and have it be read unsing Info.game_descripiton. The nice thing about an extra file is that you can be more flexible with the layout of the file to promote quick parsing.

**Comment by Enverex** [comment]
I've actually put the flavour text in as the Extras column in mine for now (cropped to around 150 characters) but yeah, a separate file may be a better choice as long as it doesn't increase loading time. There's already a few seconds delay sometimes when opening my (trimmed) MAME list (roughly 2600 games) which is unfortunate.

**Comment by mickelson** [comment]
Updating old issues, game overview/descriptions have been implemented for a while now:

540ffb6ad022bb59a519a8f01b9926fb4900b941
88595c811b2ebe717d1c9ea116373531b92cc6cb
