### ISSUE TITLE
Vertical Text Alignment / Positioning

### ISSUE THREAD

**Issue by Enverex** [mickelson/attract#241]
I've noticed that text has a Left, Right and Center alignment, but not vertical which means when you have a box of text, it's almost impossible to have it look neat because it essentially emanates from the center of the box, rather than the top left as you'd generally want or expect when dealing with text-blocks.

Any chance of implementing this? (or does it exist and I've somehow never seen it mentioned anywhere).

**Comment by mickelson** [comment]
Implemented in: 2fb0e90347a967072c2f3b54a9af4631c20b5808
