### ISSUE TITLE
Some ROMS don't work in Attract Mode

### ISSUE THREAD

**Issue by newmantjn** [mickelson/attract#243]
I have a list of about 20-30 roms that I ran many times in my mame32 front end.   They all worked fine.  I downloaded and configured Attract Mode last night and even pointed the rom directory (exclusively) to the same rom directory used by mame32.   Many of the games do not load now.
 One in particular is the 1943 game.  I verified back and forth that it works in Mame32, but not Attract Mode.

Any ideas? 

Thanks.

**Comment by mickelson** [comment]
Hi I don't have any ideas.  I suggest posting on the forum, someone there should be able to help.

This doesn't sound like a bug in attractmode, more like a configuration problem, so I'm going to close this issue.
