### ISSUE TITLE
Loses focus after exiting mame.

### ISSUE THREAD

**Issue by kaptainsteve** [mickelson/attract#244]
Hello, I have Windows 10 and AM loses focus when exiting Mame game and you have to click the mouse in order for it to get focus back.

Tried everything... uninstalled all taskbar notices, antivirus, etc.  
I've reinstalled fresh installations and the problem is the same.

It's a shame, I've loved the program but in a cabinet I can't keep the mouse out to be clicked all the time.  For the record, it didn't used to do this in W10 but something changed at some point and now it won't go away?

Thanks.

Steve

**Comment by kaptainsteve** [comment]
Found the problem!
It's a conflict between Mame and AM if you set the exits in both to the same control.
They must be different.
For example, on Mame the exit is set to esc while on AM it's set to a button like joy01but02 it works fine.
Thanks.
I hope this helps for others who run into this...

**Comment by mickelson** [comment]
Thanks, good to know as there seem to be a couple of focus problems with Windows 10...
