### ISSUE TITLE
Images Get "Stuck"

### ISSUE THREAD

**Issue by Enverex** [mickelson/attract#245]
I've ran into an odd issue now that I've not seen before and I'm not sure what's triggering it, but it seems to have started happening within the last few days.

Basically, scrolling through the games works fine until I hit what I assume is a game that is missing a specific type of artwork, at which point this appears in the console:

```
AN ERROR HAS OCCURED [the index '1200420638' does not exist]

CALLSTACK
*FUNCTION [on_tick()] /usr/share/attract/modules/fade.nut line [84]

LOCALS
[temp] ARRAY
[ttime] 12629
[this] INSTANCE
Script Error in tick function: on_tick - the index '1200420638' does not exist
```

And what was previously in that position on the screen (e.g. the box-art) will no-longer update when I continue scrolling through the list, even through items that do have art available. Basically that image is now "stuck" there as whatever was there prior to trying to load the image that didn't exist.

No idea where the number 1200420638 comes from. It's not the name of any of the files involved.

**Comment by Enverex** [comment]
Going to check if https://github.com/mickelson/attract/commit/b23c88141cc52e8bc75b07a1b668c35fa50fd69f is related as it's the only recent commit that has anything to do with artwork.

**Comment by Enverex** [comment]
Yep, that commit is what broke it. Reverting it makes AttractMode work properly again. Now when artwork is missing, I get...

```
Failed to load image "/home/arcade/.attract/layouts/arcade/snap.png". Reason: Unable to open file
Error opening input file: /home/arcade/.attract/layouts/arcade/snap.png
```

... instead of a fault, and artwork correctly appears when I move to another game that does have artwork.

**Comment by mickelson** [comment]
Ok this should be fixed now, thanks
