### ISSUE TITLE
Display option "Show in cycle" isnt working very well

### ISSUE THREAD

**Issue by fbs777** [mickelson/attract#247]
I want to hide the display "Atari 5200" so i have change the "Show in Cycle" to "No" and "Show in Menu" to "no"

Before the change the order was Atari 2600 <-> Atari 5200 <-> Atari 7800

Now the Atari 5200 display isnt showing in the display menu (as expected), and when i press the previous display button in the Atari 7800 display the AM jumps to Atari 2600 display and skip the Atari 5200 (as expected too).

But when i'm in the Atari 2600 display if i press the next display button i go to the Atari 5200 display.

So the "Right (Next Display)" controls option isnt working as expected.
I have tested with the "Next Display" controls option too but still showing the Atari 5200

Im using the previous AM Jul 5, 2016 git version (w/ mmal support)

Edit: Actually, if i choose to hide the display Atari 5200 with "Show in Cycle" = "No" i cant choose a lot of displays with left/right, they just dont show anymore (only shows in the display menu), so i need to keep the Atari 5200 display "on" for now...

Just curious: where the info about show/hide display is saved? And how the attract.am works? For now i just know that the first number of the first line means the last display before exit and last number of the other lines (each line is a display in order) is the order of the filter selected on each display.

**Comment by mickelson** [comment]
Ok thanks found it... I was pretty sloppy on this one, I'm surprised it ever worked at all!

**Comment by mickelson** [comment]
Oh and for your other questions, the show/hide setting is saved in attract.cfg, the "in_cycle" setting under each display.

IN attract.am, the first line contains the index of the current display followed by the index of the display, filter and rom that the last game launch was from (used by the "relaunch last game" command)

The rest of the lines are the state for each display, with each new line being the next display... format is as follows:

	//
	// "[curr_rom];[curr_layout_filename];[curr_filter];"
	//
	// With [curr_rom] = "[rom_index filter0],[rom_index filter1],..."

Code is here:

https://github.com/mickelson/attract/blob/v2.1.0/src/fe_settings.cpp#L621

https://github.com/mickelson/attract/blob/v2.1.0/src/fe_info.cpp#L664
