### ISSUE TITLE
Feature Request...

### ISSUE THREAD

**Issue by kaptainsteve** [mickelson/attract#251]
How about an option for a screensaver that will randomly play mame games (attract modes) for a short time period (set the seconds like 60, 90, 180, 360)?

If it just plays random Mame games for 90seconds at  a clip then there is no need to download and save any attract videos which is really just a waste since they are already inside the game roms..

Thanks.

**Comment by kaptainsteve** [comment]
Some other requests;
A simple setting to assign a shut off system key from menu with having to use a lua script.
and....
A simple way to assign simultaneous key presses. Like P1 and P2 together to esc, etc.
again, not having to use autohotkey or a script.
Thanks.

PS. a big saver of headaches is your hot exit key... saves lotsa trouble, thanks!

**Comment by mickelson** [comment]
combo keys have been implemented: 75fb786b07a29a6244bebb93ce4abee5353dbbe0
shut off system key can be achieved by configuring the Config->General->"Exit Command" to whatever command line shuts down your system (such as "sudo shutdown" on linux)
