### ISSUE TITLE
Feature Request: ESRB Rating / Game Rating

### ISSUE THREAD

**Issue by ArcadeBliss** [mickelson/attract#252]
thegamesDB contains the ESRB ratings and user feedback readings for games. Can this be added to the scraper and ESRB and Rating to the romlist? This would allow use to make layouts such as this: https://i.ytimg.com/vi/CbH4qtVIu-U/maxresdefault.jpg. Also I have little kids playing my cab and I could use this as a filter.

Also I will be able to pass this info to Rocketlauncher futher enhancing my Load Screens. :)

**Comment by progets** [comment]
+1

**Comment by mickelson** [comment]
Rating scraping was added with: https://github.com/mickelson/attract/commit/69683ee91eeac0957f9442bbfb19aaaba0d27242#diff-25d902c24283ab8cfbac54dfa101ad31
