### ISSUE TITLE
Bug and Fix for animate.nut

### ISSUE THREAD

**Issue by ArcadeBliss** [mickelson/attract#254]
The current animate.nut does stop animations after the configured time has been reached.

to fix this problem, change the current line from:
`//stop the animation when we reach the end
        if ( config.when != When.Always && time >= config.time ) stop();`

to:
`//stop the animation when we reach the end
        if ( time >= config.time ) stop();`

**Comment by Enverex** [comment]
Are you sure you don't have "Always" enabled? As that's what you're removing here to make it work.

**Comment by ArcadeBliss** [comment]
I have not seen the option to disable always in the animate settings

**Comment by ArcadeBliss** [comment]
the new animate2 module addresses this issue.
