### ISSUE TITLE
windows 10 version 1607 windows task bar issue

### ISSUE THREAD

**Issue by kent79** [mickelson/attract#258]
Hi

I just updated windows 10 to latest version (1607). On the bottom of windows task bar was on the top while AM running. Please fix it. Thanks.  

![1](https://cloud.githubusercontent.com/assets/13723897/17437819/77bab186-5b52-11e6-9c60-f72958cf5cd1.jpg)

**Comment by Riot504** [comment]
Same issue when I upgraded to Anniversary update (1607).
