### ISSUE TITLE
Request Feature: Console selection Menu

### ISSUE THREAD

**Issue by almaesdi** [mickelson/attract#263]
Hello
First i want to congratulate you for this great project.

i would like a console selection menu like Emulationstation o Maximus Arcade. 
The most close of this, its the "displays selection", but is a ugly or unesthetic interface

it's possible?

Thanks!

**Comment by RobLoach** [comment]
Attract Mode is an alternative to EmulationStation or Maximus Arcade. You can set up those menus, but will need to go through the configuration of them.

**Comment by Enverex** [comment]
I've never seen anything regarding theming the console selection page (or an easy way to get to it). Can you elaborate please @RobLoach ?

**Comment by robertybob** [comment]
@Enverex Is  #https://github.com/mickelson/attract/commit/4e8cc1b49d4acd340e63c4a483e520e632a9b928 what you were after?
