### ISSUE TITLE
How to read the "executable " and "args" just after select the game?

### ISSUE THREAD

**Issue by amuser** [mickelson/attract#264]
I want to change the command line emulator on-the-fly (already done with scripts) but after change the emulator/emulator-name.cfg with a new "executable" and "args" lines, the AM still want to open the game using the old emulator and args, so i need to stop to buffer the content of "executable" and "args" lines and search for them just after select the game.

I know its possible to edit the emulator in the config options and there the changes are done on-the-fly, but this method is a pain, this take a lot of time to write the text in the controller, i just want to select the emulator in a list, the problem is: if i change the emulator/emulator-name.cfg with a script the AM still open the old "executable" and "args"...

**Comment by Enverex** [comment]
This is all loaded and stored on startup which is likely why it's ignoring your changes.

What about using a wrapper script instead and modifying the wrapper on-the-fly instead?

**Comment by amuser** [comment]
Yes, sorry, i forgot about wrapping a file. Its working now, thank you.
