### ISSUE TITLE
#264 Swf File-support Crash - Bug

### ISSUE THREAD

**Issue by atrfate** [mickelson/attract#265]
As Requested by ray form the scpirting forums

Animations That seem to work fine are
Fade in
And Rotation 

3d Rotation on Z axis results in crash

http://www.fastswf.com/UouxsfI

**Comment by mickelson** [comment]
It looks like the file uses actionscript constant types that aren't implemented by gameswf (?)

I've at least fixed the crashing now (I think).  Fixing the actual problem in gameswf is beyond me though.

**Comment by mickelson** [comment]
https://github.com/mickelson/attract/commit/57e7f263bb8771e15a3cfe92eb33fd33e2f00d8b
