### ISSUE TITLE
[Feature Request] Save controls for each joystick name/id

### ISSUE THREAD

**Issue by fbs777** [mickelson/attract#273]
I have an xbox 360 and ps2 clone joysticks and they don't have buttons on the same position (the button 0 in xbox 360 is the bottom A button and the button 0 in the ps2 control is the top triangule button)

So if i change the joystick all the configuration is changed because there's just one configuration for controls.

Would be great if AM could work like the emulation station and retroarch saving a control config for each joystick name/id

**Comment by mickelson** [comment]
Updating old issues, this has been implemented.  It is configured from Config->Controls->Joystick Mappings

See:
06cdab9d95a7950bac8ea08a3cea3a7f5b370704
13becfbad21dbdf422bbc5e1f1d1fb29c63ca0c9
