### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by revington** [mickelson/attract#278]
Hi, 

When I run this program for the first time it creates some configuration at ~/.attract but this is incomplete compared with the configuration located at /usr/local/share/attract. No emulators, no i18n files, no layouts, etc. Is this the expected behavior?

I'm compiling and installing this by my self with 
```
make -j 3
sudo make install
```

**Comment by mickelson** [comment]
Sorry this is so late but yes something is going wrong.  The contents of /usr/local/share/attract are meant to be copied over to ~/.attract when you first run. Try deleting ~/attract and re-running
