### ISSUE TITLE
My "Joystick UP" does not work please help!

### ISSUE THREAD

**Issue by KingVarus** [mickelson/attract#280]
Hey guys, i have built my own bartop arcade, now that its finished i came along the same problem. My UP does not work, it does though in retropie and in the games NOT in attract mode displays.

I updated the kernel via the Retropie setup, but that did not fix any problems.
I googled the last few hours about the stuff that users wrote in another threat here but that did not help me either. Could someone please tell me how to fix my problem, i´ve put so much work in my cabinet, yet i cant use UP on my Joystick...please help me

**Comment by mickelson** [comment]
appears that the fix is described in https://github.com/mickelson/attract/issues/250
