### ISSUE TITLE
can't upload from previous attract-mode

### ISSUE THREAD

**Issue by Invincer** [mickelson/attract#285]
My update will not work, after "make USE_GLES=1" I get this below. Tried numerous times. Any help would be appeciated! Thanks!!

"make USE_GLES=1"
flags: -Wl,--export-dynamic -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -I/opt/vc/include -L/opt/vc/lib -Iextlibs/miniz -Iextlibs/audio/include -D__STDC_CONSTANT_MACROS -I/usr/include/freetype2 -I/usr/include/AL  -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/gameswf  -DFE_RPI -DUSE_GLES -DUSE_FONTCONFIG -DUSE_AVRESAMPLE
fatal: No names found, cannot describe anything.
mkdir -p obj
Compiling obj/fe_base.o...
In file included from src/fe_base.cpp:24:0:
src/fe_util.hpp:28:27: fatal error: SFML/Config.hpp: No such file or directory
 #include <SFML/Config.hpp>
                           ^
compilation terminated.
Makefile:412: recipe for target 'obj/fe_base.o' failed
make: *** [obj/fe_base.o] Error 1

**Comment by tcordell8891** [comment]
I am experiencing the same error.

**Comment by calle81** [comment]
I had no problem updating after following the instructions on the wiki. I updated everything (SFML, ffmpeg etc).

The new SFML changes are for the newest firmware.
Use "sudo apt-get update; sudo apt-get upgrade" to get the latest firmware.

**Comment by tcordell8891** [comment]
Agreed. Follow the instructions here: 

https://github.com/mickelson/attract/wiki/Compiling-on-the-Raspberry-Pi-%28Raspbian-Jessie%29

And it works perfect.
