### ISSUE TITLE
Invalid Corruption Complaint

### ISSUE THREAD

**Issue by Enverex** [mickelson/attract#286]
I've noticed AttractMode often complaining about corrupt images, e.g.

`Lure of the Temptress.jpg". Reason: Corrupt JPEG`

But the image isn't corrupt. It verifies fine with jpeginfo and I've opened it in an image viewer and it looks file. 

`Lure of the Temptress.jpg  640 x 480  24bit JFIF  P   34843  [OK]`

I'm getting this on a bunch of images. But what's more odd is that it does actually load the images anyway (without any issues as far as I can see).

**Comment by mickelson** [comment]
I believe this is because AM tries first to load an image using SFML, and if that fails it falls back to using FFmpeg.  SFML spits out the error message you are seeing and the frontend can't really stop that I don't think
