### ISSUE TITLE
No emulation image with Attract Mode + Raspbian + RPi3

### ISSUE THREAD

**Issue by raonyi** [mickelson/attract#287]
Environment:
- Raspberry PI 3 B
- Raspbian 8.0 Jessy (FRESH install)
- No X environment.
- All OpenGL / SDL / etc.. libraries installed.
- SFML libraries used: https://github.com/mickelson/sfml-pi
- Attract mode compiled using: https://github.com/mickelson/attract/wiki/Compiling-on-the-Raspberry-Pi-%28Raspbian-Jessie%29
- Emulators tested: Mednafen, Retroarch-picodrive, Retroarch-nestopia, Dgen, ....

All compilations & installations ran without any issue.

Attract mode starts perfectly, I can create/modify any Emulator/Display and all Layouts are working even with artwork, but when trying to launch any emulator through Attract Mode:
- Some of them fail to start, and return to AM menu.
- Some others start emulating and sound is played, but the image freezes at the attract mode menu. No game image at all.
- Not a single emulator is working.
- Output errors are different for each emulator tested.

Of course, all emulators were tested beforehand and working perfectly being launched standalone without attract mode, just from the raspbian shell directly.

Besides that, sometimes the Attract Mode menu (the one accessed by pressing TAB) is showing strange symbols instead of letters (and this issue is shown only with certain layouts...).

Since Attract Mode is working properly as an extra package in Retropie, I'm assuming it can work also just with a fresh Raspbian.

This seems to have something to do with display drivers... But not sure how to troubleshoot further. Any thoughts?

**Comment by raonyi** [comment]
Got working Retroarch emulator but only using dispmanx as video driver. gl or sdl are still not working neither with Retroarch nor with any other emulator.

**Comment by mickelson** [comment]
I'm closing as this is looking kind of stale, I don't know enough about retropie or raspbian to be of any assistance.
