### ISSUE TITLE
Controller Priorities possible?

### ISSUE THREAD

**Issue by KingVarus** [mickelson/attract#289]
Hello Guys,

So i got my Bartop Arcade finished with two 8way Sticks and i was really happy with it.
But i wanted the SNES Pad for some games so i added 2 USB HUBS to the chassis of the arcade so i could connect USB devices to play with on certain games.
It does work but when i connect 4 controllers (2 of them being the 8 Way Sticks which i cant disconnect without pulling them from the pi) and 2 being SNES Pads i just cant get it to work that when i start the game, i can use just the 2 Pads.
I know that it´s because the SNES games are 2 player games and when 4 Controllers are connected Retropie cant figure out which controllers to use.
So i came up with one solution which is adding switches to the PowerCord for the USB decoders of the Sticks. Which should work!
So i wanted to ask you guys if there´s another solution for this, which is easier smarter?

**Comment by bostonmetz** [comment]
Hey King Varus, I also just finished a Bartop Arcade and am having a similar problem with my joystick "up" in attract mode that you mentioned on a previous thread.  Did you find a solution for it?  Also, I was thinking of doing the same thing you are with the SNES controllers.  I too installed extra USB inputs on the side of the cabinet.  Thanks for any help you can give me.  I'm very very new to any kind of Linux programming
