### ISSUE TITLE
"Unable to create texture, invalid size (0x0)" infinite loop on Windows 10 32 bits.

### ISSUE THREAD

**Issue by ErnestoBorio** [mickelson/attract#290]
When I try to run attract.exe on my Windows 10 32 bit PC, a command-line window opens with an infinite loop of lines that read: "Unable to create texture, invalid size (0x0)"
Needless to say, the program never starts.

**Comment by liquid8d** [comment]
I had this same issue before with Windows 10 on my Intel HD 3000 - MBP. I believe it was an issue related to the OpenGL implementation of the video card and the W10 drivers. Make sure you have the most recent drivers for your video card (which may or may not be the Windows built-in choice) - you will probably need to at least post what video card you have and your driver version.
