### ISSUE TITLE
Hidden displays cause wrong system to be selected when returning to system select

### ISSUE THREAD

**Issue by dedbawb** [mickelson/attract#297]
When you go into a system from your system selection list, and then back out to the system selection list again, if you have any "hidden" displays (displays with "Show in Cycle" set to "No") in your system selection list that come before the system you went into, the wrong system will be selected when you come back out.  You will be N systems too far down the list, where N is the number of hidden displays described above.

It seems the logic for reselecting the previously selected system when going back to the system selection screen is incorrectly including hidden systems when it calculates how many items down in the list it needs to go.

**Comment by mickelson** [comment]
thanks for the report, this should be fixed now
