### ISSUE TITLE
Snes9x on Mac needs a commandline tweak

### ISSUE THREAD

**Issue by AmazingVanish** [mickelson/attract#299]
I don't know if this can be remedied or not, but I'd love it if it could be.

In order to execute Snes9x from the commandline on a Mac, the open command must be used like so:

open -a /Applications/Snes9x.app "romname"

There is currently no way to tell AM to trigger the app this way. I tried specifying the open -a portion before the executable path but it was ignored. Is there a way to have AM trigger this way?

**Comment by mickelson** [comment]
Try the following emulator settings:
Executable: 'open'
Command Arguments: '-a /Applications/Snes9x.app "[romname]"'
