### ISSUE TITLE
[Help] Compile error

### ISSUE THREAD

**Issue by megamanzteam** [mickelson/attract#302]
I was following the directions for installing attract mode on Ubuntu/Retropie. I have Retropie installed on Ubuntu. I can get this command to work in terminal: `cmake .. -DSFML_RPI=1 -DEGL_INCLUDE_DIR=/opt/vc/include -DEGL_LIBRARY=/opt/vc/lib/libEGL.so -DGLES_INCLUDE_DIR=/opt/vc/include -DGLES_LIBRARY=/opt/vc/lib/libGLESv1_CM.so` Then I go to do `sudo make install` but get an error:

`[ 18%] Building CXX object src/SFML/Window/CMakeFiles/sfml-window.dir/Context.cpp.o
In file included from /home/shawn/develop/sfml-pi/src/SFML/Window/Context.cpp:31:0:
/home/shawn/develop/sfml-pi/include/SFML/OpenGL.hpp:51:29: fatal error: GLES/gl.h: No such file or directory
         #include <GLES/gl.h>
                             ^
compilation terminated.
src/SFML/Window/CMakeFiles/sfml-window.dir/build.make:62: recipe for target 'src/SFML/Window/CMakeFiles/sfml-window.dir/Context.cpp.o' failed
make[2]: *** [src/SFML/Window/CMakeFiles/sfml-window.dir/Context.cpp.o] Error 1
CMakeFiles/Makefile2:170: recipe for target 'src/SFML/Window/CMakeFiles/sfml-window.dir/all' failed
make[1]: *** [src/SFML/Window/CMakeFiles/sfml-window.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

I have tried to give it `-DSFML_RPI=0` in case that could have been an issue not being installed on a raspberry pi but get this error:
```
-- Could NOT find LIBXCB_IMAGE (missing:  LIBXCB_IMAGE_LIBRARY) 
CMake Error at cmake/Modules/FindXCB.cmake:93 (message):
  xcb-image not found
Call Stack (most recent call first):
  src/SFML/Window/CMakeLists.txt:223 (find_package)


-- Configuring incomplete, errors occurred!
```
I am still rather new to Linux so I am unsure how to proceed. When I looked at OpenGL.hpp and see this: (around line 48-52)
#elif defined(SFML_SYSTEM_LINUX) || defined(SFML_SYSTEM_FREEBSD)

    #if defined(SFML_OPENGL_ES)
        #include <GLES/gl.h>
        #include <GLES/glext.h>

I am unable to find the GLES folder or files. I tried to also follow your guide [Compiling on Ubuntu Xenial Xerus (16.04-LTS) amd64 desktop](https://github.com/mickelson/attract/wiki/Compiling-on-Ubuntu-Xenial-Xerus-(16.04-LTS)-amd64-desktop) but unable to do so.

When I do `make -j $(cat /proc/cpuinfo | grep -c processor)`
I get:
`flags: -Wl,--export-dynamic -I/usr/include/freetype2 -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/miniz -Iextlibs/audio/include -D__STDC_CONSTANT_MACROS -I/usr/include/freetype2 -I/usr/include/x86_64-linux-gnu -I/usr/include/AL -I/usr/include/x86_64-linux-gnu -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/gameswf  -DUSE_XLIB -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_SWRESAMPLE
fatal: No names found, cannot describe anything.
make: 'attract' is up to date.
`
It will still be the same message if I `sudo make install`. I am unsure how I can resolve this.

Thank you for your time.

**Comment by mickelson** [comment]
i think you should have the gles dir with the gl.h header in /opt/vc/include

could you check that it is there

**Comment by megamanzteam** [comment]
I do not have that. I only have Retropie in` /opt`. I also looked in `develop/sfml-pi/include` just in case. Anything else you need to know?

**Comment by mickelson** [comment]
Sorry it looks like I misread your earlier email. You're not on a raspberry pi, and you were following the raspberry pi instructions to build.  Try following the standard linux build instructions:

https://github.com/mickelson/attract/blob/master/Compile.md

https://github.com/mickelson/attract/wiki/Compiling-on-Ubuntu-Xenial-Xerus-%2816.04-LTS%29-amd64-desktop

**Comment by megamanzteam** [comment]
It looks like I managed to get it compiled without any noticeable errors. Now I am unsure how to run it and or connect it to the Retropie install in Ubuntu. I first looked in `/usr/local/bin` and see a file called attract, but will not run. I found the config files in `/usr/local/share/attract`. Thank you so far with your help mickelson and sorry for the very noobish questions.
