### ISSUE TITLE
Hyperspin.nut ignores overlayoffsetx and overlayoffsety from video overlay image (if present)

### ISSUE THREAD

**Issue by joyrider3774** [mickelson/attract#304]
Hi,
theme.xml can contain overlayoffsetx and overlayoffsety to define an offset for the overlay video image. Currently hyperspin.nut ignores this value. This is an easy fix though see diff below. You can easily add this value by editing a theme that has a video overlay and then in hypertheme editor add a video and change the offset values for X & Y for the overlay image then theme.xml will contain the values

The default konami classics theme is an example that uses offset values. If they are not used / taken into account, the video (actually overlay) is positioned to far to the left so you can see behind the television (on the theme) while with the overlays offsets enabled (fix below)  this does not happen see http://www.hyperspin-fe.com/files/file/9724-default-konami-classics-main-menu-43/ for the example theme

Also some of the themes of hyperspin show the video and / or overlay not correctly positioned. I haven't figured out what's causing this though, must be that hyperspin perhaps doesn't use the center as a position for the overlay to be postioned ? not certain though just a guess. i can supply example hyperspin themes where this is happening if needed. Those that have the problem did not have overlayoffsety or overlayoffsetx, but editing such theme in hypertheme editor and defining offsets for the overlays might make it easier to fix themes to make them work with attract mode.
i'm not certain if resolution has something todo with it my display is 800x600 while themes from hyperspin seem to be 1024x768 based. I tried hooking up my hdmi cable to the tv but saw the same result, although i'm not certain if just hooking it up is enough to make it use a the higher resolution

```
--- hyperspin.nut.bak	2017-02-13 00:24:40.925708674 +0000
+++ hyperspin.nut	2017-02-13 00:22:20.495608862 +0000
@@ -502,6 +503,8 @@
 			local type = "";
 			local start = "";
 			local vid_below=false;
+			local overlayoffsetx = 0;
+			local overlayoffsety = 0;
 
 			foreach ( k,v in c.attr )
 			{
@@ -516,6 +519,8 @@
 //				case "delay": d=v.tofloat(); break;
 				case "type": type = v; break;
 				case "start": start = v; break;
+				case "overlayoffsetx": overlayoffsetx=v.tointeger(); break;
+				case "overlayoffsety": overlayoffsety=v.tointeger(); break;
 				case "overlaybelow":
 					if ( v == "true" )
 						vid_below = true;
@@ -544,8 +549,8 @@
 
 				obj2 = ::hs_ent["video_overlay"].obj;
 				obj2.file_name = af2;
-				obj2.x        = x - obj2.texture_width/2;
-				obj2.y        = y - obj2.texture_height/2;
+				obj2.x        = x - obj2.texture_width/2 + overlayoffsetx;
+				obj2.y        = y - obj2.texture_height/2 + overlayoffsety;
 				obj2.width    = obj2.texture_width;
 				obj2.height   = obj2.texture_height;
 				obj2.rotation = obj.rotation;

```

**Comment by mickelson** [comment]
thanks for the patch! I've applied it

**Comment by joyrider3774** [comment]
No problem. 

I might still look into the video positioning itselve wrong in certain themes but yesterday i did not find the cause yet.
