### ISSUE TITLE
Hyperspin.nut artwork does not display correctly if position (x or y) is negative 

### ISSUE THREAD

**Issue by joyrider3774** [mickelson/attract#308]
Hi, 

i noticed something else today some hyperspin themes artwork contain negative values for the position like x or y being negative. I noticed attract can not display these artwork files correctly and positions them completely wrong. It seems attract doesn't handle negative x / y correctly at least not for flash swf files i have not tried yet with negative x y values for just artwork images.

I added this to my hyperspin.nut file after assigning obj.x and obj.y values to x & y from the xml and some themes that displayed incorrectly now seem to display better.
```
if (obj.x < 0)
    obj.x = 0;
			
if (obj.y < 0)
    obj.y = 0;
```

i have found a few themes that do this like the zookeep one for example i have placed it on my google drive ( https://drive.google.com/file/d/0B9GXk-wvZQGcNEZVMGtuMG9oNHM/view?usp=sharing )

Resetting the values to non zero seems to fix but it might not work for all themes that have (very) low negative numbers because the artwork would not be displayed in the same position. So don't know if it's a good fix might be better if attract can handle negative positions.

I'll verify if it's only with flash swf files or also with pictures but resetting to 0 might be a quick fix that work in some cases

edit: 
Same thing seems to happen with artwork that goes out of bounds, i mean which uses positions that go outside the width and hight of the layout. 
the theme for beast busters is an example ( https://drive.google.com/file/d/0B9GXk-wvZQGcU2tFR29mazJzcDg/view?usp=sharing )
here there is no quick fix that might work or at least havent figured out one

**Comment by joyrider3774** [comment]
I have been testing some more.  i have found some more themes that mis behaved
like: 
https://drive.google.com/file/d/0B9GXk-wvZQGcS0pxWV9uTndJakU/view?usp=sharing bbonk.zip
https://drive.google.com/file/d/0B9GXk-wvZQGcU2tFR29mazJzcDg/view?usp=sharing  bbusters.zip
https://drive.google.com/file/d/0B9GXk-wvZQGccThVZUVzem1IaEU/view?usp=sharing (bioncc.zip bionic command)
https://drive.google.com/file/d/0B9GXk-wvZQGcd04xaDRtV1p1djQ/view?usp=sharing (bwidow.zip black widow)


The code below is my current code in hyperspin.nut and seems to fix the problems with above themes but there are other themes that still don't work with the code below or now display extra parts but on wrong places due to wrong positioning. One of the birdie king (golf) themes had this problem. But the above ones are already fixed with below code. Will test some more tommorow

```
                        obj.x        = x - w/2;
			obj.y        = y - h/2;
			
			
			obj.width    = w;
			obj.height   = h;
			obj.rotation = r;
			
			//start fixes for wrong positions
			
			if (obj.x < 0)
				obj.x = 0;
			
			if (obj.width > fe.layout.width)
				obj.width = fe.layout.width;
			
			if (obj.x + obj.width >= fe.layout.width)
				obj.x = fe.layout.width - obj.width;
			
			if (obj.y < 0)
				obj.y = 0;
			
			if (obj.height > fe.layout.height)
				obj.height = fe.layout.height;
				
			if (obj.y + obj.height >= fe.layout.height)
				obj.y = fe.layout.height - obj.height;
				
			//end fixes for wrong positions

			if ( c.tag == "video" )
			{
				// Deal with video overlay
				//
				local af2
					= get_art_file( "video_overlay", hs_sys_dir, theme, match_map );

```

**Comment by joyrider3774** [comment]
it seems the fixes only need to be applied to flash swf files most of the themes i listed above have problems due to the flash swf files being positioned wrong, the images itselve don't seem to have a problem although did not test using hypertheme yet so changed the code a bit. I'll do a pull request if i don't find any other problems 
```

function ext( name )
{
	local s = split( name, "." );

	if ( s.len() <= 1 )
		return "";
	else
		return s[s.len()-1];
}
```

```
                        obj.x        = x - w/2;
			obj.y        = y - h/2;
			
			
			obj.width    = w;
			obj.height   = h;
			obj.rotation = r;
			
          		//fixes for wrong positions for SWF files
			if ( ext( obj.file_name ).tolower() == "swf")
			{
			
				if (obj.x < 0)
					obj.x = 0;
				
				if (obj.width > fe.layout.width)
					obj.width = fe.layout.width;
				
				if (obj.y < 0)
					obj.y = 0;
				
				if (obj.height > fe.layout.height)
					obj.height = fe.layout.height;

			}
			if ( c.tag == "video" )
			{
				// Deal with video overlay
				//
				local af2
					= get_art_file( "video_overlay", hs_sys_dir, theme, match_map );

```

**Comment by joyrider3774** [comment]
tested some more using hypertheme editor. normal images artwork don't seem to have a problem when using negative coordinates or having sizes bigger then the layout file. But flash file do have a problem if that happens. So it's indeed only needed for flash files. I'll test a few other themes and see if my code fixes it. I'm currently testing on windows to let me test faster but i'll test on the pi as well to be sure. If all is ok and it does not have an impact on themes that worked fine before i'll do a pull request

**Comment by mickelson** [comment]
sounds good, thanks

**Comment by joyrider3774** [comment]
@mickelson this is my current code
```
//fixes for wrong positions for SWF files
			if ( ext( obj.file_name ).tolower() == "swf")
			{				
				//beast busters - bombjack - gladiator
				if (x > fe.layout.width || y > fe.layout.height)
				{
					obj.y = 0;
					obj.x = 0;
				}
				
				//most others
				if (obj.width == fe.layout.width)
				{
					if (obj.x < 0)
						obj.x = 0;					
				}
				
				//most others
				if (obj.height == fe.layout.height)
				{
					if (obj.y < 0)
						obj.y = 0;
				}								
			}		
```


To show you some of the fixes i created a youtube video from attract version in windows. It first shows the themes i had found that have problems (not all of them as it's real pain going through 2000 game themes, many more themes have similar problems) and then the same themes later on in the video with the hyperspin.nut modifications applied.

https://www.youtube.com/watch?v=IQ6u6ypWuqk

as you can see i only fix swf files that 1024x768 as resolution (a whole res that hyperspin theme can be) because as far as i could see those are the one causing problems and smaller swf files positioned with negative files don't and still display ok with negative values. 

For three games i added this `if (x > fe.layout.width || y > fe.layout.height)` which might be dangerous but i did not see any themes that got broken due to using it but can't be sure. So my question is should i add a layout variable to enable the fixes so one is able to turn them on or off ? The thing is if there are any valid themes where that condition is true they might position wrong. Another reason might be that people started modifying the themes repositioning the swf artwork manually by changing the x & y values in theme.xml and it could have an impact on those themes. Also 1024x768 could never be postioned negative otherwise. Not sure if that's a good idea or not ?

If you don't think it's needed to add a layout option for it i do the pull request this evening otherwise i'll add the layout option first.

**Comment by Metalciaf** [comment]
sorry for necroposting 
but i have a problem with hyperspin.nut
with 

raspberry pi4
retropie 4.8

Attract-Mode v2.6.1 (Linux, SFML 2.4.2 +FontConfig +SWF +Curl)
avcodec 58.90.100 / avformat 58.44.100 / swscale 5.6.101 / avutil 56.49.100 / swresample 3.6.100

OpenGL 2.1 Mesa 19.3.2

    vendor : Broadcom
    renderer: V3D 4.2

i have all the SWF upside down like this 
https://drive.google.com/file/d/1N8qJ29z7cVKJhqLM3OJ7TxhELZO9kP0k/view?usp=share_link

there's a way to add a command line with rotation of the swf?  

thank you for the help?
