### ISSUE TITLE
StartNavigation event needed

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#311]
I have 2 animations that needs to be triggered only once when the joystick is moved and held and then the second animation must be triggered when the joystick is released. There is an event Transition.EndNavigation which I used, but I cannot find a way to trigger the first animation. Is there any way to do it in the current form or we need a new event StartNavigation to do that?

**Comment by mickelson** [comment]
You need to trigger your start animation whenever the Transition.ToNewSelection event is fired, but only if the Transition.EndNavigation event has been fired since the last time you triggered your start animation.

**Comment by oomek** [comment]
Thanks, it's so obvious now for me that I feel shame for even asking that question :)
