### ISSUE TITLE
Does Not like Multi level directories

### ISSUE THREAD

**Issue by sirk123au** [mickelson/attract#313]
Attract Mode does not work with the workdir or executable path with more than one directory level 
eg. e:\retroarch works but e:\newfe\retroarch does not. Crashes after loading rom but rom will load.

System is Windows 10

have not tried on any other os

**Comment by djrobx** [comment]
My emulators are two or three levels deep (e.g. C:\games\snes\snes9x ) and I run Windows 10.  I have not seen this issue.

**Comment by sirk123au** [comment]
just tried a new drive and config single level directory and still crashed on rom load dont know what is going on

**Comment by sirk123au** [comment]
Found the problem retroarch was closing the console and causing attractmode to terminate must be a retroarch bug only happen when i had a per core config set, weird to me a bit to figure it out.
