### ISSUE TITLE
(Feature request) Emulator config - Launch before, launch after, and hide window

### ISSUE THREAD

**Issue by djrobx** [mickelson/attract#314]
Moving to AttractMode from Mala, the only snag I ran into was configuring the emulator launching to work as it did before.   In Mala, I use a launch before and after to run U-Hid config scripts.   

You might ask, "Why not just run a batch file that does these things?"   Because if you also need to use the "exit hot key", Attract Mode kills the running app (probably cmd.exe) which won't close the emulator.   Even if that worked, it wouldn't run the "after" script which is important in my case.    

A second, "nice to have" is being able to configure the launch to open with a hidden window on Windows.  In C# this is done with:

process.StartInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;

Kega Fusion leaves a window open on the screen for a long time before switching to full screen without that.     Kega is unfortunately the only bit of non-open-source left on my cab so I can't fix it otherwise. 

Thanks for your consideration.  This front end is truly awesome.

**Comment by mickelson** [comment]
I see why this would be helpful in your situation.

as a workaround for now, you could create a plugin to run your before and after functions.  there is an old plugin included for ultrastiks, and it basically does everything you want and is not too complicated if you open it up in a text editor.

**Comment by djrobx** [comment]
Great suggestion, works very well!   Thanks!
