### ISSUE TITLE
(BUG) Animate module - Linear tween not linear

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#316]
I found in a hard way that there is a bug in linear tween causing it to behave nonlinear

You can find more details in the link below:
http://forum.attractmode.org/index.php?topic=1462.0

**Comment by oomek** [comment]
I found that a bug is related to "t" variable in animate.nut which is not linear. That's quite serious as this prevents us to build a smooth experience.

**Comment by mickelson** [comment]
@liquid8d can you look at this one if you get a chance?

**Comment by liquid8d** [comment]
I'm looking into this, but I still don't have a pinpoint on any issue as the 't' variable isn't supposed to be linear - the values that the linear function returns is what is supposed to be linear.

**Comment by oomek** [comment]
When you add to tick callback a change of coord of any object the tweens are more smooth, that ease in slope is gone. but you still get doubled frames, first on the beginning and the second around 7-10th frame. I hope this helps.

**Comment by liquid8d** [comment]
Can you give some example code of the issue, and what you are doing to 'change coords' to make your animation smooth?

I think the key thing we might not be on the same page about is that the animation module is time-based, not frame based. It does not ensure that each 'frame' of an animation is drawn - it takes a start time, an animation duration and then totals elapsed from each tick call. It uses that elapsed value and duration to adjust the properties values using penner equations.

It doesn't have control of how often tick is called, but it is possible the way the code is written currently that it inadvertently affects that. Or perhaps the way elapsed is determined, might be causing an issue. At any rate, I'm working on a new version, so if you have suggestions on improving performance, I am all ears :) I'm sure there may be better ways to get out quirks and improve performance, this is just the method I came up with to make animation work.

**Comment by oomek** [comment]
I'm not on my pc atm. But you can just add a simple text object and update its .msg on each tick in global tick callback function. This will foce tick function to be called once per frame and somehow it fixes the animations, well almost.

**Comment by oomek** [comment]
No longer an issue since https://github.com/mickelson/attract/commit/59a06a695e49b767c14c2f98a1bb5c2e6f306f14
