### ISSUE TITLE
compile on linux error: ‘class FeWindow’ has no member named ‘hasFocus’

### ISSUE THREAD

**Issue by rcampbel3** [mickelson/attract#318]
I build attract from source on Ubuntu 14.04 regularly. Yesterday, it compiled with no issues. Today, after a git pull, and a make clean, I get this:

src/fe_window.cpp: In function ‘void launch_callback(void*)’:
src/fe_window.cpp:248:13: error: ‘class FeWindow’ has no member named ‘hasFocus’
   if ( win->hasFocus() )

Hope that info helps!

**Comment by mickelson** [comment]
Thanks, it looks like hasFocus is only available in newer versions of SFML.  The compile should be fixed for you now
