### ISSUE TITLE
Atract Mode video Problems

### ISSUE THREAD

**Issue by danilop2k2** [mickelson/attract#323]
Attract Mode video Problems:

Rattydave's image 

some bugs with video snapshots, cutting or turning screen white/not playing entirely

found somewhere a solution is to tweak the video decoder,
but i only have the "software" option

**Comment by mickelson** [comment]
You'll need to talk to rattydave or whoever you got the image from for support.

This tracker is only for bugs and feature requests for the attractmode program.
