### ISSUE TITLE
Nested surfaces - "snap" update late by 1 frame

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#324]
When I use nested surfaces like so:

```
local test1 = fe.add_surface ( )
local test2 = test1.add_surface ( )
local test1snap = test1.add_artwork( "snap" )
local test2snap = test2.add_artwork( "snap" )
```

the update of a snap drawn on surface2 is late by one frame

**Comment by oomek** [comment]
`local test1 = fe.add_surface ( 400, 400 )
local test1bg = test1.add_text( "", 0, 0, 400, 400 )
local test1label = test1.add_text( "surface1", 200, 75, 200, 40 )
test1bg.set_bg_rgb( 100, 200, 0 )
local test1snap = test1.add_artwork( "snap", 0, 0, 200, 200 )
test1snap.video_flags = Vid.ImagesOnly

local test2 = test1.add_surface ( 400, 200 )
local test2bg = test2.add_text( "", 0, 0, 400, 200 )
local test2label = test2.add_text( "surface2", 200, 75, 200, 40 )
test2bg.set_bg_rgb( 200, 0, 100 )
local test2snap = test2.add_artwork( "snap", 0, 0, 200, 200 )
test2snap.video_flags = Vid.ImagesOnly

//force updating every frame
fe.add_ticks_callback( "tick" )
function tick( tick_time ) {
    test1.set_pos( 1000, 400 )
    test2.set_pos( 0, 200)
}`

**Comment by oomek** [comment]
When you comment the last section the surface1 will update when you press an arrow on the keyboard. the surface2 will update when you release the arrow key. I recorded it with tick enabled using the 400pfs camera and it clearly showing that surface2 is late by 1 frame.

**Comment by liquid8d** [comment]
I've run into this also:
[code]
local surface = fe.add_surface(200, 200);
surface.set_pos(150, 150);
local subsurface = surface.add_surface(200, 200);
local texture = subsurface.add_image("button.png", 0, 0, 200, 50);
[/code]

If you force a redraw as oomek mentioned - like resize the AM window, the subsurface image shows up.

This is with 2.3.0, not sure how far back that goes, but I thought previously I've used subsurfaces without issue.

**Comment by oomek** [comment]
To avoid any delay in drawing nested surfaces you have to have a proper order of drawables set in the layout file as I explained in the forum post:

http://forum.attractmode.org/index.php?topic=2286.0

This is not an issue, but rather the way how and when the surfaces' content is updated.
