### ISSUE TITLE
[BUG] object edges snap to pixels with subpixel positioning

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#326]
When I move an image with sub-pixel accuracy the content moves with subpixel filtering, but the edges of an object are snapping to pixels.
The same happens with text boxes

Run this code and see. It will jump in 1 pixel increments instead smoothly transitioning across the X axis.

```
local test = fe.add_text( "", 0, 0, 32, 1080)
test.set_bg_rgb( 200, 200, 200 )

fe.add_ticks_callback( "tick" )
function tick( tick_time ) {
    test.x += 0.01
}
```

**Comment by oomek** [comment]
There is a workaround for the static layout elements. You can add a 1 pixel transparent border inside a square png image and adjust the coordinates accordingly. Nothing can be done to the snaps as I really wouldn't like to edit the whole snaps directory.

**Comment by oomek** [comment]
Would you please take a look at this as this jerky scrolling at the end of exponential animations are driving me insane. Maybe it's just a matter of setting some rendering flags.

**Comment by oomek** [comment]
Call me crazy, but this issue is annoying me to the point that I'm about to add one pixel (almost) transparent border to all my snap files in Photoshop by using macros. Adding it totally transparent makes no difference, I've just checked.

**Comment by mickelson** [comment]
what are the fe.layout.width and fe.layout.height variables set to in the layout you are working with?
Does increasing them affect this?

**Comment by oomek** [comment]
My layout size matches the display resolution.

**Comment by oomek** [comment]
Mind you, the script above needs to be run in native resolution to avoid surface resampling

**Comment by oomek** [comment]
Run this script and you will see where I'm coming from

```
local test1 = fe.add_image( "square.png", fe.layout.width / 2 + 1, fe.layout.height /2, 30, 30)
local test2 = fe.add_image( "square-border.png", fe.layout.width / 2, fe.layout.height / 2 + 32, 32, 32)

fe.add_ticks_callback( "tick" )
function tick( tick_time ) {
    test1.x += 0.025
    test2.x += 0.025
}
```
The squares are here:

[https://mega.nz/#F!jodhlBQL!pVLQ3WVf4HiCpPFLjC1kyQ](https://mega.nz/#F!jodhlBQL!pVLQ3WVf4HiCpPFLjC1kyQ)

**Comment by oomek** [comment]
Now I know it’s the nature of DirectX to draw objects this way. It can be fixed by simply enabling anti aliasing.
