### ISSUE TITLE
[BUG] [SOLVED] Window (no border) totally broken

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#327]
Windowed borderless mode is scaling 1920x1080 screen to 1918x1078 and adding a white border on top and left side of the screen. Scaling makes images very blurry. What's more, depending which mode was selected before the taskbar is sometimes showing on top. for example:

Fill Screen -> Windowed (no border) = size ok, but taskbar on top
Full Screen -> Windowed (no border) = scaled to 1918x1078, white lines on top and left.

To be honest I'm a bit tired of finding a new bug each day and the silence on GitHub regarding my reports is not heping either.

**Comment by oomek** [comment]
Oh...... wait.......the latest Nightly from today fixed the issue :) I did not check it before writing that report. Thank you very much, all the window modes are working perfectly fine now on Winodows 10.

**Comment by mickelson** [comment]
wow, well thanks for the report.
