### ISSUE TITLE
[BUG] Snap video playing takes 100% CPU

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#328]
Playing even a small video like 64x48 uses 100% CPU (1 core)
This drasticaly affect the fluidity of the interface. Would you be able to take a look if it can be fixed please?

[https://s30.postimg.org/ri349qq75/AM_video_CPU.png](https://s30.postimg.org/ri349qq75/AM_video_CPU.png)

**Comment by oomek** [comment]
I have narrowed it down to a specific codec, because half of my video snaps are draining my 2500K out of juice

low CPU
Video: MPEG4 Video (H264) 320x240 30fps 526kbps [V: VideoHandler (h264 main L1.3, yuv420p, 320x240, 526 kb/s)]
Audio: AAC 48000Hz stereo 54kbps [A: SoundHandler (aac lc, 48000 Hz, stereo, 54 kb/s)]

high CPU
Video: MPEG4 Video (H264) 320x240 59.94fps 200kbps [V: h264 high L2.1, yuv420p, 320x240, 200 kb/s]
Audio: AAC 48000Hz stereo 35kbps [A: SoundHandler (aac lc, 48000 Hz, stereo, 35 kb/s)]

**Comment by oomek** [comment]
I took a handbrake and re-encoded 1 sample video with all the H.264 levels. Same results. It seems like when video does not have a "VideoHandler" (whatever that is) it drains the CPU. Do you know what that Video Handler is?

**Comment by oomek** [comment]
It seems like AM is allergic to the standard mp4 container as reencoding my mp4s to avi solved the CPU drainage

**Comment by mickelson** [comment]
can you provide a sample file?

**Comment by oomek** [comment]
Sure
[https://mega.nz/#F!jodhlBQL!pVLQ3WVf4HiCpPFLjC1kyQ](https://mega.nz/#F!jodhlBQL!pVLQ3WVf4HiCpPFLjC1kyQ)

**Comment by mickelson** [comment]
hmmm... videos play fine for me

please post the output when you run 'attract --version'

**Comment by oomek** [comment]
```
Attract-Mode v2.2.1-34 (Windows, SFML 2.3 +SWF)

Using FFmpeg for Audio and Video.
avcodec 57.64.101 / avformat 57.56.100 / swscale 4.2.100 / swresample 2.3.100

Shaders are available.
```

You did rename the mp4 files accordingly, didn't you ?

**Comment by oomek** [comment]
Nevermind, AM loads the files even with double extensions. the reason for renaming them like that was that baddudes.avi is crashing some windows process as embedding mp4 into the avi container is considered as a hack. Just make sure you have only one of those files at once in your video snaps folder

**Comment by oomek** [comment]
Check your CPU usage while slowny scrolling through videos, maybe you are experiencing the same issues as me and AM is choking.

**Comment by grigoletto77** [comment]
After the update, AM is much more stable. Only a few videos (snaps) switch to the grey color (but keep playing sound - No more freezing). As for the CPU, I get near 60% on 2 cores and a bit (like 10%) on the other 2 cores (its a PI 3 quad core). Temp gets high as 84 degrees sometimes. I will kill the overclocking to check if it is related to temperature increase or not. get back later on. regards.

**Comment by estefan3112** [comment]
Great - and one workaround: After a re-encode of the Snap Videos in Handbrake with the option "Web Optimized", they run much smoother in Attract Mode. This immediately helps.

**Comment by grigoletto77** [comment]
I removed the overclock, temperature drops to a bit higher than 75%, core usage almost similar as before. Speed in AM is the same, meaning the overclocking only increase temperature apparently, no gain on the GUI. I guess the big difference was to make the update to this newer version (apparently updated 16 hours ago). I will try the re-encoding  as well. thanks for the tip. Will comment more tomorrow. Take care and thank you!

**Comment by grigoletto77** [comment]
System is 100% stable I would say. I guess the trick is really to have all attract mode updated (from mickelson), overclocking should be monitored and videos (snaps) double checked on Handbreak. I do have one question thought, about Handbrake... is there a way I can do batch processing with the new video files having the same name untouched on a different folder? everytime I do it adds a T1 and C1. estefan3112, any tips on that? otherwise it will take me years to correct names manually on so many files. Thank you again for all the support folks! Cheers!

**Comment by oomek** [comment]
What I did was to encapsulate all the mp4s in avi container(no reencoding necessary). That stopped all the CPU overloading for good. Here is the batch I used for ffmpeg:
```
for %%a in ("mp4\*.mp4") do ffmpeg -i "%%a" -map 0:0 -vcodec copy -map 0:1 -acodec copy -f avi "avi\%%~na.mp4"
pause
```

**Comment by grigoletto77** [comment]
Thanks oomek!

**Comment by estefan3112** [comment]
I am on a Mac and installed HandbrakeCLI via Homebrew. Then I modified this script I found in the net and saved it as HandbrakeCLI.sh:

#!/bin/sh

# This script converts any kind of video the HandBrake CLI can handle
# into a 1000 kbit MPEG4 video and shrinks it down to a max width of 640 px.
#
# Usage:
# Running the script without any parameters just uses *all* files in the
# current directory and converts them, so make sure you only have video files
# in the directory you're in.
#
# You can specify an input and output directory if you want:
# 'script <INPUT> <OUTPUT>'
#
# Done by: https://gist.github.com/halbtuerke/640051


if [ ! -n "$1" ]; then
  IN='/Users/stefan/Desktop/testin'
  OUT='/Users/stefan/Desktop/testout'
else
  IN=$1
  OUT=$2
fi

cd "$IN"
for InputItem in *;do
  /usr/local/bin/HandBrakeCLI -i "$InputItem" -o "$OUT/${InputItem}" -O  -q 22 -a 1 -E faac -B 160 -6 dpl2 -R Auto -D 0.0 -X 320
done
