### ISSUE TITLE
[BUG] add_surface drains CPU on idle

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#329]
Gues what ... I found another bug :)
When using surfaces the CPU does not go into idle state when no transitions are occuring. With one surface CPU usage sits at around 15-20% on one core.
In the example below screen is filled with snaps, each has its own surface to emphasize the problem. It takes 100% of CPU on one core even when there is no transitions, funny thing it goes down a little when you start scrolling through snaps.

```
local surface = []
local snap = []
local tiles_x = 8
local tiles_y = 6
for( local x = 0; x < fe.layout.width; x += fe.layout.width / tiles_x )
    for( local y = 0; y < fe.layout.width; y += fe.layout.height / tiles_y )
    {
        local surf = fe.add_surface( fe.layout.width / tiles_x, fe.layout.height / tiles_y )
        surf.set_pos( x, y )
        local obj =  surf.add_artwork ( "snap" ,0 , 0, fe.layout.width / tiles_x, fe.layout.height / tiles_y )
        obj.video_flags = Vid.ImagesOnly
        obj.preserve_aspect_ratio = false
        surface.push( surf )
        snap.push( obj )
    }
```

Another example does not use surfaces and the idle CPU usage as expected sits at around 0.5%

```
local snap = []
local tiles_x = 8
local tiles_y = 6
for( local x = 0; x < fe.layout.width; x += fe.layout.width / tiles_x )
    for( local y = 0; y < fe.layout.width; y += fe.layout.height / tiles_y )
    {
        local obj =  fe.add_artwork ( "snap" ,x , y, fe.layout.width / tiles_x, fe.layout.height / tiles_y )
        obj.video_flags = Vid.ImagesOnly
        obj.preserve_aspect_ratio = false
        snap.push( obj )
    }
```

So please tell me if it's a limitation of the rendering pipeline or a bug. I need to know if it's the former, as I'will try to edit my code to get rid of surfaces.

**Comment by mickelson** [comment]
ok thanks, this one should be fixed now

**Comment by oomek** [comment]
I't is, indeed. Thank you for your awesome work.
