### ISSUE TITLE
[BUG] Text alignment does not work [SOLUTION]

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#330]
The picture below shows the relation between the text box and the text placement. With Align.Left the text should stick to the very first pixel of the box. It should also be aligned verticaly. The gap and vertical alignment is even worse with fonts other than the default one.

[https://s3.postimg.org/5paot5kjn/attract_2017_03_12_14_38_06_515.png](https://s3.postimg.org/5paot5kjn/attract_2017_03_12_14_38_06_515.png)

**Comment by oomek** [comment]
Dude, I'm tearing my hair out here! I've partialy managed to fix the vertical alignment by editing the font itself. I just increased the HHead Ascent in FontForge and the text is centered on the Y axis, but now the kerning is all wrong and the font renderer does not snap to pixels so I have blurry vertical edges on half of the font sizes.

Your input regarding that case would be much appreciated as I do not know if it's even possible to do what I'm trying to achieve here.

**Comment by oomek** [comment]
Ok, I've got a fix for you for the blurred fonts in the Y axis

in tp.cpp change the line 266
```
		textPos.y = rectPos.y
				+ spacing * i
				+ ( rectSize.height - ( spacing * m_texts.size() )) / 2;
```
to:
```
#include <cmath>
(...)
		textPos.y = rectPos.y
				+ floorf( spacing * i
				+ ( rectSize.height - ( spacing * m_texts.size() )) / 2);
```

Also I do not quite understand why you have decided to add that half character space for the text position inside the textbox

```
		case Left:
			textPos.x = rectPos.x + spacing/2;
			break;
```
Furthermore it is very difficult to align vertically two boxes with diffrent font sizes. When you are using transparent textbox backgrounds this spacing does not make any sense, does it?

It could be nice if you added a property for a Text class like "nomargin" or something which would do the direct X position snapping to text box edge like so:

```
		switch ( m_align )
		{
		case Left:
			textPos.x = rectPos.x;
			break;

		case Centre:
			textPos.x = rectPos.x + ( (rectSize.width - textSize.width) / 2 );
			break;

		case Right:
			textPos.x = rectPos.x + rectSize.width - textSize.width;
			break;
		}
```

I'm now trying to find how you calculate the char's vertical size so I could snap the text to the textbox also in Y axis. This way your textbox Y size will match the char size and that would make the "nomargin" property even more useful. Just by simply setting width and height of a text box you would know the text size in pixels, wayyy more user friendly while designing themes, no more compensating, everything pixel perfect.

Can't wait to hear back from you.

**Comment by mickelson** [comment]
Hi,

I assume the pull request you sent a while back fixes this (thanks!) so I'm going to close this issue now.

To answer your question about why the text code was done the way it is: I have no idea anymore! it was a;; done early on and without a real good idea of what I was doing.  I suspect the margin code was added to make things look good in config mode, but I'm not sure.
