### ISSUE TITLE
[BUG] Pressing a launch game button again before the previous sound finishes is triggering that sound again.

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#333]
It's a 2 part bug.

When you launch a game and have a sound applied to the ToGame event and press the button continously the sound is played again and again as long as you keep pressing that button before the previuos sound finishes playing.

This sometimes triggers another bug which causes the resolution not coming back to the proper layout resolution when you exit a game so the frontent is stretched out when a game was launched in a smaller resolution. I'm not sure though when the button needs to be pressed again to trigger it. I think it's just after the sound stops playing. I get that on 1/10 launches when I repeatedly press the launch game button.

**Comment by oomek** [comment]
Ok, I know when you have to press the button for the second time to trigger the resolution change bug.
Press once, and then for the second time press it right after the sound finishes, but before the screen goes black.

**Comment by oomek** [comment]
Bear in mind that ResFix plugin do not fix that.

**Comment by mickelson** [comment]
Fixed game sound being repeated.  Unable to reproduce screen resolution change

**Comment by oomek** [comment]
Nightlies server is down recently 90% of the time. I can't download. 502 Bad Gateway
