### ISSUE TITLE
Fail to compile when attract src directory is a subdirectory of another git enabled project 

### ISSUE THREAD

**Issue by TiBeN** [mickelson/attract#334]
Hi, 
I noticed an issue with the 2.2.1 *.tar.gz src tarball version of attract mode. This version has no `.git` directory on it, which is normal because it is not a `git clone`. The issue is when this archive is extracted into a sub-directory of another git project. 
I think there is a "clash" because of theses Makefile shell commands: 

```
VER_TAG   := $(shell git describe --tags --abbrev=0 2>/dev/null || echo $(FE_VERSION))
VER_COUNT := $(shell git rev-list --count ${VER_TAG}..HEAD 2>/dev/null || echo 0)
```

Theses commands return informations about the root git project which has nothing to do with attract mode. Seems parents directories are scanned recursivelly leaf to root in search of ".git" directory.

It results in compilation errors like that: 

```
src/fe_vm.cpp: In member function ‘virtual bool FeVM::on_new_layout()’:
<command-line>:0:16: error: ‘yakkety_Ubuntu0’ was not declared in this scope
src/fe_vm.cpp:496:32: note: in expansion of macro ‘FE_VERSION_NUM’
   .Const( _SC("FeVersionNum"), FE_VERSION_NUM)
                                ^~~~~~~~~~~~~~
src/fe_vm.cpp: In constructor ‘FeConfigVM::FeConfigVM(const FeScriptConfigurable&, const string&, const string&, bool)’:
<command-line>:0:16: error: ‘yakkety_Ubuntu0’ was not declared in this scope
src/fe_vm.cpp:1407:33: note: in expansion of macro ‘FE_VERSION_NUM’
    .Const( _SC("FeVersionNum"), FE_VERSION_NUM)
                                 ^~~~~~~~~~~~~~
```

I recognize a part of tags of my parent project: `yakkety_Ubuntu0`.

This is really no big deal but i think it was worth to let you know about this issue.

Host OS: Ubuntu 16.10 Yakkety

**Comment by mickelson** [comment]
Should be fixed now. thanks
