### ISSUE TITLE
(Feature Request) Support for RatRefresh?

### ISSUE THREAD

**Issue by mgerety** [mickelson/attract#335]
A user over at BYOAC: Rataplan626 has developed a tool that allows setting custom refresh rates dynamically for MAME games to improve the experience on LCD montiors/tvs.  The solution prevents jaggies / screen tearing and is really amazing.

see here: http://forum.arcadecontrols.com/index.php?topic=152919.40

The issue is it resets the video driver when setting custom resolutions, so after exiting a game, most FEs crash, I'm guessing because of invalid device handles.  

Would it be possible to implement support for this tool by implementing some kind of graceful recovery from a driver reset while the FE is suspended during MAME launch?

**Comment by mickelson** [comment]
Have you tried using the "ResFix" plugin to see if enabling that allows attract-mode to work with ratrefresh?

**Comment by Rataplan626** [comment]
Hi, I think you're a bit soon to request this. RatRefresh is still beta on all fronts. While native support from (any) FE would be good, I'd first like to see if I can work around disabling and re-enabling the videodriver. So far I need this for it to pick up the custom displaytimings (just as CRU does). I'm not into DirectX or video-API's or the like of that, but as soon as you stop your display driver, I can imagine all applications that use anything but standard GDI calls (correct me if I'm wrong) to fail, as the application will lose its DirectX handle. ResFix won't do anything about that.

However, both Intel and NVidia have support for adding custom resolutions and refreshrates without resetting the display driver. While that may be driver specific, I'm still trying to get things to work universally without resetting drivers. I don't have much spare time though lately so it takes a bit longer than I'd like.

Of course, in time I agree that everyone should use RatRefresh ;)
