### ISSUE TITLE
Nightly Builds - 502 Bad Gateway

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#336]
I know it's not related to the source code, but I do not get any answer on the forum.  For the last several weeks I'm unable to access the recent nightly builds, I get 502 Bad Gateway all the time.

**Comment by mickelson** [comment]
I don't have any control over the nightly build.  it was h0tw1r3 that set that up

**Comment by oomek** [comment]
Oh, I see, I thought it's yours. Would you please at least update the wiki with some more details of how to cross compile AM for windows? I followed the guide, but I failed miserably on Ubuntu. I only succeeded with native compile, but without any dependencies attached.

**Comment by oomek** [comment]
I got it working. I downloaded binaries of MXE instead of compiling it.
