### ISSUE TITLE
Attract Mode crashes when controller is disconnected

### ISSUE THREAD

**Issue by SausageDog** [mickelson/attract#338]
I'm using Attract Mode on Windows 10 64 bit and using a wireless DualShock 4 controller with SCP Toolkit driver to expose the controller as an XInput device. 
https://github.com/nefarius/ScpToolkit

When the controller is idle for a long enough time, SCP Toolkit disconnects the controller from Windows (so the device is no longer visible in the Windows Game Controllers window) and this causes Attract Mode to crash.

**Comment by mickelson** [comment]
I suspect the issue here is related to this one in SFML: https://github.com/SFML/SFML/issues/1251
