### ISSUE TITLE
[BUG] screen freeze and sound looped after waking up PC

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#340]
When I execute the following command from the script:

`fe.plugin_command_bg( "rundll32.exe", @"powrprof.dll,SetSuspendState 0,1,0" )`

to put my PC into sleep mode and then wake it up with any key not bound to any action the AttractMode freezes and sound repeats in short loop until I press the up or down arrow.

Furthermore when I use a key for example the one for displaying favourites AM opens the favourites. In my opinion it should ignore the first keystroke which has been used to wake the PC from sleep.

**Comment by oomek** [comment]
Same happens even If I press the power button on my PC to enter sleep and then press a key on the keyboard. Movies are frozen, sound plays looped.

**Comment by oomek** [comment]
I found a workaround to this: I press a key on the keyboard wake up PC whicn is bound as custom1 then in the on)signal() function I check for that key and call wake() which just does that:
```
function wake() {
	if (sleep_state == true ) {
		sleep_state = false
		fe.signal( "reload" )
	}
}
```

**Comment by tomekpiatek** [comment]
I have this problem on my MacMini running macOS 10.12 (Sierra). I have any mac set up to go to sleep after an hour of inactivity. When I wake the computer up by pressing any of the keys on my control panel Attract Mode front end is frozen and unresponsive. All videos are frozen. Trying to select games works but with a lag say about 40 seconds or longer sometimes. 

I'm running AM 2.2.0 downloaded from AM site.

**Comment by oomek** [comment]
It’s been 9 months since I discovered this bug and it’s still unresolved in the recent release. I wouldn’t be nagging if the fix I proposed worked in my latest theme. Unfortunately it’s worse. The whole AM freezes after resuming from sleep until I repeatedly press alt+tab for a few seconds.

**Comment by oomek** [comment]
Fixed in https://github.com/mickelson/attract/commit/2ccc9597a3eb370e4fe31f249704f9ff8675f7a1
