### ISSUE TITLE
same zorder drawn in order of creation?

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#353]
I just started implementing zorder for the layout designer I'm creating and I noticed this:

```
local bg = fe.add_image("pixel.png", 0, 0, 300, 40)
bg.zorder = 0
local text = fe.add_text("[Title]", 20, 20, 300, 20)
text.set_rgb(200, 0, 0)
text.zorder = 0
```

This ends up putting the text behind the bg image. If objects are set at the same zorder, shouldn't they draw in the order they were created? However, it appears it's based on which zorder is specified first.. doing this fixes it:
```
text.zorder = 0
bg.zorder = 0
```
If you don't specify the zorders, they of course draw in the order they were created... this is in 2.2.1

**Comment by mickelson** [comment]
hey there, that's great that you are doing a layout designer! I look forward to checking it out.

zorder is literally just exposing an object's order in the draw list.  if you set an object's zorder to 0, the object that was previously 0 gets bumped to 1, etc. down the line.  so in your example, bg's zorder is getting changed to 1 when you set text.zorder to 0.

**Comment by liquid8d** [comment]
Yeah, I guess that makes sense. I was thinking more along the lines of multiple objects at the same "zindex", and first created wins. That's probably not a real priority since you do still have control and also have the ability to put multiple objects on different surfaces too :)

Check out the designer! I just uploaded the code here:
https://github.com/liquid8d/am-builder/

And I have an online version running here:
http://goodiesfor.me/attractmode/builder

Still fairly early on, but making good progress.
