### ISSUE TITLE
MAME not working with AM

### ISSUE THREAD

**Issue by hassenpheffer** [mickelson/attract#355]
This started with MAMEUI64 a few versions ago.

I run AM and I choose a game. It goes to desktop and creates a ghost window and opens MAME but nothing runs.

I can use the desktop and MAME fine but AM is frozen.  Task manager to close.

I checked my MAME and I check my antivirus. Nothing.

Windows 7 Pro x64

Any help would be greatly appreciated.

**Comment by mickelson** [comment]
HI I don't have any ideas. You could try asking on the forum if this is still an issue for you (I see this is getting to be pretty old now)
