### ISSUE TITLE
after launching taito type x games attract mode is out of my screen (resolution over my screen)

### ISSUE THREAD

**Issue by redoxoder** [mickelson/attract#356]
hello 
after launching and quit taito type x game or nesicalive 
the resolution of attract mode is over my screen 
(i think i get the game résolution )
please help me

http://hpics.li/32e6f87
http://hpics.li/028736c

thanks

**Comment by estivalet** [comment]
Same problem here when setting up Future Pinball. The desktop resolution downs to 800x600

**Comment by redoxoder** [comment]
found the solution 
i  activated the plugin resfix 
and now all works fine 

no one  have a last nightly build compiled ? 

thanks
