### ISSUE TITLE
Compilation error on Amlogic S905 using Libreelec

### ISSUE THREAD

**Issue by shantigilbert** [mickelson/attract#358]
I am trying to compile Attract Mode for an Amlogic S905, I got SFML to compile after a lot of searching, but  now Attract won't compile.

First it gave me this error:

`src/fe_vm.cpp: In member function 'virtual bool FeVM::on_new_layout()':
<command-line>:0:16: error: 'Sx05RE_150' was not declared in this scope
src/fe_vm.cpp:496:32: note: in expansion of macro 'FE_VERSION_NUM'
   .Const( _SC("FeVersionNum"), FE_VERSION_NUM)
                                ^
src/fe_vm.cpp: In constructor 'FeConfigVM::FeConfigVM(const FeScriptConfigurable&, const string&, const string&, bool)':
<command-line>:0:16: error: 'Sx05RE_150' was not declared in this scope
src/fe_vm.cpp:1411:33: note: in expansion of macro 'FE_VERSION_NUM'
    .Const( _SC("FeVersionNum"), FE_VERSION_NUM)
`  

For some reason it was picking up the name of my LibreElec "distro" so I made a patch to replace FE_VERSION_NUM with just a number 1

`FE_FLAGS += -DFE_VERSION_D='"$(VER_TAG)"' -DFE_VERSION_NUM=1`

But after that this is the error that I am stuck at:

`<built-in>: note: this is the location of the previous definition
Compiling obj/sqstdlib/sqstdblob.o...
In file included from /home/sg/sx05re/Kszaq/build.Sx05RE-S905.arm-1.6/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/libavutil/samplefmt.h:24:0,
                 from /home/sg/sx05re/Kszaq/build.Sx05RE-S905.arm-1.6/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/libavcodec/avcodec.h:31,
                 from src/media.cpp:30:
/home/sg/sx05re/Kszaq/build.Sx05RE-S905.arm-1.6/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/libavutil/avutil.h: In function 'void* av_x_if_null(const void*, const void*)':
/home/sg/sx05re/Kszaq/build.Sx05RE-S905.arm-1.6/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/libavutil/avutil.h:302:40: error: cast from 'const void*' to 'intptr_t {aka int}' loses precision [-fpermissive]
     return (void *)(intptr_t)(p ? p : x);
`

Can anyone shed a light as to why this is happening or a way to fix it ?

I am cross-compiling from Ubuntu 16.04 64bits 

Thank you!

**Comment by mickelson** [comment]
sorry I have no idea and see this is getting pretty stale. I'm going to close the issue
