### ISSUE TITLE
error executing command

### ISSUE THREAD

**Issue by estivalet** [mickelson/attract#359]
I have the following emulator.cfg file:

[code]
executable           "C:\emulators\Entex Electronic Baseball\mess.exe"
args                 -rompath "C:\emulators\Entex Electronic Baseball\roms" [name].zip
rompath              C:\emulators\Entex Electronic Baseball\roms
romext               .zip
artwork    snap            C:\emulators\Entex Electronic Baseball\roms\video
artwork    wheel           C:\emulators\Entex Electronic Baseball\roms\wheel
[/code]

And the following error happens:

*** Running: "C:\emulators\Entex Electronic Baseball\mess.exe" -rompath "C:\emulators\Entex Electronic Baseball\roms" ebball.zip
Error executing command: '"C:\emulators\Entex Electronic Baseball\mess.exe" -rompath "C:\emulators\Entex Electronic Baseball\roms" ebball.zip'

But if I open a new dos window and execute "C:\emulators\Entex Electronic Baseball\mess.exe" -rompath "C:\emulators\Entex Electronic Baseball\roms" ebball.zip" it runs ok

is there a log somewhere to understand what is going on? I don't see any error since the command generated is ok

**Comment by mickelson** [comment]
'attract --loglevel debug' from the command line will get you a full debug log of what is going on.  Sorry I don't have any ideas, try asking on the forum if this is still an issue for you.  I'm going to close this issue now
