### ISSUE TITLE
is it possible to create a 3 level menu?

### ISSUE THREAD

**Issue by estivalet** [mickelson/attract#368]
Example Consoles -> Mega Drive -> games?

in attract.cfg I did:

display	Consoles
	layout               unified_hursty
	romlist              Consoles
	in_cycle             yes
	in_menu              yes
	filter               All
	filter               Favourites
		rule                 Favourite equals 1

In Consoles.txt romlist:

Sega Master System;Sega Master System;@;;;;;;;;;0;;;;;
Sega Mega Drive;Sega Mega Drive;@;;;;;;;;;0;;;;;

But when I'm in the games displays of Master System when I hit ESC it returns back to the main menu and not to the consoles menus.

**Comment by iameddysmith** [comment]
This has been resolved. Plugin available. Check forum under themes.

**Comment by estivalet** [comment]
ok thanks, I've figured it out! It's really cool feature! Thanks!
