### ISSUE TITLE
example for multimon plugin

### ISSUE THREAD

**Issue by estivalet** [mickelson/attract#370]
How do I set up multimon plugin for marquee display? Ok, I put yes in the config but then what? Is there a WIKI or something to read about it? thanks

**Comment by mickelson** [comment]
The config options for the plugin only show up if the frontend detects multiple monitors on your system.
Make sure "Enable Multiple Monitors" is set to yes in Config->General
Multimonitor support in attract-mode is a little flakey unfortunately, and has only been implemented for windows and linux X11-based systems.

I'm not aware of any wiki pages about multi monitor support. there might be something on the forum.   Please feel free to add to the wiki with any info you think is helpful, it would be greatly appreciated
