### ISSUE TITLE
(Feature Request) Change Display on Joystick Input

### ISSUE THREAD

**Issue by PConn5** [mickelson/attract#372]
What I was looking for is a way to change to a specific emulator display based on device input. Basically if you have a dedicated controller to an emulator it could be configured such that any input on this controller will automatically jump to that emulators display.

Been looking through the codebase and the plugin setup. This seems like something that can possibly be done in a plugin but not sure how the joystick numbers are handled so that it can be stored as a user configurable parameter. I need to be able to detect which device sent the signal to jump to a display based on that.

**Comment by mickelson** [comment]
Hi there, good suggestion and this is implemented now.  There will now be a plugin called "SpecificDisplay" that you can configure to show a specific display when custom user inputs (such as all the inputs from your device) are recieved
