### ISSUE TITLE
Exiting MAME Game sometimes exits to black screen

### ISSUE THREAD

**Issue by steveearle86** [mickelson/attract#374]
I have the latest version of Attract Mode and running it with MAME 173. Sometimes when I exit a MAME game, the screen is blank. I can press CTRL / ALT / DEL  and then cancel the menu and that brings Attract Mode back up. I can't really work out  a pattern of when the black screen happens, it isn't specific to a single game and it is not every time, although fairly frequent.

I am running Windows 7 64-bit

**Comment by mickelson** [comment]
This seems to be a problem for a number of people that I haven't been able to figure out.
What I understand is:
- it has to do with window focus
- usually when a window is closed (i.e. mame), windows returns focus to the previous window that had focus (i.e. attract mode).  Something is intervening in your setup in these instances to mess this up.

Any further info that could help describe what is triggering this would help in tracking this bug down. thanks

**Comment by steveearle86** [comment]
Hi,
Unfortunately I've had to use a different front end now as this issue was
too frequent so can't do any more testing.

However, the only other relevant information I can give is that I was
booting directly into Attract Mode (IE no windows desktop) this issue
seemed to happen when opening a game too soon after startup.

Also I tried different versions of MAME and had minimal services running. I
also updated graphics drivers.
All the above made seemingly little impact
Steve

On Oct 15, 2017 19:08, "Andrew Mickelson" <notifications@github.com> wrote:

This seems to be a problem for a number of people that I haven't been able
to figure out.
What I understand is:

   - it has to do with window focus
   - usually when a window is closed (i.e. mame), windows returns focus to
   the previous window that had focus (i.e. attract mode). Something is
   intervening in your setup in these instances to mess this up.

Any further info that could help describe what is triggering this would
help in tracking this bug down. thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mickelson/attract/issues/374#issuecomment-336729775>,
or mute the thread

**Comment by jimbowley** [comment]
I have the same problem. It occurs every time (5 tries so far). 

It's a brand new windows7 64bit install on a Dell optiplex 760  E5300.  I'm about to update the chipset  drivers to see if that helps.

this AM setup was working perfectly on XP 32 bit. 

If there is anything I can test to add info, let me know.

**Comment by jimbowley** [comment]
Fresh win7 64bit install. This time on a Dell optiplex 3010 i3 with Intel Integrated HD graphics. All drivers up to date.  

Same problem :(

I'm running the simplest AM I can (no video or effects or screensaver).

Any ideas anyone?

**Comment by jimbowley** [comment]
I've got mine working :) and found something else.

Looks like it was self inflicted, I turned something off when I was simplifying win7. Possibly the desktop windows manager.   When I tried to turn aero back on there was a problem, win7 diagnosed and fixed it, and that fixed AttractMode.

Playing around I find this:

With win7 aero theme:  if I quit a game less than 8s after selecting it, I get a black screen for the remainder of the 8s, and then a functioning games list.

With win7 basic theme:  if I quit a game less than 8s after selecting it, I get a non-functioning games list for the remainder of the 8s, and then the keys start working again.

**Comment by popoklo** [comment]
I did also some tests:
2 PCs with Windows 10 latest build and AM 2.3:
1. with integrated graphics chip on mainboard: HD Radeon 4290
2. with dedicated Geforce

on 1.: 
---black screen problem: black screen when launching MAME via AM, i have to press ALT-TAB and click or click mouse to get MAME focus // Exit MAME to AM black screen again. also have to ALT-TAB
--- the black screen from AM to MAME does not appear when AM is in windowed mode. but also in Windowed mode, black screen appears from MAME to AM back.
--- the heavy part: i even cant set focus to AM or MAME via AUTOHOTKEY(it looks if a Window of AM exists, if so, then it focuses that window). very strange, because manual ALT-TAB works

on 2.: no problem

my thought is: a difference between integrated gfx vs dedicated? could also be a problem of the pour drivers of an integrated gfx. dont know.

**Comment by estefan3112** [comment]
I suddenly encounter this bug in MacOS with the newest binary of Attract Mode 2.5.0. No issues before that, now suddenly black screen when exiting MAME with the Esc key, in all three modes (Window, Window fill and Fullscreen). Only Alt+tab and Force Quit Attract Mode works. I also cleaned up my .attract directory and started from scratch, no avail.

When I launch Attract Mode from the Terminal, it just tells me after launching MAME:
***** Initializing display: 'Arcade'
 - Loaded master romlist 'Arcade' in 223 ms (34676 entries kept, 0 discarded)
 - Constructed 2 filters in 3 ms (69352 comparisons)
 - Loaded layout: ../config/layouts/Attrac-Man/ (layout.nut)
 ! Unexpectedly lost focus to: Unknown**

This is a very unfortunate bug.
If I can help, please tell me.
Many thanks, Stefan

**Comment by estefan3112** [comment]
This change in the Emulator Settings of MAME resolved everything:
nb_mode_wait         1
In the Settings Menu, it is called "Non-Blocking Wait Mode" with a 0 value as default.
After switching this to 1, MAME cleanly exits for me into Attract Mode.
No ResFix plugin required. Looks very promising to me her under MacOS.

**Comment by oomek** [comment]
My proposed changes to window focus management should eliminate all the possible causes of black screen on launch/exit https://github.com/mickelson/attract/pull/525

**Comment by mickelson** [comment]
closing as I believe the various MS-Windows focus issues have been resolved.
