### ISSUE TITLE
Game info text [Overview] causes pi to struggle

### ISSUE THREAD

**Issue by calle81** [mickelson/attract#377]
Hi,

Adding game info text like below causes performance issues on a pi when scrolling through a wheel. I was hoping that adding a transition state would solve the problem but it seems transitions and text don't work together. If you have any ideas pleas let me know.

local gtext = fe.add_text("[Overview]", flx*0.73, fly*0.25, flw*0.25, flh*0.45 );
gtext.set_rgb( 255, 255, 255 );
gtext.align = Align.Left;
gtext.charsize = 20;
gtext.rotation = 0;
gtext.word_wrap = true;
gtext.font = "MyriadPro-Bold.otf"
gtext.trigger = Transition.EndNavigation;

**Comment by calle81** [comment]
Same thing with the pan and scan module. This module doesn't seem to take the bgart.trigger = Transition.EndNavigation; option into consideration. When used on a pi this causes navigation performance issues because it loads the flyer for each game when moving through the wheel.

local bgart = PanAndScanArt( "flyer", 0, 0, flw, flh);
bgart.preserve_aspect_ratio = false;
bgart.set_fit_or_fill("fill");
bgart.set_anchor(::Anchor.Center);
bgart.set_zoom(4.5, 0.00008);
bgart.set_animate(::AnimateType.Bounce, 0.50, 0.50)
bgart.set_randomize_on_transition(true);
bgart.set_start_scale(1.1);
bgart.trigger = Transition.EndNavigation;

**Comment by hyperpie** [comment]
I solved my problem with the pan and scan module. The issue with the [overview] text remains however.

**Comment by calle81** [comment]
I solved my problem with the pan and scan module by adding the transition directly in the module. The issue with the [overview] text remains however.

**Comment by calle81** [comment]
Here is how to only make overview update on EndNavigation:

local text = fe.add_text("info", flx*0.72, fly*0.13, flw*0.26, flh*0.7);


fe.add_transition_callback("on_infotransition")

function on_infotransition(ttype, var, ttime) {
    if ( ttype == Transition.EndNavigation)
        text.msg = fe.game_info(Info.Overview)
	if ( ttype == Transition.StartLayout)
        text.msg = fe.game_info(Info.Overview)
	if ( ttype == Transition.ToNewList)
        text.msg = fe.game_info(Info.Overview)
}
