### ISSUE TITLE
commit f3bc4fba9a460028839386cf946c9d4eac167d72 breaks update on RPi

### ISSUE THREAD

**Issue by haggistech** [mickelson/attract#382]
After the commit two days ago updatign ont he RPi no longer works

Looking at a working version that was updated before the change. attract -v looks like this

```
pi@retropie:~ $ attract -v
Attract-Mode v2.2.1 (Linux, SFML 2.3 +FontConfig +RPi +SWF) 

Using FFmpeg for Audio and Video.
avcodec 57.108.100 / avformat 57.84.100 / swscale 4.9.100 / swresample 2.10.100

Shaders are not available.
```

On one that was updated after that commit it looks like this

```
pi@retropie:~ $ attract -v
Attract-Mode v2.2.1 (Linux, SFML 2.3 +FontConfig +GLES +SWF) 

Using FFmpeg for Audio and Video.
avcodec 57.108.100 / avformat 57.84.100 / swscale 4.9.100 / swresample 2.10.100

Shaders are not available.
```

When booting to attract mode you just get a blank screen, i can still hear background music

**Comment by calle81** [comment]
Same problem here with black screen after update.

**Comment by mickelson** [comment]
This issue is posted in retropie along with a workaround: https://github.com/RetroPie/RetroPie-Setup/issues/2193

I'd prefer not to revert the change, so hopefully this gets fixed in retropie

**Comment by haggistech** [comment]
Perfect thanks

**Comment by fandomfilms** [comment]
I did the update via the interface myself.  It shows the initial pi image and then I hear the loading sound then nothing.
