### ISSUE TITLE
"console" is not showing on windows even if "hide" is disabled

### ISSUE THREAD

**Issue by IceLancerSR** [mickelson/attract#384]
"console" is not showing on windows even if "hide" is disabled

I am trying root some problems but i cant make console to show at all even with hide is disabled for windows.
Native win64 build

**Comment by keilmillerjr** [comment]
attract 3.2 is now split into two different builds - regular and console. Are you using the correct version?

**Comment by IceLancerSR** [comment]
yeah i am using console, figured that option doesnt do anything, can be removed as well then. Thanks anyway
