### ISSUE TITLE
Compile issue with latest source on Ubuntu 14.04

### ISSUE THREAD

**Issue by rcampbel3** [mickelson/attract#388]
I regularly check out the latest code for attract-mode and build from source on my slightly customized Ubuntu 14.04 build machine

The last successful build of Attract Mode on my LInux box was on October 11th.

Here's the output of 'make'

$ make
flags: -Wl,--export-dynamic -I/usr/include/freetype2   -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/audio/include -D__STDC_CONSTANT_MACROS -I/usr/include/freetype2 -I/usr/include/x86_64-linux-gnu   -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/gameswf  -DUSE_XLIB -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_LIBARCHIVE -DUSE_SWRESAMPLE
Compiling obj/fe_input.o...
src/fe_input.cpp: In function ‘void {anonymous}::joy_raw_map_init(const std::vector<std::pair<int, std::basic_string<char> > >&)’:
src/fe_input.cpp:118:4: error: ‘g_joy_femap’ was not declared in this scope
    g_joy_femap[i] = i;
    ^
src/fe_input.cpp:122:9: error: name lookup of ‘i’ changed for ISO ‘for’ scoping [-fpermissive]
   for ( i=0; i<sf::Joystick::Count; i++ )
         ^
src/fe_input.cpp:122:9: note: (if you use ‘-fpermissive’ G++ will accept your code)
src/fe_input.cpp:124:8: error: ‘getIdentification’ is not a member of ‘sf::Joystick’
     << sf::Joystick::getIdentification(i).name.toAnsiString()
        ^
make: *** [obj/fe_input.o] Error 1

**Comment by mickelson** [comment]
Ok, thanks for the report. It should work for you now next time you update the source

**Comment by rcampbel3** [comment]
Hi Now I get this:

$ make
flags: -Wl,--export-dynamic -I/usr/include/freetype2   -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/audio/include -D__STDC_CONSTANT_MACROS -I/usr/include/freetype2 -I/usr/include/x86_64-linux-gnu   -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/gameswf  -DUSE_XLIB -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_LIBARCHIVE -DUSE_SWRESAMPLE
Compiling obj/fe_input.o...
src/fe_input.cpp:132:39: error: definition of ‘FeInputSingle::keyStrings’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 const char *FeInputSingle::keyStrings[] =
                                       ^
src/fe_input.cpp:238:41: error: definition of ‘FeInputSingle::mouseStrings’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 const char *FeInputSingle::mouseStrings[] =
                                         ^
src/fe_input.cpp:254:39: error: definition of ‘FeInputSingle::joyStrings’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 const char *FeInputSingle::joyStrings[] =
                                       ^
src/fe_input.cpp:276:30: error: definition of ‘FeInputSingle::FeInputSingle()’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 FeInputSingle::FeInputSingle()
                              ^
src/fe_input.cpp:282:45: error: definition of ‘FeInputSingle::FeInputSingle(FeInputSingle::Type, int)’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 FeInputSingle::FeInputSingle( Type t, int c )
                                             ^
src/fe_input.cpp:288:100: error: definition of ‘FeInputSingle::FeInputSingle(const sf::Event&, const IntRect&, int)’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 FeInputSingle::FeInputSingle( const sf::Event &e, const sf::IntRect &mc_rect, const int joy_thresh )
                                                                                                    ^
src/fe_input.cpp:419:54: error: definition of ‘FeInputSingle::FeInputSingle(const string&)’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 FeInputSingle::FeInputSingle( const std::string &str )
                                                      ^
src/fe_input.cpp:487:40: error: definition of ‘std::string FeInputSingle::as_string() const’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 std::string FeInputSingle::as_string() const
                                        ^
src/fe_input.cpp:519:37: error: definition of ‘bool FeInputSingle::is_mouse_move() const’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 bool FeInputSingle::is_mouse_move() const
                                     ^
src/fe_input.cpp:526:58: error: definition of ‘bool FeInputSingle::operator<(const FeInputSingle&) const’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 bool FeInputSingle::operator< ( const FeInputSingle &o ) const
                                                          ^
src/fe_input.cpp:534:57: error: definition of ‘bool FeInputSingle::get_current_state(int) const’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 bool FeInputSingle::get_current_state( int joy_thresh ) const
                                                         ^
src/fe_input.cpp:586:38: error: definition of ‘int FeInputSingle::get_current_pos() const’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 int FeInputSingle::get_current_pos() const
                                      ^
src/fe_input.cpp:630:43: error: definition of ‘std::string FeInputSingle::get_joy_name() const’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 std::string FeInputSingle::get_joy_name() const
                                           ^
src/fe_input.cpp:644:58: error: definition of ‘bool FeInputSingle::operator==(const FeInputSingle&) const’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 bool FeInputSingle::operator==( const FeInputSingle &o ) const
                                                          ^
src/fe_input.cpp:649:58: error: definition of ‘bool FeInputSingle::operator!=(const FeInputSingle&) const’ is not in namespace enclosing ‘FeInputSingle’ [-fpermissive]
 bool FeInputSingle::operator!=( const FeInputSingle &o ) const
                                                          ^
src/fe_input.cpp:654:34: error: definition of ‘FeInputMapEntry::FeInputMapEntry()’ is not in namespace enclosing ‘FeInputMapEntry’ [-fpermissive]
 FeInputMapEntry::FeInputMapEntry()
                                  ^
src/fe_input.cpp:659:90: error: definition of ‘FeInputMapEntry::FeInputMapEntry(FeInputSingle::Type, int, FeInputMap::Command)’ is not in namespace enclosing ‘FeInputMapEntry’ [-fpermissive]
 FeInputMapEntry::FeInputMapEntry( FeInputSingle::Type t, int code, FeInputMap::Command c )
                                                                                          ^
src/fe_input.cpp:665:79: error: definition of ‘FeInputMapEntry::FeInputMapEntry(const string&, FeInputMap::Command)’ is not in namespace enclosing ‘FeInputMapEntry’ [-fpermissive]
 FeInputMapEntry::FeInputMapEntry( const std::string &s, FeInputMap::Command c )
                                                                               ^
src/fe_input.cpp:680:89: error: definition of ‘bool FeInputMapEntry::get_current_state(int, const FeInputSingle&) const’ is not in namespace enclosing ‘FeInputMapEntry’ [-fpermissive]
 bool FeInputMapEntry::get_current_state( int joy_thresh, const FeInputSingle &trigger ) const
                                                                                         ^
src/fe_input.cpp:694:42: error: definition of ‘std::string FeInputMapEntry::as_string() const’ is not in namespace enclosing ‘FeInputMapEntry’ [-fpermissive]
 std::string FeInputMapEntry::as_string() const
                                          ^
src/fe_input.cpp:709:40: error: definition of ‘bool FeInputMapEntry::has_mouse_move() const’ is not in namespace enclosing ‘FeInputMapEntry’ [-fpermissive]
 bool FeInputMapEntry::has_mouse_move() const
                                        ^
src/fe_input.cpp:720:47: error: definition of ‘FeMapping::FeMapping(FeInputMap::Command)’ is not in namespace enclosing ‘FeMapping’ [-fpermissive]
 FeMapping::FeMapping( FeInputMap::Command cmd )
                                               ^
src/fe_input.cpp:725:49: error: definition of ‘bool FeMapping::operator<(FeMapping) const’ is not in namespace enclosing ‘FeMapping’ [-fpermissive]
 bool FeMapping::operator< ( const FeMapping o ) const
                                                 ^
src/fe_input.cpp:732:40: error: definition of ‘FeInputMap::commandStrings’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 const char *FeInputMap::commandStrings[] =
                                        ^
src/fe_input.cpp:785:44: error: definition of ‘FeInputMap::commandDispStrings’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 const char *FeInputMap::commandDispStrings[] =
                                            ^
src/fe_input.cpp:838:24: error: definition of ‘FeInputMap::FeInputMap()’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 FeInputMap::FeInputMap()
                        ^
src/fe_input.cpp:856:38: error: definition of ‘void FeInputMap::initialize_mappings()’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 void FeInputMap::initialize_mappings()
                                      ^
src/fe_input.cpp:978:38: error: definition of ‘void FeInputMap::on_joystick_connect()’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 void FeInputMap::on_joystick_connect()
                                      ^
src/fe_input.cpp:983:87: error: definition of ‘FeInputMap::Command FeInputMap::get_command_from_tracked_keys(int) const’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 FeInputMap::Command FeInputMap::get_command_from_tracked_keys( const int joy_thresh ) const
                                                                                       ^
src/fe_input.cpp:1032:113: error: definition of ‘FeInputMap::Command FeInputMap::map_input(const sf::Event&, const IntRect&, int)’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 ::Command FeInputMap::map_input( const sf::Event &e, const sf::IntRect &mc_rect, const int joy_thresh )
                                                                                                       ^
src/fe_input.cpp:1125:80: error: definition of ‘FeInputMap::Command FeInputMap::input_conflict_check(const FeInputMapEntry&)’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 FeInputMap::Command FeInputMap::input_conflict_check( const FeInputMapEntry &e )
                                                                                ^
src/fe_input.cpp:1154:76: error: definition of ‘FeInputMap::Command FeInputMap::get_default_command(FeInputMap::Command)’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 FeInputMap::Command FeInputMap::get_default_command( FeInputMap::Command c )
                                                                            ^
src/fe_input.cpp:1165:84: error: definition of ‘void FeInputMap::set_default_command(FeInputMap::Command, FeInputMap::Command)’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 void FeInputMap::set_default_command( FeInputMap::Command c, FeInputMap::Command v )
                                                                                    ^
src/fe_input.cpp:1170:77: error: definition of ‘bool FeInputMap::get_current_state(FeInputMap::Command, int) const’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 bool FeInputMap::get_current_state( FeInputMap::Command c, int joy_thresh ) const
                                                                             ^
src/fe_input.cpp:1182:69: error: definition of ‘void FeInputMap::get_mappings(std::vector<FeMapping>&) const’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 void FeInputMap::get_mappings( std::vector< FeMapping > &mappings ) const
                                                                     ^
src/fe_input.cpp:1201:56: error: definition of ‘void FeInputMap::set_mapping(const FeMapping&)’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 void FeInputMap::set_mapping( const FeMapping &mapping )
                                                        ^
src/fe_input.cpp:1258:24: error: definition of ‘int FeInputMap::process_setting(const string&, const string&, const string&)’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
  const std::string &fn )
                        ^
src/fe_input.cpp:1321:43: error: definition of ‘void FeInputMap::save(std::ofstream&) const’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 void FeInputMap::save( std::ofstream &f ) const
                                           ^
src/fe_input.cpp:1346:73: error: definition of ‘FeInputMap::Command FeInputMap::string_to_command(const string&)’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 FeInputMap::Command FeInputMap::string_to_command( const std::string &s )
                                                                         ^
src/fe_input.cpp:1377:63: error: definition of ‘bool FeInputMap::is_repeatable_command(FeInputMap::Command)’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 bool FeInputMap::is_repeatable_command( FeInputMap::Command c )
                                                               ^
src/fe_input.cpp:1387:55: error: definition of ‘bool FeInputMap::is_ui_command(FeInputMap::Command)’ is not in namespace enclosing ‘FeInputMap’ [-fpermissive]
 bool FeInputMap::is_ui_command( FeInputMap::Command c )
                                                       ^
src/fe_input.cpp:1395:41: error: definition of ‘FeSoundInfo::settingStrings’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 const char *FeSoundInfo::settingStrings[] =
                                         ^
src/fe_input.cpp:1402:45: error: definition of ‘FeSoundInfo::settingDispStrings’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 const char *FeSoundInfo::settingDispStrings[] =
                                             ^
src/fe_input.cpp:1410:26: error: definition of ‘FeSoundInfo::FeSoundInfo()’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 FeSoundInfo::FeSoundInfo()
                          ^
src/fe_input.cpp:1418:67: error: definition of ‘void FeSoundInfo::set_volume(FeSoundInfo::SoundType, const string&)’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 void FeSoundInfo::set_volume( SoundType t, const std::string &str )
                                                                   ^
src/fe_input.cpp:1443:48: error: definition of ‘int FeSoundInfo::get_set_volume(FeSoundInfo::SoundType) const’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 int FeSoundInfo::get_set_volume( SoundType t ) const
                                                ^
src/fe_input.cpp:1457:49: error: definition of ‘int FeSoundInfo::get_play_volume(FeSoundInfo::SoundType) const’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 int FeSoundInfo::get_play_volume( SoundType t ) const
                                                 ^
src/fe_input.cpp:1465:30: error: definition of ‘bool FeSoundInfo::get_mute() const’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 bool FeSoundInfo::get_mute() const
                              ^
src/fe_input.cpp:1470:36: error: definition of ‘void FeSoundInfo::set_mute(bool)’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 void FeSoundInfo::set_mute( bool m )
                                    ^
src/fe_input.cpp:1477:24: error: definition of ‘int FeSoundInfo::process_setting(const string&, const string&, const string&)’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
  const std::string &fn )
                        ^
src/fe_input.cpp:1509:73: error: definition of ‘bool FeSoundInfo::get_sound(FeInputMap::Command, std::string&) const’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 bool FeSoundInfo::get_sound( FeInputMap::Command c, std::string &name ) const
                                                                         ^
src/fe_input.cpp:1525:77: error: definition of ‘void FeSoundInfo::set_sound(FeInputMap::Command, const string&)’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 void FeSoundInfo::set_sound( FeInputMap::Command c, const std::string &name )
                                                                             ^
src/fe_input.cpp:1533:44: error: definition of ‘void FeSoundInfo::save(std::ofstream&) const’ is not in namespace enclosing ‘FeSoundInfo’ [-fpermissive]
 void FeSoundInfo::save( std::ofstream &f ) const
                                            ^
src/fe_input.cpp:1545:1: error: expected ‘}’ at end of input
 }
 ^
make: *** [obj/fe_input.o] Error 1

**Comment by mickelson** [comment]
Oh man, sorry about that.  It should really be fixed this time.

**Comment by rcampbel3** [comment]
works great. Thanks!
