### ISSUE TITLE
overview for collections

### ISSUE THREAD

**Issue by IceLancerSR** [mickelson/attract#391]
Issue at the moment. Collections are not pulling overview from their respective emulators is there a way to remedy that?
at the moment its looking for overview data in its own collection folder within romlist. Buts too much of a problem to do for each collection.Can it be made to read its respective emulator folder instead?

**Comment by IceLancerSR** [comment]
I mean, its already pulling snaps, wheels, boxart from original folders, why not overview?

**Comment by calle81** [comment]
I agree. This would be a great improvement!

**Comment by IceLancerSR** [comment]
Any chance for this to be seen as implemented?
Pulling data from original game source would be of immense help for maintaining collections data.

**Comment by calle81** [comment]
Bump :) Dont't want this feature to be forgotten. It's a pain having to duplicate all the info files for collections and different emulators like mame 2003 / advance mame all pulling roms from different folders. If we could set the overview dir per emulator (like artwork) that would be very helpful.

**Comment by mickelson** [comment]
Yes I understand now, I'll look at fixing this as suggested, it does make a lot more sense to store it by emulator...

**Comment by mickelson** [comment]
Ok done.  This changes breaks things a bit and users will have to either "generate a romlist" or "scrape artwork" for an emulator in order to have overview information available
