### ISSUE TITLE
Running commands with single quotes seems to confuse Attract-Mode

### ISSUE THREAD

**Issue by TheDarkula** [mickelson/attract#393]
Attract-Mode says that it runs this command:
`retroarch -f -L /usr/lib/libretro/mame_libretro.so 'coleco -rp /path/to/coleco -cart "/path/to/rom.7z"'`

Which, when I run it in a terminal, plays perfectly. Attract-Mode blips out like it can't parse the path correctly.

I tried wrapping the single-quoted bit in just double quotes, which then ran with Attract-Mode, but then the paths can't have spaces in them.

Thanks so much for the awesome frontend. :)

**Comment by TheDarkula** [comment]
If you point me in the correct direction, I'll work on this.

**Comment by mickelson** [comment]
Hey sorry for the delay, there has developed quite a backlog on this project.  It looks like this was an error in the code that should be fixed now if you update to the latest master.  Please let me know if it isn't working for you

**Comment by TheDarkula** [comment]
No worries. It works perfectly now. Thanks so much!
I did have one other unrelated question. Attract-Mode currently omits articles of speech ("The" for example). Is there a toggle for this somewhere I haven't seen?

**Comment by mickelson** [comment]
I'm not sure what you mean about omitting articles of speech.

When attract-mode is scraping and trying to match game names with names from the information source, it does do a couple of tricks including ignoring "the" when matching a name, so that "Simpsons.zip" matches "The Simpsons.zip" for example.  Is that what you mean?

**Comment by TheDarkula** [comment]
Yeah. I had a look at the romlist folder. It's doing stuff like `Ninja Warriors, The.cfg` I can just go in and change those files manually. Thanks so much!

**Comment by TheDarkula** [comment]
Actually, I realised what the problem is. In the `.txt` for each emulator in the `romlists` folder, attract-mode disregards the article `The`. So, for example:
```
Ninja Gaiden Trilogy;Ninja Gaiden Trilogy;Super Nintendo;;;;;;;;;;;;;;
The Ninja Warriors;The Ninja Warriors;Super Nintendo;;;;;;;;;;;;;;
Nosferatu;Nosferatu;Super Nintendo;;;;;;;;;;;;;;
```
Whereas `The Ninja Warriors;The Ninja Warriors;Super Nintendo;;;;;;;;;;;;;;` should be in the "T" section.

**Comment by TheDarkula** [comment]
You might also want to be informed that something very odd is going on with thegamesdb.net's API. Currently none of their /api/*.php pages exist and their wiki hasn't said anything about changes.
