### ISSUE TITLE
fe.get_input_state accepts input when AM isn't focused

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#395]
When AM is not the focused application, get_input_state still accepts input, which it shouldn't. This is on Windows (10), not sure if this occurs with other OS's, but could test.

No input should be received when AM is not focused. I know ideally you aren't multi-tasking when using AM, but that's potentially a security risk :)

**Comment by mickelson** [comment]
ok this should be fixed now: f6548a94ccb1867a663eaafec97f8f9f28b8f965
