### ISSUE TITLE
Some mp4 files dont play anymore on recent git versions

### ISSUE THREAD

**Issue by amuser** [mickelson/attract#406]
The AM cant play some vídeos in mp4 anymore on recent versions compiled on Windows using the MSYS2 (updated) or the cross-compile mxe (updated) on linux

Message on the console:
```
FFmpeg: get_buffer() failed
FFmpeg: thread_get_buffer() failed
FFmpeg: decode_slice_header error
FFmpeg: no frame!
Error decoding video
FFmpeg: get_buffer() failed
FFmpeg: thread_get_buffer() failed
FFmpeg: decode_slice_header error
FFmpeg: no frame!
Error decoding video
FFmpeg: get_buffer() failed
FFmpeg: thread_get_buffer() failed
FFmpeg: decode_slice_header error
FFmpeg: no frame!
Error decoding vídeo
```

Some files not working (stop after a few seconds)

https://anonfile.com/U8xav9ddb6/Sega_CD.mp4
https://anonfile.com/V1xfvad0b8/Sony_PlayStation_2.mp4

Version:
```
./attract -v
Attract-Mode v2.3.0-23 (Windows, SFML 2.4 +SWF +7z)
avcodec 57.107.100 / avformat 57.83.100 / swscale 4.8.100 / swresample 2.9.100

Shaders are available.
```

Log compiling on MSYS2 w/ Windows 10 core i5 4440 and gtx 970:
`$ make
flags: -Wl,--subsystem,windows -O2 -DNDEBUG -Iextlibs/audio/include -D__STDC_CONSTANT_MACROS -mms-bitfields -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/AL -IC:/msys64/mingw64/include -Iextlibs/expat -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/gameswf  -DUSE_LIBARCHIVE -DUSE_SWRESAMPLE
mkdir -p obj
Compiling obj/fe_base.o...
In file included from C:/msys64/mingw64/include/c++/7.2.0/backward/hash_map:60:0,
                 from extlibs/gameswf/base/container.h:75,
                 from extlibs/gameswf/base/image.h:14,
                 from extlibs/gameswf/gameswf/gameswf.h:21,
                 from src/fe_base.cpp:34:
C:/msys64/mingw64/include/c++/7.2.0/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^~~~~~~
Compiling obj/fe_file.o...
Compiling obj/fe_util.o...
Compiling obj/fe_util_sq.o...
Compiling obj/fe_cmdline.o...
Compiling obj/fe_info.o...
Compiling obj/fe_input.o...
Compiling obj/fe_romlist.o...
Compiling obj/fe_settings.o...
Compiling obj/scraper_xml.o...
Compiling obj/scraper_general.o...
Compiling obj/scraper_net.o...
Compiling obj/fe_config.o...
Compiling obj/fe_presentable.o...
Compiling obj/fe_present.o...
Compiling obj/sprite.o...
Compiling obj/fe_image.o...
Compiling obj/fe_sound.o...
Compiling obj/fe_shader.o...
src/fe_shader.cpp: In member function 'void FeShader::set_param(const char*, float)':
src/fe_shader.cpp:84:34: warning: 'void sf::Shader::setParameter(const string&, float)' is deprecated [-Wdeprecated-declarations]
   m_shader.setParameter( name, x );
                                  ^
In file included from src/fe_shader.hpp:26:0,
                 from src/fe_shader.cpp:23:
C:/msys64/mingw64/include/SFML/Graphics/Shader.hpp:554:26: note: declared here
     SFML_DEPRECATED void setParameter(const std::string& name, float x);
                          ^~~~~~~~~~~~
src/fe_shader.cpp: In member function 'void FeShader::set_param(const char*, float, float)':
src/fe_shader.cpp:93:37: warning: 'void sf::Shader::setParameter(const string&, float, float)' is deprecated [-Wdeprecated-declarations]
   m_shader.setParameter( name, x, y );
                                     ^
In file included from src/fe_shader.hpp:26:0,
                 from src/fe_shader.cpp:23:
C:/msys64/mingw64/include/SFML/Graphics/Shader.hpp:562:26: note: declared here
     SFML_DEPRECATED void setParameter(const std::string& name, float x, float y);
                          ^~~~~~~~~~~~
src/fe_shader.cpp: In member function 'void FeShader::set_param(const char*, float, float, float)':
src/fe_shader.cpp:102:40: warning: 'void sf::Shader::setParameter(const string&, float, float, float)' is deprecated [-Wdeprecated-declarations]
   m_shader.setParameter( name, x, y, z );
                                        ^
In file included from src/fe_shader.hpp:26:0,
                 from src/fe_shader.cpp:23:
C:/msys64/mingw64/include/SFML/Graphics/Shader.hpp:570:26: note: declared here
     SFML_DEPRECATED void setParameter(const std::string& name, float x, float y, float z);
                          ^~~~~~~~~~~~
src/fe_shader.cpp: In member function 'void FeShader::set_param(const char*, float, float, float, float)':
src/fe_shader.cpp:111:43: warning: 'void sf::Shader::setParameter(const string&, float, float, float, float)' is deprecated [-Wdeprecated-declarations]
   m_shader.setParameter( name, x, y, z, w );
                                           ^
In file included from src/fe_shader.hpp:26:0,
                 from src/fe_shader.cpp:23:
C:/msys64/mingw64/include/SFML/Graphics/Shader.hpp:578:26: note: declared here
     SFML_DEPRECATED void setParameter(const std::string& name, float x, float y, float z, float w);
                          ^~~~~~~~~~~~
src/fe_shader.cpp: In member function 'void FeShader::set_texture_param(const char*)':
src/fe_shader.cpp:120:59: warning: 'void sf::Shader::setParameter(const string&, sf::Shader::CurrentTextureType)' is deprecated [-Wdeprecated-declarations]
   m_shader.setParameter( name, sf::Shader::CurrentTexture );
                                                           ^
In file included from src/fe_shader.hpp:26:0,
                 from src/fe_shader.cpp:23:
C:/msys64/mingw64/include/SFML/Graphics/Shader.hpp:626:26: note: declared here
     SFML_DEPRECATED void setParameter(const std::string& name, CurrentTextureType);
                          ^~~~~~~~~~~~
src/fe_shader.cpp: In member function 'void FeShader::set_texture_param(const char*, FeImage*)':
src/fe_shader.cpp:133:42: warning: 'void sf::Shader::setParameter(const string&, const sf::Texture&)' is deprecated [-Wdeprecated-declarations]
    m_shader.setParameter( name, *texture );
                                          ^
In file included from src/fe_shader.hpp:26:0,
                 from src/fe_shader.cpp:23:
C:/msys64/mingw64/include/SFML/Graphics/Shader.hpp:618:26: note: declared here
     SFML_DEPRECATED void setParameter(const std::string& name, const Texture& texture);
                          ^~~~~~~~~~~~
Compiling obj/fe_overlay.o...
src/fe_overlay.cpp: In member function 'bool FeOverlay::edit_loop(std::vector<sf::Drawable*>, std::__cxx11::basic_string<unsigned int>&, FeTextPrimative*)':
src/fe_overlay.cpp:1586:34: warning: 'void sf::Text::setColor(const sf::Color&)' is deprecated [-Wdeprecated-declarations]
  cursor.setColor( tp->getColor() );
                                  ^
In file included from C:/msys64/mingw64/include/SFML/Graphics.hpp:51:0,
                 from src/fe_overlay.hpp:26,
                 from src/fe_overlay.cpp:23:
C:/msys64/mingw64/include/SFML/Graphics/Text.hpp:177:26: note: declared here
     SFML_DEPRECATED void setColor(const Color& color);
                          ^~~~~~~~
Compiling obj/fe_window.o...
Compiling obj/tp.o...
src/tp.cpp: In member function 'void FeTextPrimative::setColor(const sf::Color&)':
src/tp.cpp:71:26: warning: 'void sf::Text::setColor(const sf::Color&)' is deprecated [-Wdeprecated-declarations]
   m_texts[i].setColor( c );
                          ^
In file included from C:/msys64/mingw64/include/SFML/Graphics.hpp:51:0,
                 from src/tp.hpp:26,
                 from src/tp.cpp:23:
C:/msys64/mingw64/include/SFML/Graphics/Text.hpp:177:26: note: declared here
     SFML_DEPRECATED void setColor(const Color& color);
                          ^~~~~~~~
src/tp.cpp: In member function 'const sf::Color& FeTextPrimative::getColor() const':
src/tp.cpp:76:29: warning: 'const sf::Color& sf::Text::getColor() const' is deprecated [-Wdeprecated-declarations]
  return m_texts[0].getColor();
                             ^
In file included from C:/msys64/mingw64/include/SFML/Graphics.hpp:51:0,
                 from src/tp.hpp:26,
                 from src/tp.cpp:23:
C:/msys64/mingw64/include/SFML/Graphics/Text.hpp:285:34: note: declared here
     SFML_DEPRECATED const Color& getColor() const;
                                  ^~~~~~~~
Compiling obj/fe_text.o...
Compiling obj/fe_listbox.o...
Compiling obj/fe_vm.o...
Compiling obj/zip.o...
Compiling obj/main.o...
src/main.cpp: In function 'int main(int, char**)':
src/main.cpp:561:44: warning: 'sf::Image sf::RenderWindow::capture() const' is deprecated [-Wdeprecated-declarations]
       sf::Image sshot_img = window.capture();
                                            ^
In file included from C:/msys64/mingw64/include/SFML/Graphics.hpp:47:0,
                 from src/fe_present.hpp:26,
                 from src/main.cpp:24:
C:/msys64/mingw64/include/SFML/Graphics/RenderWindow.hpp:140:27: note: declared here
     SFML_DEPRECATED Image capture() const;
                           ^~~~~~~
Compiling obj/fe_net.o...
Compiling obj/swf.o...
In file included from C:/msys64/mingw64/include/c++/7.2.0/backward/hash_map:60:0,
                 from extlibs/gameswf/base/container.h:75,
                 from extlibs/gameswf/base/tu_file.h:18,
                 from src/swf.cpp:26:
C:/msys64/mingw64/include/c++/7.2.0/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^~~~~~~
Compiling obj/attract.res...
Compiling obj/media.o...
src/media.cpp: In member function 'void FeVideoImp::preload()':
src/media.cpp:534:15: warning: 'AVCodecContext::refcounted_frames' is deprecated [-Wdeprecated-declarations]
    codec_ctx->refcounted_frames = 1;
               ^~~~~~~~~~~~~~~~~
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:2694:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
src/media.cpp:534:15: warning: 'AVCodecContext::refcounted_frames' is deprecated [-Wdeprecated-declarations]
    codec_ctx->refcounted_frames = 1;
               ^~~~~~~~~~~~~~~~~
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:2694:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
src/media.cpp:534:15: warning: 'AVCodecContext::refcounted_frames' is deprecated [-Wdeprecated-declarations]
    codec_ctx->refcounted_frames = 1;
               ^~~~~~~~~~~~~~~~~
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:2694:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
src/media.cpp:540:24: warning: 'int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)' is deprecated [-Wdeprecated-declarations]
     &got_frame, packet );
                        ^
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:4993:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^~~~~~~~~~~~~~~~~~~~~
src/media.cpp: In member function 'void FeVideoImp::video_thread()':
src/media.cpp:706:17: warning: 'AVCodecContext::refcounted_frames' is deprecated [-Wdeprecated-declarations]
      codec_ctx->refcounted_frames = 1;
                 ^~~~~~~~~~~~~~~~~
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:2694:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
src/media.cpp:706:17: warning: 'AVCodecContext::refcounted_frames' is deprecated [-Wdeprecated-declarations]
      codec_ctx->refcounted_frames = 1;
                 ^~~~~~~~~~~~~~~~~
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:2694:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
src/media.cpp:706:17: warning: 'AVCodecContext::refcounted_frames' is deprecated [-Wdeprecated-declarations]
      codec_ctx->refcounted_frames = 1;
                 ^~~~~~~~~~~~~~~~~
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:2694:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
src/media.cpp:712:27: warning: 'int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)' is deprecated [-Wdeprecated-declarations]
        &got_frame, packet );
                           ^
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:4993:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^~~~~~~~~~~~~~~~~~~~~
src/media.cpp:718:35: warning: 'AVFrame::pkt_pts' is deprecated [-Wdeprecated-declarations]
       raw_frame->pts = raw_frame->pkt_pts;
                                   ^~~~~~~
In file included from C:/msys64/mingw64/include/libavcodec/avcodec.h:38:0,
                 from src/media.cpp:31:
C:/msys64/mingw64/include/libavutil/frame.h:302:13: note: declared here
     int64_t pkt_pts;
             ^~~~~~~
src/media.cpp:718:35: warning: 'AVFrame::pkt_pts' is deprecated [-Wdeprecated-declarations]
       raw_frame->pts = raw_frame->pkt_pts;
                                   ^~~~~~~
In file included from C:/msys64/mingw64/include/libavcodec/avcodec.h:38:0,
                 from src/media.cpp:31:
C:/msys64/mingw64/include/libavutil/frame.h:302:13: note: declared here
     int64_t pkt_pts;
             ^~~~~~~
src/media.cpp:718:35: warning: 'AVFrame::pkt_pts' is deprecated [-Wdeprecated-declarations]
       raw_frame->pts = raw_frame->pkt_pts;
                                   ^~~~~~~
In file included from C:/msys64/mingw64/include/libavcodec/avcodec.h:38:0,
                 from src/media.cpp:31:
C:/msys64/mingw64/include/libavutil/frame.h:302:13: note: declared here
     int64_t pkt_pts;
             ^~~~~~~
src/media.cpp: In member function 'bool FeMedia::internal_open(sf::Texture*)':
src/media.cpp:1020:73: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^~~~~
In file included from src/media.cpp:32:0:
C:/msys64/mingw64/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
src/media.cpp:1020:73: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^~~~~
In file included from src/media.cpp:32:0:
C:/msys64/mingw64/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
src/media.cpp:1020:73: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^~~~~
In file included from src/media.cpp:32:0:
C:/msys64/mingw64/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
src/media.cpp:1075:73: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^~~~~
In file included from src/media.cpp:32:0:
C:/msys64/mingw64/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
src/media.cpp:1075:73: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^~~~~
In file included from src/media.cpp:32:0:
C:/msys64/mingw64/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
src/media.cpp:1075:73: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = m_imp->m_format_ctx->streams[stream_id]->codec;
                                                                         ^~~~~
In file included from src/media.cpp:32:0:
C:/msys64/mingw64/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
src/media.cpp: In member function 'virtual bool FeMedia::onGetData(sf::SoundStream::Chunk&)':
src/media.cpp:1232:23: warning: 'AVCodecContext::refcounted_frames' is deprecated [-Wdeprecated-declarations]
   m_audio->codec_ctx->refcounted_frames = 1;
                       ^~~~~~~~~~~~~~~~~
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:2694:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
src/media.cpp:1232:23: warning: 'AVCodecContext::refcounted_frames' is deprecated [-Wdeprecated-declarations]
   m_audio->codec_ctx->refcounted_frames = 1;
                       ^~~~~~~~~~~~~~~~~
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:2694:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
src/media.cpp:1232:23: warning: 'AVCodecContext::refcounted_frames' is deprecated [-Wdeprecated-declarations]
   m_audio->codec_ctx->refcounted_frames = 1;
                       ^~~~~~~~~~~~~~~~~
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:2694:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
src/media.cpp:1241:82: warning: 'int avcodec_decode_audio4(AVCodecContext*, AVFrame*, int*, const AVPacket*)' is deprecated [-Wdeprecated-declarations]
   int len = avcodec_decode_audio4( m_audio->codec_ctx, frame, &got_frame, packet );
                                                                                  ^
In file included from src/media.cpp:31:0:
C:/msys64/mingw64/include/libavcodec/avcodec.h:4944:5: note: declared here
 int avcodec_decode_audio4(AVCodecContext *avctx, AVFrame *frame,
     ^~~~~~~~~~~~~~~~~~~~~
mkdir -p obj/expat
Compiling obj/expat/xmlparse.o...
Compiling obj/expat/xmlrole.o...
Compiling obj/expat/xmltok.o...
Archiving obj/libexpat.a...
mkdir -p obj/squirrel
Compiling obj/squirrel/sqapi.o...
Compiling obj/squirrel/sqbaselib.o...
Compiling obj/squirrel/sqfuncstate.o...
Compiling obj/squirrel/sqdebug.o...
Compiling obj/squirrel/sqlexer.o...
Compiling obj/squirrel/sqobject.o...
Compiling obj/squirrel/sqcompiler.o...
Compiling obj/squirrel/sqstate.o...
Compiling obj/squirrel/sqtable.o...
Compiling obj/squirrel/sqmem.o...
Compiling obj/squirrel/sqvm.o...
Compiling obj/squirrel/sqclass.o...
Archiving obj/libsquirrel.a...
mkdir -p obj/sqstdlib
Compiling obj/sqstdlib/sqstdblob.o...
Compiling obj/sqstdlib/sqstdio.o...
Compiling obj/sqstdlib/sqstdstream.o...
Compiling obj/sqstdlib/sqstdmath.o...
Compiling obj/sqstdlib/sqstdstring.o...
Compiling obj/sqstdlib/sqstdaux.o...
Compiling obj/sqstdlib/sqstdsystem.o...
Compiling obj/sqstdlib/sqstdrex.o...
Archiving obj/libsqstdlib.a...
mkdir -p obj/gsbaselib
Compiling obj/gsbaselib/configvars.o...
Compiling obj/gsbaselib/ear_clip_triangulate_float.o...
Compiling obj/gsbaselib/ear_clip_triangulate_sint16.o...
Compiling obj/gsbaselib/container.o...
Compiling obj/gsbaselib/file_util.o...
Compiling obj/gsbaselib/image.o...
Compiling obj/gsbaselib/image_filters.o...
Compiling obj/gsbaselib/jpeg.o...
Compiling obj/gsbaselib/logger.o...
Compiling obj/gsbaselib/membuf.o...
Compiling obj/gsbaselib/postscript.o...
Compiling obj/gsbaselib/triangulate_float.o...
Compiling obj/gsbaselib/triangulate_sint32.o...
Compiling obj/gsbaselib/tu_file.o...
Compiling obj/gsbaselib/tu_gc_singlethreaded_marksweep.o...
Compiling obj/gsbaselib/tu_loadlib.o...
Compiling obj/gsbaselib/tu_random.o...
Compiling obj/gsbaselib/tu_timer.o...
Compiling obj/gsbaselib/tu_types.o...
Compiling obj/gsbaselib/utf8.o...
Compiling obj/gsbaselib/utility.o...
Compiling obj/gsbaselib/zlib_adapter.o...
mkdir -p obj/gameswflib
mkdir -p obj/gameswflib/gameswf_as_classes
Compiling obj/gameswflib/gameswf_as_classes/as_array.o...
Compiling obj/gameswflib/gameswf_as_classes/as_boolean.o...
Compiling obj/gameswflib/gameswf_as_classes/as_broadcaster.o...
Compiling obj/gameswflib/gameswf_as_classes/as_class.o...
Compiling obj/gameswflib/gameswf_as_classes/as_color.o...
Compiling obj/gameswflib/gameswf_as_classes/as_color_transform.o...
Compiling obj/gameswflib/gameswf_as_classes/as_date.o...
Compiling obj/gameswflib/gameswf_as_classes/as_event.o...
Compiling obj/gameswflib/gameswf_as_classes/as_flash.o...
Compiling obj/gameswflib/gameswf_as_classes/as_geom.o...
Compiling obj/gameswflib/gameswf_as_classes/as_global.o...
Compiling obj/gameswflib/gameswf_as_classes/as_key.o...
Compiling obj/gameswflib/gameswf_as_classes/as_loadvars.o...
Compiling obj/gameswflib/gameswf_as_classes/as_math.o...
Compiling obj/gameswflib/gameswf_as_classes/as_matrix.o...
Compiling obj/gameswflib/gameswf_as_classes/as_mcloader.o...
Compiling obj/gameswflib/gameswf_as_classes/as_mouse.o...
Compiling obj/gameswflib/gameswf_as_classes/as_mouse_event.o...
Compiling obj/gameswflib/gameswf_as_classes/as_netconnection.o...
Compiling obj/gameswflib/gameswf_as_classes/as_netstream.o...
Compiling obj/gameswflib/gameswf_as_classes/as_number.o...
Compiling obj/gameswflib/gameswf_as_classes/as_point.o...
Compiling obj/gameswflib/gameswf_as_classes/as_selection.o...
Compiling obj/gameswflib/gameswf_as_classes/as_sharedobject.o...
Compiling obj/gameswflib/gameswf_as_classes/as_sound.o...
Compiling obj/gameswflib/gameswf_as_classes/as_string.o...
Compiling obj/gameswflib/gameswf_as_classes/as_textformat.o...
Compiling obj/gameswflib/gameswf_as_classes/as_transform.o...
Compiling obj/gameswflib/gameswf_as_classes/as_xml.o...
Compiling obj/gameswflib/gameswf_as_classes/as_xmlsocket.o...
Compiling obj/gameswflib/gameswf_abc.o...
Compiling obj/gameswflib/gameswf_action.o...
Compiling obj/gameswflib/gameswf_avm2.o...
Compiling obj/gameswflib/gameswf_as_sprite.o...
Compiling obj/gameswflib/gameswf_button.o...
Compiling obj/gameswflib/gameswf_canvas.o...
Compiling obj/gameswflib/gameswf_character.o...
Compiling obj/gameswflib/gameswf_disasm.o...
Compiling obj/gameswflib/gameswf_dlist.o...
Compiling obj/gameswflib/gameswf_environment.o...
Compiling obj/gameswflib/gameswf_filters.o...
Compiling obj/gameswflib/gameswf_font.o...
Compiling obj/gameswflib/gameswf_function.o...
Compiling obj/gameswflib/gameswf_impl.o...
Compiling obj/gameswflib/gameswf_listener.o...
Compiling obj/gameswflib/gameswf_log.o...
Compiling obj/gameswflib/gameswf_morph2.o...
Compiling obj/gameswflib/gameswf_movie_def.o...
Compiling obj/gameswflib/gameswf_object.o...
Compiling obj/gameswflib/gameswf_player.o...
Compiling obj/gameswflib/gameswf_render.o...
Compiling obj/gameswflib/gameswf_root.o...
Compiling obj/gameswflib/gameswf_shape.o...
Compiling obj/gameswflib/gameswf_sound.o...
Compiling obj/gameswflib/gameswf_sprite.o...
Compiling obj/gameswflib/gameswf_sprite_def.o...
Compiling obj/gameswflib/gameswf_stream.o...
Compiling obj/gameswflib/gameswf_styles.o...
Compiling obj/gameswflib/gameswf_tesselate.o...
Compiling obj/gameswflib/gameswf_text.o...
Compiling obj/gameswflib/gameswf_tools.o...
Compiling obj/gameswflib/gameswf_types.o...
Compiling obj/gameswflib/gameswf_value.o...
Compiling obj/gameswflib/gameswf_video_impl.o...
Compiling obj/gameswflib/gameswf_mutex.o...
Compiling obj/gameswflib/gameswf_sound_handler_openal.o...
Compiling obj/gameswflib/gameswf_freetype.o...
Compiling obj/gameswflib/gameswf_render_handler_ogl.o...
Archiving obj/libgameswf.a...
mkdir -p obj/audiolib
Compiling obj/audiolib/ALCheck.o...
Compiling obj/audiolib/AudioDevice.o...
Compiling obj/audiolib/Listener.o...
Compiling obj/audiolib/SoundSource.o...
Compiling obj/audiolib/SoundStream.o...
Archiving obj/libaudio.a...
Creating executable: attract.exe
`

**Comment by mickelson** [comment]
What is your "Video decoder" set to (in Config->General->Video decoder)?

Also, could you try running 'attract --loglevel debug' and provide the output that provides?

**Comment by amuser** [comment]
Yes, the problem is the video decoder option with dxva2
Now, after change to software, all videos are working fine again.

I can't remember when i changed to "dxva2", i was thinking it already was configured with "software".
