### ISSUE TITLE
floor() returns wrong value

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#413]
```
print( 1080.0 * 0.025 + "\n" )
print( floor( 1080.0 * 0.025 ) + "\n" )
print( floor( 1080.0 / 40.0 ) + "\n" )

```
result:
27
26
27

expected result:
27
27
27

**Comment by oomek** [comment]
The same happens with abs() function. //scratching head vigorously

**Comment by oomek** [comment]
.tointeger() yields the same result

**Comment by oomek** [comment]
Ok, it seems that multiplication by a number < 1 is producing a rounding errors in Squirrel
I found a workarond for that, but it's not a fix and I suppose the fix it's out of your reach, am I right? 
```
print(floor( 1080.0 * 0.025 ) + "\n" )
print(floor( format( "%.5f", 1080.0 * 0.025 ).tofloat() ) + "\n" )

```

output:
26
27

**Comment by oomek** [comment]
So the floor fixed function should look like this:

function floorf( a ){
	return floor( format( "%.5f", a ).tofloat() )
}

**Comment by oomek** [comment]
I think the root of the problem is how Squirrel stores floats
`print( format( "%.30f", 0.025) )`
returns:
0.024999998509883881
instead of:
0.02500000037252902984619140625

Summarizing this long monologue I can say only that:
Squirrel does not conform to the IEEE-754 standard.

**Comment by mickelson** [comment]
I’m not sure what you are talking about.  From what you have posted it looks like squirrel is giving you a double precision binary floating point format, about 15 to 17 significant decimal digits, which is right in line with the standard:  https://en.m.wikipedia.org/wiki/Double-precision_floating-point_format

I’m pretty sure squirrel is just providing a thin wrapper on the float and double float functionality in the standard c/c++ library.

**Comment by oomek** [comment]
I'm talking about that the floor() function cannot be trusted when I calculate the size of elements based on the screen size:
`local elementHeight = floor( fe.layout.height * 0.025 )`
returns 26 instead of 27 for fe.layout.height = 1080

**Comment by oomek** [comment]
I contacted the Squirrel developer and he's getting correct results. Do you have any clue what could affect that? Compiler settings maybe?

**Comment by oomek** [comment]
i found this:
https://gcc.gnu.org/wiki/FloatingPointMath

**Comment by oomek** [comment]
I found the problem
32bit build is showing 26
64bit build is showing 27
