### ISSUE TITLE
.zorder can not be set for clones drawn on a surface

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#418]
When I try to set a zorder of a clone drawn on a surface there is no effect, the objects stay in order as they've been initialized.

In the following example the lines commented are not working:

```
local flw = fe.layout.width
local flh = fe.layout.height

local surface = fe.add_surface( flw, flh/2 )
surface.set_pos( 0, flh/2 )

local image1 = fe.add_artwork( "snap", flw* 0.2, flh * 0.1, flw * 0.35, flh * 0.3 )
local image2 = fe.add_artwork( "snap", flw * 0.45, flh * 0.1, flw * 0.35, flh * 0.3 )
image1.set_rgb( 255, 100, 100 )
image2.set_rgb( 100, 100, 255 )
image1.video_flags = Vid.ImagesOnly
image2.video_flags = Vid.ImagesOnly

local image1clone = surface.add_clone( image1 )
local image2clone = surface.add_clone( image2 )

function transition( ttype, var, ttime ) {
    switch( ttype ) {
        case Transition.FromOldSelection:
            if (var > 0 ) {
                image1.zorder = 100
                image1clone.zorder = 100 //this line does nothing
            }
            if (var < 0 ) {
                image2.zorder = 100
                image2clone.zorder = 100  //this line does nothing
            }
            break
    }    
    return false
}
fe.add_transition_callback( "transition" )
```

**Comment by mickelson** [comment]
I think this is behaving as intended.

Surfaces are off-screen render textures.  They are essentially their own images with their own zorder etc.  The objects that you draw to a surface are drawn to the surface based on their zorder.  But then the surface image itself gets drawn to the screen based on its zorder.  So if you want to change where the clones are being drawn, you also need to change the zorder of the surface to bring it forward/backwards accordingly in the zorder.

AM's surfaces wrap an SFML render textures, more info here: https://www.sfml-dev.org/documentation/2.4.2/classsf_1_1RenderTexture.php#details
