### ISSUE TITLE
More of a question vs issue

### ISSUE THREAD

**Issue by techiexp1969** [mickelson/attract#428]
I am reading your code on the steps on installing Attract-Mode on Raspian Jessie.

Where I am getting confused is, when you should and should not be in the "develop" directory.

Would I be correct in saying that, this should be done in "develop"
cd ~/develop
git clone --depth 1 https://github.com/mickelson/sfml-pi sfml-pi
mkdir sfml-pi/build; cd sfml-pi/build
cmake .. -DSFML_RPI=1 -DEGL_INCLUDE_DIR=/opt/vc/include -DEGL_LIBRARY=/opt/vc/lib/libbrcmEGL.so -DGLES_INCLUDE_DIR=/opt/vc/include -DGLES_LIBRARY=/opt/vc/lib/libbrcmGLESv2.so
sudo make install
sudo ldconfig

but this instruction: "sudo apt-get install libavutil-dev libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavresample-dev " is not done in "develop".

Is that correct?

**Comment by techiexp1969** [comment]
Also, after several attempts, I continue to get this error:

Attract-Mode v2.3.0 (Linux, SFML 2.4 +FontConfig +GLES +SWF)
avcodec 58.11.101 / avformat 58.9.100 / swscale 5.0.101 / swresample 3.0.101

Config file not found: /home/pi/.attract/attract.cfg
 - Constructed 1 filters in 0 ms (1 comparisons)
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
Attract-Mode v2.3.0 (Linux, SFML 2.4 +FontConfig +GLES +SWF)
avcodec 58.11.101 / avformat 58.9.100 / swscale 5.0.101 / swresample 3.0.101

**Comment by mickelson** [comment]
Hi, this is the bug tracker for attract mode and is not a good place for general help requests, please try the forum for support questions (forum.attractmode.org), thanks
