### ISSUE TITLE
[Suggestion] Wine Version list

### ISSUE THREAD

**Issue by Sethox** [mickelson/attract#429]
So congratulations on giving Wine-Staging life again. I noticed experimental wine builds in the Managing list in the Lutris application. My suggestion is to either have a separate tab for installed or experimental wine builds. This is so within the application I can remove installed wine builds that is no longer supported. The build I installed is no longer registered and I cannot remove it (since the list does not show the experimental version besides one).
There could also be another column on the window (in managing wine builds) saying "status", it's to say if it's outdated/drafted/ongoing/new/old/abandoned. So the users can manage it by themselves (as intended).

**Comment by Enverex** [comment]
Er, I have a feeling you've accidentally posted this to the wrong issue tracker.
