### ISSUE TITLE
Idea for your new “per display” layout parameters 

### ISSUE THREAD

**Issue by progets** [mickelson/attract#436]
I see that you mention "when i get some time i’m going to look at implementing “per display” layout parameters" here https://github.com/mickelson/attract/pull/432. I assume that you mean that each display listed in the attract.cfg will be able to store the layout options separately vs. all layouts with the same name using the settings typically appended to the end of the file. I think it's a great idea and a way to prevent needing multiple layout folders to accomplish the same thing.

My idea works into this concept and would include an option to choose the specific .nut in the layout directory. This function exists today but only using a key/button to cycle through the .nut files and I don't think you can actually see which .nut file is being used anywhere (this can be confusing). By having an option to choose the .nut file per display in the menu will allow complete layouts to have different .nut files for a Displays Menu vs. an Arcade Menu vs. Console Systems, etc. while all using one layout folder (and one set of art assets) with little confusion.

I think this could work the same way that choosing a layout from the Display Menu does today. It would be an option directly underneath the Display Menu layout option and it would cycle through *.nut files like the the layout option cycles through /layouts/*.

**Comment by calle81** [comment]
Hi, I agree with Progets. This would be an excellent addition.

**Comment by progets** [comment]
FYI - I wondered why the end of my post was in italic. I can now see that my use of the asterisk before ".nut" and after "/layouts/"  in the last line of the post was the cause.

Does an asterisk need to be escaped somehow?

**Comment by progets** [comment]
@calle81 - Please post your layouts on the forum. Some are great but I hate having to download 16 GB to get a 100 MB layout. No offence but I don't want "branded" artwork and I already have all the media I need.

**Comment by calle81** [comment]
Hi, I finished working on an update yesterday. Just waiting for feedback from some beta testers to make sure all is good.

Here is the latest version if you want to test it.

https://mega.nz/#!OYtzQKzQ!znNgzdhbW4q_FioJwuUi9-zX_hLEBDkptUlq84PrV_g

Delete the old HP2 layouts in attract/layouts and replace them with the ones in the file. Don't copy over existing themes as that will leave a lot of unwanted stuff like views that have been renamed or deleted!
Paste in the layout configs from "PUT THIS IN ATTRACT.CFG FOR X" over your current layout configs in attract/attract.cfg. Make a backup first just in case. Also delete your attract/attract.am file. This file keeps a track of which view you had selected for a specific display. A new one will be generated when you start AM.

You can see some videos with new features etc on my youtube channel.

https://www.youtube.com/channel/UCM8xZ6CbyMiLrokOQwfWl6Q

Let me know if you run into any issues.

/Carl

Från: progets <notifications@github.com>
Skickat: den 26 mars 2018 10:55
Till: mickelson/attract <attract@noreply.github.com>
Kopia: Carl Hagström - Nitma <carl.h@nitma.se>; Mention <mention@noreply.github.com>
Ämne: Re: [mickelson/attract] Idea for your new “per display” layout parameters (#436)


@calle81<https://github.com/calle81> - Please post your layouts on the forum. Some are great but I hate having to download 16 GB to get a 100 MB layout. No offence but I don't want "branded" artwork and I already have all the media I need.

**Comment by calle81** [comment]
OK, I thought it was a pm sent somehow and replied using e-mail. I removed my previous reply.

**Comment by mickelson** [comment]
Ok I think I've got this one, it should be fairly straight forward to implement, but might have to work a bit differently in the UI due to the limitations of the config menu system, I'll see what I can do

I think I've finally got the per_display parameters ready to go so they should be checked in soon and I will look at having the layout file configurable.
