### ISSUE TITLE
REQ: seperate image / video smoothing

### ISSUE THREAD

**Issue by tednilsen** [mickelson/attract#437]
would be nice to have the ability to turn off smoothing of videos, while maintaining the ability to smooth images / artwork.
decoding videos with low resolution (eg. 248x240) for retro games looks like shit when smoothed, perfect when smoothing is off - but then the images / artwork is chunky.

would love to see the ability to turn smoothing on / off for objects, so I could have the video + spinwheel smooth off, and other sprites and art smoothed.

the images provided shows the video with image-smoothing on and off, the difference says it all.

![chunky2](https://user-images.githubusercontent.com/9750957/38575584-0721c83c-3cfc-11e8-80d7-7a73e20e4d51.png)

![smooth2](https://user-images.githubusercontent.com/9750957/38575587-09885aaa-3cfc-11e8-8b2f-259caf925d63.png)

![chunky](https://user-images.githubusercontent.com/9750957/38575494-d997c8c6-3cfb-11e8-8c1d-255fe91442c0.png)

![smooth](https://user-images.githubusercontent.com/9750957/38575484-d1e34088-3cfb-11e8-8225-6335f2ea26b1.png)

**Comment by mickelson** [comment]
Hi, there is a smooth attribute for each image in attract mode, so layouts can set whether or not to smooth something on an image by image basis.  So your layout could specify not to smooth the video... Does this help?

see: https://github.com/mickelson/attract/blob/master/Layouts.md#Image
