### ISSUE TITLE
fresh retropie 4.4 install

### ISSUE THREAD

**Issue by frezeen** [mickelson/attract#439]
hi i install fresh 4.4 retropie, manual compile attractmode following wiki instruction and when i launch attractmode i got this one:
pi@retropie:~/develop/attract $ attract
Attract-Mode v2.3.0 (Linux, SFML 2.4 +FontConfig +GLES +SWF)
avcodec 58.19.100 / avformat 58.13.100 / swscale 5.2.100 / swresample 3.2.100

Config file not found: /home/pi/.attract/attract.cfg
 - Constructed 1 filters in 0 ms (1 comparisons)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

audio is ok, i can hear it but are this warnings about jack server normal?  hw is rpi 3b+

**Comment by mickelson** [comment]
I'm not sure that this error is an issue. I don't think it is coming from attract mode though, it looks like something to do with how sound is configured on your system.
