### ISSUE TITLE
Launching mame : Unable to create  the Direct3D device

### ISSUE THREAD

**Issue by monkeyboy1970** [mickelson/attract#44]
Mame launches fine from the command line, no issues. Many different versions of Mame work fine. However, when launching via the frontend, I get a black screen. If I alt-tab, the Mame window becomes active and runs fine. If I alt tab through the active windows while Mame is running, there is also a DOS window with the message 'Unable to  create the Direct 3D device, repeated many times.  If I alt-tab back to the Mame window and escape back to the frontend the DOS window disappears.   Strange thing is, after a reboot, the frontend works as intended and launches Mame just fine but only once, then the above problem occurs until I reboot.  I've used all the available layouts, including a very basic one with no fancy transitions and the problem still persists.

Brilliant work BTW :)

**Comment by mickelson** [comment]
The most recent version of windows baseline mame (0.160) has added opengl rendering as an option.  I suspect running mame with opengl would fix this problem, since opengl is what attractmode uses as well.

**Comment by mickelson** [comment]
I'm closing since this appears to be a battle between OpenGL vs. Direct 3D, which will depend on the graphic  drivers installed etc.  The ability of Mame to render in opengl now should be an option for dealing with this in the future...
