### ISSUE TITLE
fe.signal(“layout_settings”)

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#444]
If you often change the layout settings you are forced now to dive into 3 levels of submenus. The ability to bind it to a button would ease this.
Also the ability to customise the look of that submenu like the rest of overlay dialogs would be a great addition.

**Comment by calle81** [comment]
I agree with Oomek. The three levels of sub menus to reach the layout options is a pain.

**Comment by GiacomoBianchi** [comment]
Layout option inside 3 levels is not so intuitive to find it and then it is not rapid when you have to often change setting, specially when I'm writing a new theme.
Thanks for creating this amazing project!

**Comment by mickelson** [comment]
Ok this is added now. There is  a "Layout Options" control that can now be mapped to get you straight to the layout configuration screen
