### ISSUE TITLE
word_wrap - unexpected behaviour - bug or feature ?

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#449]
As you can probably see I'm preparing a pull request enhancing the alignment modes. In the meantime i stumbled across a weird behaviour of the word_wrap property. I fixed it, but before I pull the commit I just need to make sure whether it's a deliberate behaviour, or just some overlooked bug.

The easiest way to explain I think will be to show a video. The string contains an alphabet letters divided with spaces.

https://www.youtube.com/watch?v=7QEVZ5mDMjc

**Comment by mickelson** [comment]
I think it is an overlooked bug. I don't recall any reason why that would be intentional.

As you are probably discovering the word wrapping code is generally a mess. I commend you for taking it on and trying to sort it out!

**Comment by oomek** [comment]
Thanks for confirmation. I’ve already fixed it it’s in my branch with align modes. But it’s one commit behind as I’m testing it now.

**Comment by oomek** [comment]
Fixed in: https://github.com/mickelson/attract/pull/448/commits/2d1e1ad6b76ff62abb7629c94c224993fad603de
