### ISSUE TITLE
attract compile issue on Ubuntu 14.04 

### ISSUE THREAD

**Issue by rcampbel3** [mickelson/attract#452]
I periodically compile attract mode from source on Ubuntu 14.04. The last time I was able to build from source successfully was Jan 31, 2018.

Here are the errors from my latest compile attempt after doing a git pull today:

<pre>
Compiling obj/fe_blend.o...
src/fe_blend.cpp: In static member function ‘static sf::BlendMode FeBlend::get_blend_mode(int)’:
src/fe_blend.cpp:35:76: error: expression list treated as compound expression in functional cast [-fpermissive]
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcColor);
                                                                            ^
src/fe_blend.cpp:35:24: error: expected primary-expression before ‘(’ token
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcColor);
                        ^
src/fe_blend.cpp:35:29: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcColor);
                             ^
src/fe_blend.cpp:35:49: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcColor);
                                                 ^
src/fe_blend.cpp:37:81: error: expression list treated as compound expression in functional cast [-fpermissive]
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::OneMinusSrcAlpha);
                                                                                 ^
src/fe_blend.cpp:37:24: error: expected primary-expression before ‘(’ token
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::OneMinusSrcAlpha);
                        ^
src/fe_blend.cpp:37:29: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::OneMinusSrcAlpha);
                             ^
src/fe_blend.cpp:37:54: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::OneMinusSrcAlpha);
                                                      ^
src/fe_blend.cpp:39:73: error: expression list treated as compound expression in functional cast [-fpermissive]
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::SrcColor);
                                                                         ^
src/fe_blend.cpp:39:24: error: expected primary-expression before ‘(’ token
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::SrcColor);
                        ^
src/fe_blend.cpp:39:29: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::SrcColor);
                             ^
src/fe_blend.cpp:39:54: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::DstColor, sf::BlendMode::SrcColor);
                                                      ^
src/fe_blend.cpp:41:76: error: expression list treated as compound expression in functional cast [-fpermissive]
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcAlpha);
                                                                            ^
src/fe_blend.cpp:41:24: error: expected primary-expression before ‘(’ token
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcAlpha);
                        ^
src/fe_blend.cpp:41:29: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcAlpha);
                             ^
src/fe_blend.cpp:41:49: error: ‘sf::BlendMode’ is not a class or namespace
    return sf::BlendMode(sf::BlendMode::One, sf::BlendMode::OneMinusSrcAlpha);
                                                 ^
make: *** [obj/fe_blend.o] Error 1
</pre>

**Comment by mickelson** [comment]
Hi there, I'm unable to reproduce this here but some changes have been made that might fix this.  Could you try compiling again with the latest code from master and let me know if it fixes this? thanks

**Comment by rcampbel3** [comment]
Hi -- this fixes my compile issue. Thanks!
