### ISSUE TITLE
Menu-Art using Box returns Flyer art instead

### ISSUE THREAD

**Issue by zombiesbyte** [mickelson/attract#455]
If the `menu-art` directory contains
`box`, `flyer`, `marquee` etc

then I would assume that using

```
add_art("box"),
add_art("flyer")
add_art("marquee")
//etc,
```

would correspond.

Issue: `fe.get_art( "box" , currentID );` returns `C:\emu\attract\menu-art\flyer\nes.png` for example

fanart, flyer, marquee, snap and wheel all work fine. It's just the **box** folder for some reason

**Comment by mickelson** [comment]
Thanks for the report, this should be fixed now.
