### ISSUE TITLE
Possible Attract-Mode BUG: Listbox not fade correctly. 

### ISSUE THREAD

**Issue by zlagos** [mickelson/attract#459]
I use this code to fade a listbox after 3.5 seconds:

```
local flx = fe.layout.width;
local fly = fe.layout.height;
local flw = fe.layout.width;
local flh = fe.layout.height;

// Listbox
if(my_config["wheel_type"] == "listbox")
{
	::OBJECTS <- {lbx = fe.add_listbox(flx*0.76, fly*0.33, flw*0.20, flh*0.64)}
	OBJECTS.lbx.rows = 21;
	OBJECTS.lbx.charsize = 24;
	OBJECTS.lbx.align = Align.Centre;
	OBJECTS.lbx.selbg_alpha = 0;
	OBJECTS.lbx.set_selbg_rgb(255,255,255);
	OBJECTS.lbx.set_rgb(0,0,0);
	OBJECTS.lbx.set_sel_rgb(255,255,255);

	// Fade Listbox
	local move_lbx1 = { when = Transition.ToNewSelection, property = "alpha", start = 0, end = 255, time = 1}  
	local move_lbx2 = { when = When.ToNewSelection, property = "alpha", start = 255, end = 0, time = 2500, delay = 3500}  
	animation.add(PropertyAnimation(OBJECTS.lbx, move_lbx1));
	animation.add(PropertyAnimation(OBJECTS.lbx, move_lbx2));	
}

```

But it does not fade correctly. 

The rest of the listbox fades correctly, **but the selected field in the listbox remains visible.**

It seems totally an Attract-Mode bug.

Does anyone know why this happens?

Is there any solution?

**Comment by oomek** [comment]
You are right. The properties ListBox.sel_alpha, ListBox.selbg_alpha and functions ListBox.set_sel_rgb(), ListBox.set_selbg_rgb() update only on  Transition.ToNewList. they do not update from tick() and other transitions.

**Comment by zlagos** [comment]
And there is no solution at the moment? Can not you think of anything?

**Comment by oomek** [comment]
https://github.com/mickelson/attract/commit/62c2a6e100194daf663c0ede39833172eb65eb1e#diff-8f27264b8acedbb428a1b6ab211bf664R177

https://github.com/mickelson/attract/commit/62c2a6e100194daf663c0ede39833172eb65eb1e#diff-8f27264b8acedbb428a1b6ab211bf664R194

@mickelson  Would you take a look at this bug please. I wouldn't like to mess with your commits.

**Comment by mickelson** [comment]
Ok found the problem, it should be fixed now
