### ISSUE TITLE
v2.4 build not working on Windows XP: Unable to launch: "bcrypt.dll was not found"

### ISSUE THREAD

**Issue by Joe737** [mickelson/attract#464]
I get the message "This application has failed to start because bcrypt.dll was not found"

I am able to run version 2.3 no problem.  Running running sfc /scannow with the Windows CD didn't fix

Running Window XP SP3 with a Pentium D 3.4.  Thanks!

**Comment by mickelson** [comment]
Hi,

I have figured out the issue.  FFmpeg dropped support for WinXP as of version 4.0: https://github.com/FFmpeg/FFmpeg/blob/master/Changelog

I have tried building against an older version of FFmpeg and it seems to fix the issue. Please try one of these packages and let me know if it fixes things for you:

32-bit: https://github.com/mickelson/attract/releases/download/v2.4.0/WinXP-attract-v2.4.0-win32.zip
64-bit: https://github.com/mickelson/attract/releases/download/v2.4.0/WinXP-attract-v2.4.0-win64.zip

**Comment by Joe737** [comment]
Wow, thank you! It launches and appears to work for me (XP 32-bit), I'll get it all configured and report back, but thank you so much!

**Comment by mickelson** [comment]
I suggesting asking your questions about setting up the software on the forum.  No suggestions occur to me based on what you have described.
