### ISSUE TITLE
More custom keys or "per_display" custom keys...

### ISSUE THREAD

**Issue by zlagos** [mickelson/attract#469]
Hello, I do not know if it would be very complicated to add more custom keys to the AM, or to put the custom keys separated by display ...
I am working in a jukebox for AM, without external player, and with 6 custom keys I do not have enough if I have to share them with the rest of the displays ...
It could be done?
Do I have any other solution that I do not know?

**Comment by mickelson** [comment]
Hi you don’t need to be limited to the custom keys in the config menu.  Layouts and plugins can check themselves for any user input.  Take a look at the attracman layout (for how it allows users to control pacman and one of the ghosts) or the submenu module for how it checks for when a user triggers the submenu.  there should be no limit to how many inputs you could be checking for.

I hope that helps get you going! I never considered that this would get used for a jukebox.  cool

**Comment by zlagos** [comment]
I'll see it, thanks.
And the JukeBox I have it operational by 99%. Today or tomorrow I'll upload it to the forum, to Themes.

**Comment by mickelson** [comment]
great, i'll check it out
