### ISSUE TITLE
Mac OS X: location of mouse pointer triggers hot corners

### ISSUE THREAD

**Issue by pmonks** [mickelson/attract#472]
**Steps to reproduce:**

1. Open `System Preferences > Desktop & Screen Saver > Screen Saver > Hot Corners...`
2. Configure the lower right to `Start Screen Saver`
3. Start Attract
4. Start a game

**Expected result:**

* Game starts

**Actual result:**

* Screen saver starts

**Comment by pmonks** [comment]
I suspect this is happening because attract programmatically locates the mouse pointer to the lower right corner of the screen prior to starting the emulator (MAME, in my case), which then triggers the screen saver.

What's worse is that if password-on-awake is enabled (`System Preferences > Security & Privacy > Require password immediately after sleep or screen saver begins`), it becomes impossible to enter the password into the password prompt after interrupting the screen saver - keypresses don't do anything.  My assumption is that Attract and/or MAME are grabbing the keyboard in some low-level way that prevents keystrokes from going to the password entry field, making it impossible to log back in (an undesirable hard reset being the only way out of this situation).

**Comment by estefan3112** [comment]
I confirm this behavior - and many thanks for this hint, this is actually why Attract Mode was not launching MAME. As a workaround I disabled the Hot Corner and Attract Mode/MAME works now :-).

**Comment by mickelson** [comment]
This has been an issue in the past as well: https://github.com/mickelson/attract/commit/302110a055dec534320fb3e088f13ce9d7cbb5bb#diff-fe220e33dd437766526be4116ebd76b1

I've added a "move_mouse_on_launch" setting to attract.cfg allowing you to control this in the future.
