### ISSUE TITLE
 Is it an AM bug? Evidently, yes.

### ISSUE THREAD

**Issue by zlagos** [mickelson/attract#482]
Why with this layout, the UTF-8 texts (proper characters of the Spanish language as á í ñ) are shown correctly, and yet the "wheel" does not appear. Is it an AM bug? Evidently, yes.

In the video you can check that the wheels come out of those texts that are not typical of the Spanish language.

I leave the necessary data and the video where you see the malfunction of AM:

Layout:

//------------------------------------------------
// Dimensions
local flx = fe.layout.width;
local fly = fe.layout.height;
local flw = fe.layout.width;
local flh = fe.layout.height;

// Coordinates
local text_wide = flw*0.995;
local text_tit_x = flx*0.005;
local text_tit_y = fly*0.47;

// Fonts
local font_title = "Antonio-Bold";

// Fonts sizes
local font_intp_size = flh*0.05;

 // Artist
local artist = fe.add_text("[Title]", text_tit_x, text_tit_y, text_wide, 0);
artist.font = font_title;
artist.charsize = font_intp_size;
artist.align = Align.Centre;
artist.set_rgb(255,255,255);

// Album
local album = fe.add_text("[Manufacturer]", text_tit_x, text_tit_y*1.2, text_wide, 0);
album.font = font_title;
album.align = Align.Centre;
album.charsize = font_intp_size;
album.set_rgb(255,255,255);

// Year
local year = fe.add_text("[Year]", text_tit_x, text_tit_y*1.4, text_wide, 0);
year.font = font_title;
year.align = Align.Centre;
year.charsize = font_intp_size;
year.set_rgb(255,255,255);  
 
 // Name
local artist = fe.add_text("[Name]", text_tit_x, text_tit_y*1.6, text_wide, 0);
artist.font = font_title;
artist.charsize = font_intp_size;
artist.align = Align.Centre;
artist.set_rgb(255,255,255);

 // Snap
local snap = fe.add_artwork("wheel", 200, 200, 300, 300);
snap.trigger = Transition.EndNavigation;
snap.preserve_aspect_ratio = false;

//------------------------------------------------

The font Antonio is in squirrel fonts, but you can download it here:
https://mega.nz/#!u9MnwAxb!2CXERazJCU7Wd9U1_oiAYcBkcXNex7nrdOED5QBLTqY

Romlist:

//------------------------------------------------
Alaska - The Platinum Collection - 2007;Alaska;Jukebox;;2007;The Platinum Collection;;;;;;;;;;;
Amaral - Pájaros En La Cabeza - 2005;Amaral;Jukebox;;2005;Pájaros En La Cabeza;;;;;;;;;;;
Avicii - True - 2014;Avicii;Jukebox;;2014;True;;;;;;;;;;;
Dami Im - Dami Im - 2013;Dami Im;Jukebox;;2013;Dami Im;;;;;;;;;;;
Dami Im - Heart Beats - 2014;Dami Im;Jukebox;;2014;Heart Beats;;;;;;;;;;;
Elefantes - Gracias - 2006;Elefantes;Jukebox;;2006;Gracias;;;;;;;;;;;
Francis Cabrel - Algo Mas De Amor - 2005;Francis Cabrel;Jukebox;;2005;Algo Mas De Amor;;;;;;;;;;;
Jean Michel Jarre - Magnetic Fields (Remastered 2014) - 1981;Jean Michel Jarre;Jukebox;;1981;Magnetic Fields (Remastered 2014);;;;;;;;;;;
Jean Michel Jarre - Magnetic Fields - 1981;Jean Michel Jarre;Jukebox;;1981;Magnetic Fields;;;;;;;;;;;
Jean Michel Jarre - Oxygene (New Master Recording) - 2007;Jean Michel Jarre;Jukebox;;2007;Oxygene (New Master Recording);;;;;;;;;;;
Jean Michel Jarre - Oxygene (Remastered 2014) - 1976;Jean Michel Jarre;Jukebox;;1976;Oxygene (Remastered 2014);;;;;;;;;;;
Jean Michel Jarre - Oxygene - 1976;Jean Michel Jarre;Jukebox;;1976;Oxygene;;;;;;;;;;;
Jean Michel Jarre - Oxygene 7~13 - 1997;Jean Michel Jarre;Jukebox;;1997;Oxygene 7~13;;;;;;;;;;;
Joan Manuel Serrat - Dedicado A Antonio Machado Poeta - 1969;Joan Manuel Serrat;Jukebox;;1969;Dedicado A Antonio Machado Poeta;;;;;;;;;;;
Joan Manuel Serrat - La Paloma - 1969;Joan Manuel Serrat;Jukebox;;1969;La Paloma;;;;;;;;;;;
Joan Manuel Serrat - Mediterraneo - 1971;Joan Manuel Serrat;Jukebox;;1971;Mediterraneo;;;;;;;;;;;
Joan Manuel Serrat - Mi Niñez - 1970;Joan Manuel Serrat;Jukebox;;1970;Mi Niñez;;;;;;;;;;;
Joan Manuel Serrat - Miguel Hernandez - 1972;Joan Manuel Serrat;Jukebox;;1972;Miguel Hernandez;;;;;;;;;;;
Joan Manuel Serrat - Serrat 4 - 1970;Joan Manuel Serrat;Jukebox;;1970;Serrat 4;;;;;;;;;;;
Julio Iglesias - Begin The Beguine - 1981;Julio Iglesias;Jukebox;;1981;Begin The Beguine;;;;;;;;;;;
Julio Iglesias - Soy - 1973;Julio Iglesias;Jukebox;;1973;Soy;;;;;;;;;;;
Kelly Clarkson - Piece By Piece (Deluxe Version) - 2015;Kelly Clarkson;Jukebox;;2015;Piece By Piece (Deluxe Version);;;;;;;;;;;
Miguel Ríos - Los Viejos Rockeros Nunca Mueren - 1979;Miguel Ríos;Jukebox;;1979;Los Viejos Rockeros Nunca Mueren;;;;;;;;;;;
Miguel Ríos - Memorias De Un Ser Humano - 1974;Miguel Ríos;Jukebox;;1974;Memorias De Un Ser Humano;;;;;;;;;;;
Miguel Ríos - Rocanrol Bumerang - 1980;Miguel Ríos;Jukebox;;1980;Rocanrol Bumerang;;;;;;;;;;;
Miguel Ríos - Unidos - 1971;Miguel Ríos;Jukebox;;1971;Unidos;;;;;;;;;;;
Mr Siro - Nuoc Mat Va Em - 2014;Mr Siro;Jukebox;;2014;Nuoc Mat Va Em;;;;;;;;;;;
Of Monsters And Men - Beneath The Skin - 2015;Of Monsters And Men;Jukebox;;2015;Beneath The Skin;;;;;;;;;;;
Raign - Knocking On Heavens Door - 2015;Raign;Jukebox;;2015;Knocking On Heavens Door;;;;;;;;;;;
The Alan Parsons Project - Gold Collection 1978~1985 - 1998;The Alan Parsons Project;Jukebox;;1998;Gold Collection 1978~1985;;;;;;;;;;;
The Alan Parsons Project - The Best Of The Alan Parsons Project - 1983;The Alan Parsons Project;Jukebox;;1983;The Best Of The Alan Parsons Project;;;;;;;;;;;
Tom Odell - Long Way Down - 2013;Tom Odell;Jukebox;;2013;Long Way Down;;;;;;;;;;;
//------------------------------------------------
I'm sorry, but when I cut the video it's out of sync, so I had to upload it again without cutting the start and the end. My apologies.

Video: https://www.youtube.com/watch?v=0O858rNUJkE

**Comment by zlagos** [comment]
I know that this is not a major problem for English-speaking users, but there is a significant part of non-English speaking users of attract-mode who deserve some attention ... thanks

**Comment by zlagos** [comment]
Yes, Windows 10.

**Comment by zlagos** [comment]
I closed the thread too soon, I'm sorry.

Now he does read the graphics, but he does not read the text files:

Log:

Attract-Mode v2.4.1 (Windows, SFML 2.4 +SWF) 
avcodec 57.89.100 / avformat 57.71.100 / swscale 4.6.100 / avutil 55.58.100 / swresample 2.7.100

Config: E:\arcade\attract juke\attract.cfg

*** Initializing display: 'JukeBox'
 - Loaded master romlist 'JukeBox' in 21 ms (2045 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (4090 comparisons)
Loading TXT: E:\arcade\attract juke\emulators\Jukebox.cfg
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/10CC - The Complete Hit Album - 1985.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/5000 Volts - 5000 Volts - 1979.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/ABBA - Gold - 1992.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/ABBA - Gracias Por La Música - 1979.m3u
Error opening file for reading: E:\arcade\sistemas\pinballs\jukebox\roms/ABBA - Gracias Por La Música - 1979.m3u: cannot open file
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/ABBA - Oro ~ Grandes Exitos - 1999.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/ABC - The Ultimate Collection - 2004.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/ACDC - Highway To Hell - 1979.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/ACDC - Let There Be Rock - 1977.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/ACDC - The Very Best Of ACDC - 2010.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adamo - Lo Mejor De Adamo - 2002.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adamo - Los Hits de Adamo En Castellano - 1969.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adele - 19 - 2008.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adele - 21 - 2011.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adele - Chasing Pavements - 2008.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adele - Cold Shoulder - 2008.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adele - Hometown Glory - 2008.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adele - Make You Feel My Love - 2008.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adele - Rolling In The Deep - 2011.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Adele - Skyfall - 2012.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Aerosmith - Nine Lives - 1997.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Aerosmith - Tough Love ~ Best Of The Ballads - 2011.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Aida Cuevas - Totalmente Juan Gabriel - 2013.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Air Supply - Forever Love ~ 36 Greatest Hits 1980~2001 - 2003.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Al Bano - Al Bano En Español - 1987.m3u
Error opening file for reading: E:\arcade\sistemas\pinballs\jukebox\roms/Al Bano - Al Bano En Español - 1987.m3u: cannot open file
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Al Green - Greatest Hits - 1995.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Al Stewart - Time Passages (Remastered) - 1978.m3u
Loading TXT: E:\arcade\sistemas\pinballs\jukebox\roms/Al Stewart - Time Passages - 1978.m3u

**Comment by mickelson** [comment]
Hi can you please explain, what text files are not being loaded?

I don't understand the log you have posted, it seems that your layout is trying to load m3u music files as txt files? not sure what that is about, but it may be an error in whatever layout you are using.

**Comment by zlagos** [comment]
Yes, try to read m3u files for what they are, text files, and do not read the ones with unicode characters in the name, and then in each file that does not carry unicode characters in the name, if you read the unicode characters inside from them.

The layout is a jukebox for AM and it's fine, and you can see it here: http://forum.attractmode.org/index.php?topic=2378.0

**Comment by zlagos** [comment]
Now yessssssssssssssss.

Its Ok, thanks very much.
