### ISSUE TITLE
Positioning of a layout on a different sized screen with rotation...

### ISSUE THREAD

**Issue by zpaolo11x** [mickelson/attract#490]
I think there's a bug, at least on OSX, in the way AM adapts a layout with a different aspect ratio with respect to the screen. Say you have a 16:10 screen with a 2:4 layout displayed over it in "preserve aspect ratio" mode. If you toggle rotation, the layout is partially cut off the screen and not centered. 

Sample code:

fe.layout.base_rotation = 1
fe.layout.width = 200
fe.layout.height = 400
fe.layout.preserve_aspect_ratio = true
local pippo = fe.add_text("",0,0,fe.layout.width,fe.layout.height)
local pappo = fe.add_text("A",1,1,fe.layout.width-2,fe.layout.height-2)
pippo.set_bg_rgb(250,100,0)
pappo.set_bg_rgb(50,100,0)

See the attached images for the theme with base rotation = 0 and base rotation = 1
![screen226](https://user-images.githubusercontent.com/35961910/46478784-fbc57b00-c7ed-11e8-8c12-45f549f23d29.png)
![screen227](https://user-images.githubusercontent.com/35961910/46478786-fc5e1180-c7ed-11e8-824c-e6aa2247bc00.png)

**Comment by zpaolo11x** [comment]
Confirmed the same issue on Windows, not only on Mac OS

**Comment by oomek** [comment]
Fixed in https://github.com/mickelson/attract/pull/512
Thank you for spotting that.

**Comment by oomek** [comment]
Fix merged https://github.com/mickelson/attract/pull/512
