### ISSUE TITLE
Video Overlay -Strange Behavior

### ISSUE THREAD

**Issue by sergiohinniger** [mickelson/attract#496]
Hi, i'm using attractmode on a rpi3, and Hyperspin themes. I have a collection of game themes that used to work fine. Recently a have updated AM from source and a strangething start to happen: every time a gametheme use a video overlay image, the next game that i choose show that exact video overlay... its really annoying. Thanks for the awesome work. (see below images)
![hook](https://user-images.githubusercontent.com/44624107/47755689-eec96980-dc7d-11e8-8644-b99cd0719421.jpg)
![off-road](https://user-images.githubusercontent.com/44624107/47755691-f557e100-dc7d-11e8-801f-9ce20e425c80.jpg)

**Comment by oomek** [comment]
To make sure I understand the problem correctly please clarify what do you mean by saying video overlay. Do you mean the frame that is shown on to of the video? Can you give me the link to the theme you are using please?

**Comment by oomek** [comment]
Additionaly a video showing the problem would help.

**Comment by sergiohinniger** [comment]
You're right, the video frame is the problem (i think this frame is known as video overlay in the hyperspin.nut). As you can see in the example above, the Hook theme has his own frame image, but the off-road theme (the next one on the wheel) hasn't. So the frame from Hook theme appears on the off-road theme. As long as the next theme doesn't have his own frame, the frame from Hook (or any other with a personal frame) continue to show.  I can't record the video right now, but i will as soon as i can. The link of the themes are: 
Hook: https://hyperspin-fe.com/files/file/6767-hook-world-hook-mame/
Offroad: https://hyperspin-fe.com/files/file/5779-ironman-ivan-stewarts-super-off-road-track-pak-offroadt-mame/
Hope you can understand. Thanks a lot.

**Comment by sergiohinniger** [comment]
You can test with any theme with frame and another without frame.

**Comment by oomek** [comment]
I do not have installed any hyperspin themes, so I will need you to do the investigation. Are those frames just pngs? Are they all in one folder? If the answer is yes to the above can you try to insert some dummy png file to that folder with a name  youremulatorname.png (ie mame.png or snes.png) and see if it appears on offroad? If it shows I think I know where the problem lies.

**Comment by sergiohinniger** [comment]
In the attractmode layout folder, i have a folder with the name of the emulator Display name (in the case Arcade), then inside that folder i have two other folders, one called Images (that is empty) and another called Themes, inside that folder I have game themes matching the names of the games that i own in the arcade. The process is described here: http://forum.attractmode.org/index.php?topic=1399.15 . When i get home i wil record a video and try to help.

**Comment by sergiohinniger** [comment]
Hi. Below the link to the video. As you can see the frame from one game is shown on the other. If a go back to the menu and enter again, the frame disappear.
https://youtu.be/lXACj3DKAmg

**Comment by oomek** [comment]
Message me on discord channel https://discord.gg/H5rKtq
I'm gonna to need your layout and artwork.

**Comment by oomek** [comment]
As a workaround you can add 2 lines in the hyperspin.nut file
After:
`obj2 = ::hs_ent["video_overlay"].obj;`
Add:
`if ( af2 == "" ) obj2.visible = false
else obj2.visible = true`

It needs to be investigated why `obj2.file_name = af2` is not clearing the texture when provided with the empty string.

**Comment by sergiohinniger** [comment]
The workaround worked perfectly. Thanks
