### ISSUE TITLE
SFML 2.5.0+ is causing black/white screen and font corruption on loading swf files

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#497]
~~There is a known issue with SFML 2.5.0 that is causing a black screen ( and even MSI Afterburner OSD corruption ) when loading swf files
It was fixed somwhere between https://github.com/SFML/SFML/commit/4a41f37d5d0c8b3be91205f3e4e21671a7cf3f63 and
https://github.com/SFML/SFML/commit/bb3bd05823e60785c2620482cc5ecaa2dc66798e
so it's advised to build AM against SFML 2.5.1~~

**Comment by oomek** [comment]
It seem to be something else. What I suspect is that the recent changes to SFML ( FBOs for rendertextures? ) allowed the manifestation of a problem with improper handling of mixed OpenGL and SFML draw calls without saving and restoring the GLStates. This results in overwriting random parts of the VRAM, at least on my machine with an nVidia card ( AMD driver may handle this in different manner, and I suppose RPI does not use FBOs for rendertextures )

![desktop screenshot 2018 11 04 - 11 15 25 05](https://user-images.githubusercontent.com/2974860/47963734-fd21d780-e027-11e8-8202-5d7895defa85.png)

**Comment by oomek** [comment]
I tried fixing it, but no luck so far. The changes in the SFML RenderTexture were quite radical in the 2.5.0  The only way of using sfml 2.5.0 or 2.5.1 is to make a patch that makes the function `bool RenderTextureImplFBO::isAvailable()` to always return false. I guess we have to stick with the old RT implementation until we figure out why FBOs are not playing nice with gameSWF.

**Comment by sergiohinniger** [comment]
On my raspberry pi, after play with the wheels on attract mode the videos and flash turn blank and the caracters turn to be like the image you attached.

**Comment by oomek** [comment]
I already know why this is happening. The fix is on the way, so stay tuned.

**Comment by oomek** [comment]
Fixed in https://github.com/mickelson/attract/releases/tag/v2.5.1
