### ISSUE TITLE
Feature Request: Layout-wide place-holder artwork

### ISSUE THREAD

**Issue by randombyt** [mickelson/attract#500]
Right now an artwork named after romlist acts as a place holder, this requires to create additional files even if the artwork being used is same in every case, e,g. simple snap saying missing artwork.

It would be great if we can create layout-wide place-holders. Romlist specific place-holders can over-ride layout specific place-holders keeping everything intact.

**Comment by oomek** [comment]
It's been already implemented in my wip branch whicj I'm about to push. The details explained in the following issue 
https://github.com/mickelson/attract/issues/499#issuecomment-437488271

**Comment by randombyt** [comment]
In case of romlist placeholders we can make an image in each artwork folder (snap, title, video etc). How would that work in "Missing Image Placeholders"? Will there be a single image applicable to all artwork classes or one image for each artwork class?

**Comment by oomek** [comment]
So to fix the null references in shaders I just make a 1x1 transparent snap.png and stick it into the layout folder?

**Comment by randombyt** [comment]
Thank you, that is exactly what I was looking for. I didn't knew AM already has the layout-wide placeholders in place. I just checked and 'layout/<layout-name>/<artwork>.png works as expected.

closing the issue.
