### ISSUE TITLE
Windowed and NoBorder render at display resolution

### ISSUE THREAD

**Issue by oomek** [mickelson/attract#511]
I don't know if it was intentional, or not, but in both windowed modes when you set the window to the size smaller than the current resolution the window is rendered at full monitor resolution. The fe.layout.width and height also return the display resolution. If you want to test how layout is adapting to different resolutions, for example 1280x1024, on 1920x1080 screen fonts have sampling artiffacts and the dimensions of elements set in pixels are wrong. I have a fix ready to pull in case you confirm that this wasn't intentional and should be corrected.

**Comment by oomek** [comment]
![desktop screenshot 2018 11 25 - 00 56 37 82](https://user-images.githubusercontent.com/2974860/48974383-d5ce9100-f04e-11e8-8632-929634aec5ad.png)

**Comment by zpaolo11x** [comment]
I think this is intentional, I always set both window size and layout size to a reduced size to see how it looks on smaller resolutions...

**Comment by oomek** [comment]
Even if you do so you still get at least text rendering with heavy aliasing and kerning errors. Do some screenshots in your native display resolution and for example 800x600 and compare.

Here is a video comparing the AM 2.5.1 and my daily build with a potential fix applied:
https://youtu.be/PWTbyxyvT1I

**Comment by oomek** [comment]
![attract mode 2 5 1 windowed - text aliasing](https://user-images.githubusercontent.com/2974860/49008673-52a05e80-f166-11e8-8858-59bad231cb4f.gif)

**Comment by oomek** [comment]
There is another issue I've fixed, which was bothering me for a long time. When you set your window mode to windowed or borderless and have for example 800x600 in window.am this gets reseted to the desktop resolution if you switch mode to fullscreen or fill screen, so you have to edit the file again.

**Comment by oomek** [comment]
Here is my suggestion of changes https://github.com/mickelson/attract/pull/513

**Comment by zpaolo11x** [comment]
Thinking about a workaround for this issue. and wanted to share this thought: right now my theme adapts to screen resolution, and as you said in window mode it doesn't adapt since AM still renders everything at screen res. 

Now if we fix that and the layout is rendered at the window resolution, there must be a way for me to get this value and adapt the layout to that value, for example the ScreenWidth  and ScreenHeight properties should reflect the actual window resolution, not be stuck at screen resolution.

**Comment by oomek** [comment]
This is the part of my fix. In windowed modes fe.layout.width/height will return a window size

**Comment by oomek** [comment]
No, it will not. Overriding the w&h of the layout is neccessary for layouts that are constructed on the pixel basis. In this situation the positioning of elements is based on the specified w&h but fonts are rendered based on the renderwindow size, that's why they look bad without my fix. There will be no text aliasing after my fix, whether you set your custom fe.layout.width&height or not.

**Comment by oomek** [comment]
Additionally no layout size overriding will be neccessary to test in other resolutions. You just set the desired window size in window.am, set the window mode to Windowed or No Border and that's it. I hope all os clear now. Dynamic resizing is also possible, but I need to see if I can make it without triggering the layout reload signal.

**Comment by oomek** [comment]
Fixed in https://github.com/mickelson/attract/pull/528
