### ISSUE TITLE
Wheels have random white border lines in 2.5.1

### ISSUE THREAD

**Issue by jhdgghost** [mickelson/attract#530]
![20190105_170747](https://user-images.githubusercontent.com/25726039/50726440-3c92a000-110d-11e9-80db-d19289d0c631.jpg)

AM 2.5.1 show sometimes strange white border lines in wheels. 

That is not happening in previous versions. The effect is random happen with some wheels. If you scroll the wheel several time the border effect is more evident in more games. 

Happens also in different layouts. And also i not think is the png because in previous versions i did not notice the lines.

Check the photo attached.

Kind Regards

**Comment by oomek** [comment]
Try this Photoshop plugin https://github.com/oomek/SuperPNG/releases resave one of the pngs that has this lines and report the results. If it helps I'll know if this is what I think it is.
Also would you provide a debug log and tell what hardware and system tou are running AM on please

**Comment by jhdgghost** [comment]
Hi oomek,

I did as you say i resave the file Fantasy Star Soldier (USA).png with SUPERpng plugin for photoshop but yet with the new file the borders are there (photo).

I attach also the log for my session in putty opening attract-mode with attract --loglevel debug. If there is a better way to get detailed debug log please tell me and i will do it again

Sorry my stupid mistake not telling the software or hardware. I am running last version of attract-mode in retropie 4.4 in a raspberry 3b+.

Hope it helps. 

![20190106_131610](https://user-images.githubusercontent.com/25726039/50736030-de6ec700-11b7-11e9-9cb4-a959fc2aaa88.jpg)

[putty.log](https://github.com/mickelson/attract/files/2730463/putty.log)

**Comment by oomek** [comment]
Thank you for your report. I was able to reproduce the problem. We will try to find the source of those blending errors.

**Comment by oomek** [comment]
Could you check the following branch and test if the issue with white lines on pngs border has ben resolved please? You can just simply replace the repositiry url in the update script

https://github.com/oomek/attract/tree/dev-pi

**Comment by jhdgghost** [comment]
Hi,

Just checked and the issue is perfectly fixed. 

Thanks
