### ISSUE TITLE
legacy.thegamesdb.net is no more, scraper does no longer work.

### ISSUE THREAD

**Issue by meveric** [mickelson/attract#532]
legacy.thegamesdb.net servers have been disabled.
Scraping is no longer possible.
But hey, at least everyone is having the same issue, EmulationStation also still uses the old API.

Anyway here's the official announcement:
https://forums.thegamesdb.net/viewtopic.php?f=5&t=591

But maybe this can be helpful to figure out how to solve this:
https://github.com/maloep/romcollectionbrowser/blob/master/resources/lib/pyscraper/thegamesdb_scraper.py

**Comment by LukyzCZ** [comment]
Is there any alternative for AM instead of gamesdb? Thx

**Comment by mickelson** [comment]
None right now. I will look into what is needed to update to the new api, just need some time

**Comment by mickelson** [comment]
https://forums.thegamesdb.net/viewtopic.php?f=10&t=621

**Comment by LukyzCZ** [comment]
I'm sorry for asking but is there any ETA for AM update to work with new gamedb API? Thank you

**Comment by LuckyGray7** [comment]
> https://forums.thegamesdb.net/viewtopic.php?f=10&t=621

So I just recently downloaded Attractmode so I can setup an arcade system on my arcade 1 up that I am modding, but I can't download any artwork and all my games show up as question marks because I can't scrape? do you know when this will be fixed?

**Comment by meveric** [comment]
It's been nearly 4 months..
It would be really nice to see this fixed.
ES has this fixed since early February. I'd really like to see this fixed or have an alternative for this on AM.

**Comment by oomek** [comment]
@mickelson what is the status of your API key request?

**Comment by tonberryhunter** [comment]
Any news on this?  Saddens me to see my Attract Mode build incomplete.  I have all the art and videos I just need all the game info, dates, genres, etc.

**Comment by meveric** [comment]
I found https://github.com/muldjord/skyscraper/ which can scrape for Attract Mode and use this now as a means of getting art and infos and stuff for my ROMs.
