### ISSUE TITLE
Screenchot output has two additional pixels added to height and width both

### ISSUE THREAD

**Issue by randombyt** [mickelson/attract#540]
Screenshot output has two additional pixels added to height and width. Thus a screen having dimensions 1920x1080 has the screenshot of dimensions 1922x1082.

**Comment by oomek** [comment]
The Attract Mode window in Fill Screen mode is extended in each direction off-screen by 1 pixel. What you see is normal. You can set the Full Screen mode to take the screenshots that match the display resolution.

**Comment by randombyt** [comment]
Thanks, solved.
