### ISSUE TITLE
Wrong texture_width and texture_height for video snaps with display aspect ratio

### ISSUE THREAD

**Issue by zpaolo11x** [mickelson/attract#545]
I noticed that most of my vertical videosnaps for mame are not pixel perfect in attract mode. Take the dkong.mp4 for example (you can get it from progettosnap): its pixel resolution is 224x256, the native Donkey Kong resolution, but it's displayed by players as 224x298 (anamorphic stretch to 3:4). If I load this video in attract mode i get a texture resolution of 192x256, so it seems that the texture resolution applies the display aspect ratio of 3:4 _reducing_ the horizontal dimension, not enlarging the vertical dimension. This is perfectly fine for horizontal games, but should be the other way for vertical games

**Comment by zpaolo11x** [comment]
I took the original dkong.mp4 and used MKVtoolnix to repackage it as mkv with explicit display resolution of 224x1000 (to exagerate a bit). Built a very simple layout and the result is always the same: media players show the file at correct aspect ratio (stretched) while AM reports 192x256

**Comment by oomek** [comment]
From what I quickly checked that's correct. AM applies the aspect ratio transform only to width, regardless of the resolution. MKVtoolnix does not change the stream resolution if you specify the width and height and repackage into a MKV container, it only changes the Display Pixel Aspect Ratio. Original aspect ratio is also there in MediaInfo. What are you suggesting we should do? Apply transform to height instead of width based on: ratio of the dimensions of the base stream, Display Pixel Aspect Ratio? What about streams with square resolution?

**Comment by zpaolo11x** [comment]
When you say "applies the aspect ratio transformation" is this related to "preserve_aspect_ratio = true"? Because in my experience this seems to have no impact on texture_width and height. 

I think one possible way to fix this would be to apply the stretch dependent on the "rotation": if a game has horizontal rotation it's fine to stretch it horizontally, if the game is rotated vertically it should be stretched vertically. In a CRT scanlines are the only "discreet" items, when you stretch horizontally a vertical game you get mangled scanlines because each pixel doesn't fit exactly a scanline.

Another possibility would be to disregard aspect ratio at all and provide texture_width and texture_height _before_ the display aspect ratio is applied (which means more work for me in the layout lol)

**Comment by zpaolo11x** [comment]
Jsut to be clear, my video has 224x256 pixel resolution and 224x298 display resolution (AR 3:4) but I always get texture width and height of 192x256, irregardless of preserve_aspect_ratio

**Comment by zpaolo11x** [comment]
In general terms the issue of square games is tricky: if the resolution is, say 256x256 there's no way to tell whether the game was horizontal or vertical. In most cases though this videos have a DAR set, so maybe AM could adapt the resolution taking into account the DAR as a means to drive the stretch.

Example: 

sample resolution 224 x 256, DAR 3:4 it means it's a vertical game, therefore let's not mess with the 224 scanlines and stretch the 256 pixels to 298

sample resolution 256x256 DAR 4:3 it's an horizontal game, let's enlarge the horizontal 256 pixels

etc.

**Comment by oomek** [comment]
This seems a bit more complicated. AM applies the aspect ratio to the texture on which the video is rendered to. Maybe it would be better to render the movie in the native stream resolution and apply the transform in a way you suggested to the sprite, but only if images aspect ratio is set to false.

**Comment by zpaolo11x** [comment]
That would be a possibility, if I could get the actual pixel resolutions and the actual pixel data I could do the transformations myself.

Just out of curiosity: where does AM get the aspect ratio data? From the video DAR?

**Comment by oomek** [comment]
It calculates the ratio from the image width and height after the DAR was applied to the texture on creation.

**Comment by zpaolo11x** [comment]
I see, so the DAR is applied to the texture (changing the texture width) and then the texture_width and texture_height parameters refer to that texture size with DAR applied. That's clear.

**Comment by oomek** [comment]
I'll try to make a build today evening whitch renders the video in its native resolution, exposes the overrided aspect ratio to the image class and then applies it to the sprite transform, so you won't get degraded resolution when keep aspect ratio to false and a proper aspect ratio when set to true. What platform I should build it for?

**Comment by zpaolo11x** [comment]
If you can build for macOS it would be great, I'll have time to check it the day after tomorrow though so no real hurry

**Comment by oomek** [comment]
I found both aspect ratios the original `codec_ctx->sample_aspect_ratio` and overridden `m_video->stream->sample_aspect_ratio`, so it's doable

**Comment by oomek** [comment]
Moving the aspect ratio scaling from FeMedia to FeImage is showing an improvement in the quality of videos:
![mpatrol](https://user-images.githubusercontent.com/2974860/54171442-35bc3c80-4472-11e9-942f-c7516da180ac.png)

Since videos now are decoding in their native resolutions I'm still not quite sure what should texture_width return, a native width, or with aspect ratio applied.

**Comment by zpaolo11x** [comment]
Nice improvement, let me check if I got it right: the top image applies stretch at the low resolution of the video, so we can see "blurry" pixels when the stretch happens, while the bottom image applies the stretch at the image rendering level (pardon my poor wording, I'm not sure this is the right term) so the resolution is much higher and enlarged pixels look "clean" even if they are not square. Neat.

Now could you check the effect with a video like this? http://www.progettosnaps.net/videosnaps/mp4/dkong.mp4 I'm curious to see if the stairs are clean or blulrred ;)

As for the texture_width to pass I'm not quite sure too, I think the stretched resolution would be good, but for vertical mp4s is it still stretching the horizontal resolution to apply AR?

**Comment by oomek** [comment]
Seems right to me
![dkong](https://user-images.githubusercontent.com/2974860/54226992-dce2b780-44f6-11e9-88fc-5c652a2abe36.png)

`local snap = fe.add_artwork( "snap", 0 , 0, 1024, 768 )
snap.preserve_aspect_ratio = true`

**Comment by zpaolo11x** [comment]
It looks perfect!

**Comment by oomek** [comment]
I do not have an environment set-up yet to build for OSX. Would you be interested in Windows build?

**Comment by zpaolo11x** [comment]
Sure, I have a windows installation on a virtual machine, performance won't be very good but it doesn't matter

**Comment by oomek** [comment]
https://1drv.ms/u/s!Ag7uFeM0f_fzhYhwBiJOVxlXgWbZUg

**Comment by zpaolo11x** [comment]
Just checked, video rendering is perfect and I see the texture width and height are the ones of the "unadultered" video. For some obscure reason my VM has some issue with the mame configuration so I can't check right now what happens when this videos are used with shaders like Lottes CRT, but overall this is a huge improvement.

**Comment by zpaolo11x** [comment]
Ok, I was able to check the build with GLSL shaders, it's gorgeous. Look at the screenshot attached, the scanlines align perfectly with the pixels of the video. I can't wait to have the feature in AM for Mac OS :D
<img width="359" alt="Screenshot 2019-03-13 at 11 55 05" src="https://user-images.githubusercontent.com/35961910/54274393-48289a00-4588-11e9-9637-257c4dc074dc.png">

**Comment by oomek** [comment]
https://github.com/mickelson/attract/pull/548
