### ISSUE TITLE
AM keeps focusing on frontend when game is launched at random times

### ISSUE THREAD

**Issue by arnoldsecret** [mickelson/attract#557]
No matter what I do with the settings, it seems that sometimes, the game would start, but the frontend still remains. I can however interact with the game, but the screen would focus on AM.

Intel HD Graphics
Windows x64
Hooked up to external monitor
AM 2.5.1

**Comment by oomek** [comment]
Have you tried the latest daily build?
http://forum.attractmode.org/index.php?topic=2324.0
