### ISSUE TITLE
Magic token [SortValue] is not available as fe.game_info

### ISSUE THREAD

**Issue by zpaolo11x** [mickelson/attract#558]
When a list is not sorted by name but by other parameters it is useful to extract the "Sort Value" of a game, you can use magic tokens to do it. But you can not get the SortValue as fe,game_info parameter.

Eg: game "Golden Axe" from 1982 has an [SortValue] = "Golden Axe" if the list is sorted by name, of "Sega" if ordered by manufacturer, of "1982" if ordered by year. All this data is not available as fe.game_info AFAIK

**Comment by mickelson** [comment]
Ok, added
