### ISSUE TITLE
Feature request: same layout, different options for each display

### ISSUE THREAD

**Issue by zpaolo11x** [mickelson/attract#568]
It would be great if every Display could use different "Layout Options" and not that every display with the same layout shares all the options, unless you duplicate the layout folder

**Comment by progets** [comment]
As discussed here http://forum.attractmode.org/index.php?topic=2068.msg20215#msg20215 these features exist today.

Also see https://github.com/mickelson/attract/commit/f55779e54ab04305c3604a3f0b894b5e95ce0888 and https://github.com/mickelson/attract/commit/7b1cc07f2274cca87d11e928a1fdc598d876bc6a,
