### ISSUE TITLE
fe.get_art results inconsistent when images and videos are present

### ISSUE THREAD

**Issue by zpaolo11x** [mickelson/attract#569]
I'm using fe.get_art to load artwork in an image object, I have a "snap" artwork category that contains both images and videos, the manual says to use the "Art.ImageOnly" parameter, but if I use this I get an error. If I try "Art.ImagesOnly" the result is an empty string. Is there something wrong in the implementation?

**Comment by oomek** [comment]
it's a typo in the documentation. It should be `Art.ImagesOnly`

**Comment by zpaolo11x** [comment]
I tried, but still I only get video filenames even if image snaps are there.

**Comment by oomek** [comment]
This works fine on my end:
```
local png = fe.add_text( "", 0, 0, 1000, 25 )
png.align = Align.MiddleLeft

local mp4 = fe.add_text( "", 0, 25, 1000, 25 )
mp4.align = Align.MiddleLeft

function on_transition( ttype, var, ttime ) {
	switch( ttype ) {
		case Transition.ToNewList:
		case Transition.FromOldSelection:
			png.msg = fe.get_art("snap",0 ,0 , Art.ImagesOnly)
			mp4.msg = fe.get_art("snap")
		default:
			break
	}
}

fe.add_transition_callback( "on_transition" )
```

**Comment by zpaolo11x** [comment]
Oh wow now I see, I forgot to put the "0" in filter offset!

**Comment by oomek** [comment]
Solved, so I'm closing the issue
