### ISSUE TITLE
Wrong boxart shown

### ISSUE THREAD

**Issue by Yaron2019** [mickelson/attract#577]
When using  fe.add_artwork() function and the boxart label is not set in the emulator config file, AM will look for the boxart folder in the active layout folder but will present the wrong box.

So if my emulator config file looks like this:

executable           E:/Arcade/Attract/apps/RetroArch/retroarch.exe
args                 -L cores\cap32_libretro.dll "[romfilename]"
rompath              E:/Arcade/Attract/apps/AmstradCPC
romext               .dsk;.cdt
system               Amstrad CPC
**artwork    boxart          $PROGDIR/menu-art/amstradcpc/boxart**

And I use this script to load boxart in it's theme layout file:
	**local boxart = fe.add_artwork("boxart", flx*0.005, fly*0.47 flw*0.18, flh*0.5 );**

If AM can't find boxart folder in the designated place, it will look for it in the current layout folder and if it finds the boxart folder there, it will show the wrong box.

Screenshot showing 'Double dragon' as selected game but a boxart from a different game (yaba daba doo!):
![boxart bug recreation](https://user-images.githubusercontent.com/52970692/61309800-ee97dc80-a7c0-11e9-9286-f8e6b0a1c113.JPG)

**Comment by mickelson** [comment]
This is the intended behaviour and is documented in the "Artwork" and "Artwork selection order" section of the Readme.md file.

If no boxart images are found, the frontend does check for a default boxart image in the layout directory.  If there is actually a "boxart" subdirectory, it will pick a random image from that directory
