### ISSUE TITLE
Modifying Romlists

### ISSUE THREAD

**Issue by randombyt** [mickelson/attract#579]
Hi Andrew

 Is it possible to increase the fields (headers) in romlist.txt file? The current one only caters to MAME (Rotation, Control, Status, DisplayCount, DisplayType, AltRomname, AltTitle etc). Is it possible to modify this? Like add Region, Language, Database, Series head etc? I am currently listing that info under unused heads (like Series info under Rotation head) but that creates a problem if I want to share a layout in forum and is a temporary fix.

**Comment by mickelson** [comment]
Hi there, the fields in the romlist.txt files are all hardcoded currently, so to add new fields would require changes to the frontend code.  I'm open to doing that if their are fields that are useful to people that are missing.  I'd need to know specifically what fields should be added and where the current scraper/import functions can find the information that is needed to populate them.

**Comment by randombyt** [comment]
> 
> 
> Hi there, the fields in the romlist.txt files are all hardcoded currently, so to add new fields would require changes to the frontend code. I'm open to doing that if their are fields that are useful to people that are missing. I'd need to know specifically what fields should be added and where the current scraper/import functions can find the information that is needed to populate them.

Hi, thanks. The three big ones for MAME/ Consoles are:
1. **Series:** can be derived from series.ini (part of MAME extras)
2. **Language:** can be derived from language.ini (part of MAME extras)
3. **Region:** Region is not directly accessible but there are ways like using custom dat files available on mame related websites. 

Some others easily accessible fields like:
4. **Developer:** accessible via xml files
5. **Rating:** e.g 1-5 stars etc. Either self-made or comm created (in which case can be derived from xml)
6. **Content Rating/ ESRB:** i.e. general audience/ mature etc, can be derived from hyperspin lists

Above 6 fields can also be accessed via Launchbox database xml file.

And few which I personally use:
7. **Database:** e.g. MAME (v), No-Intro, Redump etc.   
8. **Rom/ Media Format:** like cartridge, floppy, cd etc (this is primarily for computer systems having more then one rom format)
9. **Rom/ Media Count:** e.g. number of floppies
10. **Gameplay Status**: playing, completed, shortlisted (currently doing this via tags)

If empty fields in a romlist don't have any negative effect on speed/ performance then perhaps these can be added after #Buttons or maybe allow users to select between a basic (current romlist) and an advanced list with some of these fields added?

**Comment by mickelson** [comment]
Hi, thanks for the suggestions. I've added the first three fields you mention (series, language, region) as well as a rating field and the ability to import from series.ini and language.ini.  I expect the addition of fields might have some impact on speed/performance but it should be pretty minor.

**Comment by randombyt** [comment]
Thank you so much, this is perfect. Closing the issue.
