### ISSUE TITLE
Key repeat in 2.6.1 different from 2.6.0

### ISSUE THREAD

**Issue by zpaolo11x** [mickelson/attract#597]
If I load this very basic layout:
```

fe.add_ticks_callback( this, "tick" )
fe.add_signal_handler( this, "on_signal" )

function on_signal( sig ){
print(sig+"\n")
return true
}

function tick( tick_time ) {
}
```

In Attract Mode 2.6.0 if I keep the down or right button pressed I get an output like this:

right
right
right
right
right
right
right
right

while in 2.6.1 after the first "right" signal no further signals are generated while I keep the same button pressed

**Comment by oomek** [comment]
There was a bug in the previous versions of Attract Mode that has been fixed, directional signals are not repeatable. you should call repeatable command in the signal handler like:
```
function on_signal( sig )
{
	switch ( sig )
	{
		case "left":
			fe.signal( "prev_game" )
			return true

		case "right":
			fe.signal( "next_game" )
			return true
	}
}
```

and manage all your stuff in transitions.

**Comment by zpaolo11x** [comment]
Ok, I don't fully understand... let's say I don't want to call "prev_game" or "next_game" but I want to do some stuff (for example increase the fe.list.index in some way) when the "right" button is pressed, and I want this "something" to be repeated while the "right" button is pressed. It seems this is not possible in 2.6.1 am I right?

**Comment by oomek** [comment]
If you really need to bypass the AM internal acceleration and index management you can do so in tick by checking the result of  `fe.get_input_state()' function

**Comment by mickelson** [comment]
seems like that may be an unintended consequence of the bug fix.  I can look at if there is a way ti restore the earlier behaviour (making directions ‘repeatable)

Andrew

**Comment by oomek** [comment]
Would it be even possible without breaking keyrepeat and transitions of this?
https://github.com/mickelson/attract/issues/597#issuecomment-576871235

**Comment by oomek** [comment]
Btw, previous keyrepeat of directional keys was way too fast and did not react to `selection_speed_ms`

**Comment by mickelson** [comment]
it may not be possible...  I’ll still take a look

**Comment by zpaolo11x** [comment]
Well in my layout I have some code to control the repeat speed of left and right  triggers, so if there was a way to switch repeating on and off  from the layout it would be great. 
I’ll look into the new behavior to see if I can fix the layout to use it

**Comment by zpaolo11x** [comment]
If I use the code by Oomek it works, next/prev game repeats even if the right signal doesn't repeat, but if I want to do something different in the "prev_game" "next_game" signal response and I use this code:

`
fe.add_signal_handler( this, "on_signal" )
fe.add_transition_callback( this, "on_transition" )
fe.add_ticks_callback( this, "tick" )

function on_transition( ttype, var0, ttime ) {
}

function tick( tick_time ) {
}

function on_signal( sig ){
	print ("Signal: " + sig + "\n" )
   	switch ( sig )
	{
		case "left":
			fe.signal( "prev_game" )
			return true

		case "right":
			fe.signal( "next_game" )
			return true

		case "prev_game":
			fe.list.index --
			return true

		case "next_game":
			fe.list.index ++
			return true
	}
}`

it doesn't repeat anymore. So basically the only way to make something repeat is to stick with the "vanilla" next_game or next_page or next_letter routines managed by AM. 

This is important to me because my layout acts in ways that are far from "standard" in AM: I have 10 tiles on screen in two rows, and when one goes left or right it changes the list index by +/-2 to keep the movement correct. I could use next_page and prev_page with a step of 2 but I actually use next_page and prev_page to skip whole screens, that is +10 or -10 on the list index. I let the user set its own hotkeys for prev/next game (going zig zag through the games shown) or next/prev page (skipping whole screens) but left and right are bound to +number of rows -number of rows.

Of course I'll try to hack the "next_page" signal response to accomodate all this cases but it would be much easier for me to have repeatable "left" "right" signal responses and keep managing the repeat flow as I do now ;D

**Comment by zpaolo11x** [comment]
Ok, no worries, I've found a quite decent workaround that seems to work in 2.6.0 and 2.6.1, I'm implementing it for most signals and if everything goes right there's no need to change anything in 2.6.2 :)
