### ISSUE TITLE
Missing artwork Bug after "Cache artwork paths" Commit

### ISSUE THREAD

**Issue by randombyt** [mickelson/attract#602]
A bug has been introduced after "Cache artwork paths" commit. When an artwork is missing, the last available artwork is shown rather then showing it empty. This also ignores place-holder items for missing artwork. 

This is only happening with artwork, calling artwork directly (fe.add_image) does not exhibit this behavior and works normally i.e. empty is shown empty and last available image is not used.

This is similar to issue #499

**Comment by mickelson** [comment]
Thanks for finding that, it should be fixed now
