### ISSUE TITLE
Add Kms or gles support for pi 4

### ISSUE THREAD

**Issue by saitoh00** [mickelson/attract#603]
Hello, its needed these support for use it in raspberry pi 4 without x11, example : launch from retropie or include it.

**Comment by kwyxz** [comment]
Duplicate of #575

**Comment by fczuardi** [comment]
Well, after https://github.com/mickelson/attract/issues/575#issuecomment-622987074 it looks like this is not a duplicate anymore, due to a bad title on #575

**Comment by kwyxz** [comment]
My bad : duplicate of #576
