### ISSUE TITLE
Image won't boot the first time!

### ISSUE THREAD

**Issue by lggarcia** [mickelson/attract#604]
I don't know if I'm supposed to create a thread, or if it's here the right place, but here we go !

I recently downloaded the floob-retropie-attractmode-v05-23-AUG-2016 for Raspberry Pi 3B+, as it's appear to be the last version of it available and create a image using balena etcher on debian 10. 

When I plug it in the RPI with a keyboard and mouse wireless combo, ethernet and a controler (tested 2 differents raspberrys, tested other images on this SanDisk Ultra 128Gb class 10 A1 sdcard XC and tested to boot only with HDMI and power), it just won't boot. the screen just stays black and do nothing (waited more then 10 minutes expecting something like file expansion or whatever)...

what can it be ? can anyone help me???

tested as well the floob-retropie-attractmode-v04-07-MAY-2016 version and the Ptiwee's Buildroot (AM + RetroArch) Image as well ...

**Comment by oomek** [comment]
Definitely a wrong repository. This repo holds an Attract Mode launcher and is not in any way afiliated with Retropie
