### ISSUE TITLE
Problem with titles contain " ; "

### ISSUE THREAD

**Issue by duy64** [mickelson/attract#605]
This game "Odekake Lester - Lelele no Le (^^; (Japan)" for super nintendo would not register in the rom list correctly, it will show as " (Japan)" ". Manually change it works, but will reverse when reopen attract mode again. This is on Windows 10, Attract Mode v2.6.1.

**Comment by randombyt** [comment]
In AM romlists semicolon ( ; ) means ending one field and starting next. You can rename the "Name" and "Title" so semicolon is not used. Easiest way would be to close AM and open systemname.txt in AM/romlists to rename both Name and Title.

**Comment by duy64** [comment]
I'm aware of the " ; " being used to end a field, but the point is I should be able to name my game with any characters. I'm not sure how hard it is to make the program recognize "quotes" so that I can use any characters in the title.

**Comment by duy64** [comment]
This is what AM generated in the rom list but never actually showed up correctly on screen.
This is why I reported this a bug since the program was designed to use "quotes" but did work properly.


"Odekake Lester - Lelele no Le (^^; (Japan)";"Odekake Lester - Lelele no Le (^^; (Japan)";Super Nintendo; ;;;;;;;;;;;;;;;;;

**Comment by keilmillerjr** [comment]
http://adb.arcadeitalia.net/dettaglio_mess.php?software_name=odekake&software_list=snes

Bizzare title, and likely to not run into again. I suggest changing romlist manually, or using the parent rom lester.

Issue with correcting this: What would you use as a single line delimiters? You could use multi-line like history.dat? Or perhaps we can escape the character.

**Comment by mickelson** [comment]
should be fixed now, thanks for reporting
