### ISSUE TITLE
> I just downloaded and ran 2.5.1 as beccobunsen recommended.

### ISSUE THREAD

**Issue by beccobunsen** [mickelson/attract#607]
> I just downloaded and ran 2.5.1 as beccobunsen recommended.
> I worked.

try 2.6.1 with win7 compatibily on

**Comment by oomek** [comment]
You've just accidentaly opened a new issue, please close it and respond in
https://github.com/mickelson/attract/issues/606

**Comment by bazarte** [comment]
> > I just downloaded and ran 2.5.1 as beccobunsen recommended.
> > I worked.
> 
> try 2.6.1 with win7 compatibily on

Win 7 Compatibility, no change.

**Comment by kruezbergbier** [comment]
Touching lesson uno

**Comment by kruezbergbier** [comment]
Touching lesson uno
