### ISSUE TITLE
PNG files larger than 8bit?

### ISSUE THREAD

**Issue by Luke-Nukem** [mickelson/attract#63]
Every once in a while I get an error relating to a PNG file, for example;

Failed to load image "../vulgus_art/snap/exerion.png". Reason : PNG not supported: 8-bit only

It wouldn't be an issue if it was easy for me to track which ones cause this error, and edit them to be 8bit instead of 16 or 24 bit. There is just a few too many.
How easy would it be to allow loading of higher quality?

**Comment by h0tw1r3** [comment]
I rebuild SFML with an updated stb_image library (2.0) which supports 1/2/4-bit PNG's.  While it does load all the PNG's, it's also slow for some reason.  When using the default layout, it hangs (on my machine) when scrolling quickly through the list.

**Comment by h0tw1r3** [comment]
Patching SFML v2.2 works like a charm.  I had to patch it anyways because there is a bug with video mode reporting the correct X & Y pixels when a screen is rotated (randr).  Not sure if it affects windows.
https://github.com/LaurentGomila/SFML/issues/771

**Comment by mickelson** [comment]
great, thanks h0tw1r3, I'll follow the SFML thread you linked, it will be good to get this one fixed!

**Comment by eXpl0it3r** [comment]
> I rebuild SFML master branch with an updated stb_image library (2.0) which supports 1/2/4-bit PNG's. It load's all PNG's just fine.

Just FYI: `stb_image` will be get officially updated for SFML 2.3 see [here](http://en.sfml-dev.org/forums/index.php?topic=17176.0). :wink:

**Comment by h0tw1r3** [comment]
My SFML 2.2 branch with an updated stb_image library (this will never be merged upstream):
https://github.com/h0tw1r3/SFML/tree/backport/2.2

Pull request for upcoming SFML 2.3 (WIP):
https://github.com/LaurentGomila/SFML/pull/777

**Comment by mickelson** [comment]
I believe this is fixed now.  Attract-Mode by default now uses FFmpeg to load images, which supports these other png formats.

Alternatively there is a compile flag to still use SFML for image loading (it seems to be a bit faster) and with h0tw1r3's patches now in SFML 2.3 it will be fixed if you use SFML >=2.3

**Comment by Enverex** [comment]
Should this still be happening?

> Failed to load image "/home/arcade/.attract/layouts/arcade/logo/Nintendo 64.png". Reason: PNG not supported: 1/2/4/8-bit only

**Comment by Enverex** [comment]
Another example:

`Failed to load image "/mnt/store/Emulation/Assets/Live/Sega_Genesis/Wheel/Top Gear 2 (USA).png". Reason: PNG not supported: 1/2/4/8-bit only`

But the image is 16bit which given the earlier comments, should be supported:

`/mnt/store/Emulation/Assets/Live/Sega_Genesis/Wheel/Top Gear 2 (USA).png PNG 297x175 297x175+0+0 16-bit sRGB 78.7KB 0.000u 0:00.000`
