### ISSUE TITLE
Error loading images with exclamation in bracktes on its name. [!]

### ISSUE THREAD

**Issue by Ryback2501** [mickelson/attract#630]
I got errors when loading an image with an exclamation mark in brackets.

**Example:** Contra III - The Alien Wars (U) [!].jpg

The information about the image is wrong. For example, texture_width and_texture_height are zero.

I'm loading this image as a normal image, **not as artwork**.

**Comment by mickelson** [comment]
I can't reproduce here, loading normal images with a exclamation in brackets works for me.

**Comment by Ryback2501** [comment]
Hello again and sorry for insisting. Here's more information about the issue:

I'm creating [a theme](https://github.com/Ryback2501/TendoMode/releases/tag/0.3) that uses [this module](https://github.com/Ryback2501/wafam/releases/tag/0.3). Someone reported me this bug recently. Here's the [link to the issue](https://github.com/Ryback2501/TendoMode/issues/1).

**Comment by Ryback2501** [comment]
I have uploaded a basic layout.nut code to test the problem. The code is on Pastebin ([link here](https://pastebin.com/5ig0Le60)).

To test it, run the layout and check the lat_run.log file. ([her there is an example o a test I ran](https://pastebin.com/B6WVpasj)).
