### ISSUE TITLE
Can't generate romlists

### ISSUE THREAD

**Issue by placeboyue** [mickelson/attract#643]
I tried fresh downloads of the last two builds and it still happens, the overwrite of an existing romlist does nothing, and creating a new romlist does not create a new .txt file on the romlist folders. Creating a new emulator also does not create it's romlist.

What's going on?? i don't know if it's an issue on my end, it started happening out of nowhere. I tried running the app as admin and everything else i can think of but no difference.

**Comment by keilmillerjr** [comment]
What's your log say?

**Comment by placeboyue** [comment]
It was my antivirus preventing AM from doing any changes to any files on my desktop files, since desktop was flagged as protected content.. for some reason that behaviour started out of nowheree the day i wrote that, never had trouble with it before.

Sorry, no problems since, there's no bug.
