### ISSUE TITLE
Attract Mode wont start Windows 10

### ISSUE THREAD

**Issue by tonberryhunter** [mickelson/attract#663]
GPU GeForce GTX 970 
Driver Version 457.09

Windows 10 64 bit

![attract error](https://user-images.githubusercontent.com/49738515/98230377-0e5c9200-1f29-11eb-8577-81c9ea7225fc.png)

**Comment by oomek** [comment]
Debug log please.

**Comment by tonberryhunter** [comment]
last_run.log?

**Comment by tonberryhunter** [comment]
Attract-Mode v2.6.1 (Windows, SFML 2.5.1 +SWF +7z +Curl) 
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

**Comment by oomek** [comment]
`attract.exe --loglevel debug`

**Comment by tonberryhunter** [comment]
I dont ever run anything from cmd in Windows Im gonna have to refresh my memory on how to do it.

**Comment by tonberryhunter** [comment]
Attract-Mode v2.6.1 (Windows, SFML 2.5.1 +SWF +7z +Curl) 
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

NvAPI: nvapi64.dll loaded

**Comment by oomek** [comment]
Seems like Nvidia broke nvapi again. The same error was popping up on Quadro cards before. I think I have some older Nvidia card on hand. I hope the new driver works on it.

**Comment by oomek** [comment]
Try the following workaround in the meantime.
https://github.com/mickelson/attract/issues/606#issuecomment-609484735

**Comment by tonberryhunter** [comment]
> Try the following workaround in the meantime.
> [#606 (comment)](https://github.com/mickelson/attract/issues/606#issuecomment-609484735)

Didnt work

**Comment by oomek** [comment]
Attract Mode works on my card with the latest driver. Go to `C:\Windows\System32` and check version of `nvapi64.dll please
![image](https://user-images.githubusercontent.com/2974860/98242295-23a2e200-1f64-11eb-9041-e3f5be681486.png)

**Comment by tonberryhunter** [comment]
Looks the same as mine 
![dll](https://user-images.githubusercontent.com/49738515/98281805-3d93f300-1f6b-11eb-8088-919b001e23a4.png)

**Comment by oomek** [comment]
Could you try nightly build and report?
http://www.dabone.xyz/attract/attract-daily.zip

**Comment by tonberryhunter** [comment]
> Could you try nightly build and report?
> http://www.dabone.xyz/attract/attract-daily.zip

The daily build fixed the issue.  I was using the version from the homepage http://attractmode.org/about.html

Maybe someone should update it with this newer version.

**Comment by oomek** [comment]
Fixed in b0d5424038218885fdd9be90ec07620ab578e97f
