### ISSUE TITLE
Attract mode not supporting resolution set in config.txt

### ISSUE THREAD

**Issue by SKYNET2023** [mickelson/attract#667]
I am running a pi 4 in an arcade cabinet with a CRT Monitor which requires the 800x600 60Hz 4:3 Resolution (hdmi_group=2, mode 9) in the pi's config.txt file.

The command line, Emulation Station and multiple emulators support this video mode without issue. However, Attract Mode shows video in a very distorted and scrambled manor, almost as if sync was not working correctly. 

I believe this issue is specific to the pi 4 because I was previously using those same settings in Attract Mode on a pi 3B+ build for years without issue.

Please help me finish my pi 4 upgrade!

**Comment by oomek** [comment]
On PI4 Attract Mode by default will open in maximum resolution reported by the display. Please refer to SFML-PI readme to se gow to override the resolution and refresh rate using environmental variables
https://github.com/mickelson/sfml-pi/blob/aeefcd461348cf344afbc2a89f170116ee854744/readme.md

**Comment by tonberryhunter** [comment]
> On PI4 Attract Mode by default will open in maximum resolution reported by the display. Please refer to SFML-PI readme to see how to override the resolution and refresh rate using environmental variables
> https://github.com/mickelson/sfml-pi/blob/aeefcd461348cf344afbc2a89f170116ee854744/readme.md

Why not build resolution options into Attract Mode?  I've also found this to be quite annoying trying to run Attract Mode with a display that natively runs at 1024 x 768 but reports up to 1080p.

**Comment by oomek** [comment]
Resolution selection will come eventually. For the time being your option is to set the env var.

**Comment by SKYNET2023** [comment]
I read the article you shared, thank you for that! However, I am still unsure exactly how to set the environmental variables. I noticed that the readme had the four "SFML_DRM..." commands which can be used to set the device, video mode, refresh rate etc. but what file do I open to add that in? Also, can you give me an example of a full command? For example, if I want to set a video mode, what else do I need to add to "SFML_DRM_MODE"?

**Comment by oomek** [comment]
Type in the console:
`SFML_DRM_MODE=800x600 SFML_DRM_REFRESH=60 attract`
or:
`export SFML_DRM_MODE=800x600
export SFML_DRM_REFRESH=60`
then launch `attract`
to make it remember until console session is active.

**Comment by SKYNET2023** [comment]
It worked! Thanks so much.
