### ISSUE TITLE
How to use mamewah themes

### ISSUE THREAD

**Issue by mlcampbe** [mickelson/attract#674]
I see there is a mamewah.nut file in /usr/local/share/attract/loader but not sure how to use it. I have a layout.lay file from a mamewah theme (along with the corresponding jpg files for main, message, & options). When I select that theme from the list all I get is a while screen.

Any ideas?

**Comment by oomek** [comment]
Your best chance of geting an answer to that is our forum http://forum.attractmode.org/
This section is for reporting bugs and issues.
