### ISSUE TITLE
Search bug and fix

### ISSUE THREAD

**Issue by Yaron2019** [mickelson/attract#678]
Searching for a game while wheel is located on the first game in the list results in AM not updating the first wheel logo, the snap and any other art related to the first result in the list. This bug occurs in both the search module shown in the following video and the built-in AM search plugin.

This is fixed by altering line 1510 in function `FePresent::set_search_rule` , in file fe_present.cpp from:
`update_to_new_list( 0 );`
To:
`update_to_new_list( 0, true );`

Video of the issue:
https://youtu.be/Iz-ix4664hQ

**Comment by mickelson** [comment]
Hey thanks for the fix!
