### ISSUE TITLE
Suspected ffmpeg memory leak 

### ISSUE THREAD

**Issue by YaronAM** [mickelson/attract#717]
Even though you have stopped responding to users posting issues, I will do this one last post. 
After your latest 2.6.2 commits, if you leave AM running for a couple of hours randomly shuffling through video snaps, the memory usage grows and is not released. 4 hours of random wheel navigation results in about 700MB RAM usage on my PC. Before 2.6.2 it would have stayed under 200MB. Image Cache size is set to 0. No background loading. There is a video related memory leak for sure and the worst thing to do is continue to pile code on top of it.

I wish you all the best and goodbye,
Yaron

**Comment by mickelson** [comment]
Should be fixed now, thanks for the report!
