### ISSUE TITLE
Media Layout request

### ISSUE THREAD

**Issue by omegaman1** [mickelson/attract#73]
How hard would it be to create a layout similar to AppleTV guide.  Here is what I had in mind. A horizontal list of artwork like carts or boxes equally spaced across the bottom. A snap in a fixed position, in the upper left for example. Game info would be aligned right of snap. I guess this would be similar to XBMC as well but more flexible. I tried to mangle some of the orbit code but couldn't quite get the desired result I wanted. I think this could be the layout that rules them all if implemented right.

**Comment by mickelson** [comment]
An apple tv-style layout would be great, but I'm going to close this issue and keep this bug tracker focused on the core software... this discussion can be continued in the layouts discussion over at the forum.
