### ISSUE TITLE
Suggestion : filter_offset for layout

### ISSUE THREAD

**Issue by checkist84** [mickelson/attract#87]
Basically my goal is very similar to #75..

We currently have 'index_offset' for handling previous/next game indices.
My suggestion is that we have additional 'filter_offset' for handling previous/next filter indices.

The filter_offset works similar fashion with 'index_offset', with higher priority than index_offset like:

filter_offset : -1  /  index_offset : 0
-> [previous filter]'s [current_game], in other words, what we see after pressing 'prev_filter' key

filter_offset : +1 / index_offset : 1
-> [next filter]'s [next game]

Corresponding text's 'msg' fields may be substituted as well (including [ListSize], [ListFilterName], and so on), just like 'index_offset'

And, 'Transition.ToNewFilter / Transition.FromOldFilter' can be added 'add_transition_callback', for enabling transitional effects for filter changing. Values of '-1 / +1' can indicate whether the user has pressed 'previous filter' or 'next filter' key..

**Comment by mickelson** [comment]
this one's almost ready to go, it's going to need some serious testing since it fundamentally changes how filters are handled...

its looking pretty good atm though!
