### ISSUE TITLE
Hang while loading videos

### ISSUE THREAD

**Issue by liquid8d** [mickelson/attract#96]
I am loading video snaps from a network location, so it's understandable there could be a delay. However, it seems to occasionally cause the app to hang until the video has started. Is it possible for the loading to be done in a thread, if that would help the issue? My hope is it would still process the UI stuff while loading the video.

**Comment by popoklo** [comment]
In general, theres a problem with loading snaps, even if theyre small size, which causes sloppy animations ie. Is there a possibility to "stream pics" like a webpage with many pics not influencing animation or scrolling Animation?

**Comment by mickelson** [comment]
Closing as duplicate of https://github.com/mickelson/attract/issues/179
