### ISSUE TITLE
Starting directly into Attract-Mode

### ISSUE THREAD

**Issue by akufox** [mickelson/attract#97]
As you need X Windows to run mame if you want to use a frontend (other than advancemenu) then you need a GUI thing is a GUI eats up resourses and when you are using a low ram/cpu combo for your mame cab it can be vital to have as much as you can! I was using lubuntu. The desktop enviorment takes up ram and is hard to hide. It is based on Openbox though so I found out that you can do this to start directly into Attract-Mode:

Go to /home/(your user name)/.config/openbox and create a new document 
this is what I have in mine:
#set background
#start attract mode

xsetroot & <- this "blacks the screen (background)
attract <- this starts attract-mode

you can add other things too but that just makes a simple one to start. My "cab" starts right into attract mode and starts antimicro I never see any desktop envirement at all! :)
I tried to change the boot logo so that you don't see "lubuntu" on start up but I just managed to delete it..but t least it's blank! lol hope this helps someone!

**Comment by h0tw1r3** [comment]
It's actually easier than that, and you don't need to install a window manager (like openbox).
Minimal install X11 with the xinitrc package (different for each distro).

    $ echo "exec attract" > ~/.xinitrc
    $ startx
