### ISSUE TITLE
Pausing and stuttering when artwork is on a network resource

### ISSUE THREAD

**Issue by shade99gt** [mickelson/attract#98]
I have my artwork (snaps, titles, flyers, etc) on a NAS device and Attract-Mode stutters and pauses when scrolling through games.  This also prevents rapid scrolling from occurring (such as when Up or Down is held).

I realize there is increased time to access the artwork files on a network share, but perhaps the following methods can be used to solve the issue:

1) Don't attempt to load a new flyer, snap or video until Up or Down is released.  
2) Don't wait for artwork to load when scrolling between games in the list.

In the above scenarios, perhaps it simply a "busy" or "loading" marquee and snap can be specified in the config file, or it defaults to a black screen for the snap and the default layout marquee or emulator marquee until the artwork loads. That way, the user can scroll between games as fast as they want without having to wait for new artwork to load.

This is with the Win32 version of Attract-Mode using Windows 7 Pro x64.

**Comment by mickelson** [comment]
Duplicate issue:
https://github.com/mickelson/attract/issues/96
